
var createFFmpegCore = (function() {
  var _scriptDir = typeof document !== 'undefined' && document.currentScript ? document.currentScript.src : undefined;
  if (typeof __filename !== 'undefined') _scriptDir = _scriptDir || __filename;
  return (
function(createFFmpegCore) {
  createFFmpegCore = createFFmpegCore || {};


function e(){h.buffer!=l&&aa(h.buffer);return ba}function ca(){h.buffer!=l&&aa(h.buffer);return da}function ea(){h.buffer!=l&&aa(h.buffer);return fa}function t(){h.buffer!=l&&aa(h.buffer);return ha}function u(){h.buffer!=l&&aa(h.buffer);return ia}function ja(){h.buffer!=l&&aa(h.buffer);return ka}var x;x||(x=typeof createFFmpegCore !== 'undefined' ? createFFmpegCore : {});var la,ma;x.ready=new Promise(function(a,b){la=a;ma=b});x.quit=function(a){if(x.onExit)x.onExit(a);throw new na(a);};x.exit=oa;
pa=z=function(){};var qa={},ra;for(ra in x)x.hasOwnProperty(ra)&&(qa[ra]=x[ra]);var sa=[],ta="./this.program";function ua(a,b){throw b;}var va=!1,A=!1,B=!1,wa=!1;va="object"===typeof window;A="function"===typeof importScripts;B="object"===typeof process&&"object"===typeof process.versions&&"string"===typeof process.versions.node;wa=!va&&!B&&!A;var C=x.ENVIRONMENT_IS_PTHREAD||!1,D="";function xa(a){return x.locateFile?x.locateFile(a,D):D+a}var ya,za,Aa,Ba,Ca;
if(B){D=A?require("path").dirname(D)+"/":__dirname+"/";ya=function(a,b){Ba||(Ba=require("fs"));Ca||(Ca=require("path"));a=Ca.normalize(a);return Ba.readFileSync(a,b?null:"utf8")};Aa=function(a){a=ya(a,!0);a.buffer||(a=new Uint8Array(a));assert(a.buffer);return a};1<process.argv.length&&(ta=process.argv[1].replace(/\\/g,"/"));sa=process.argv.slice(2);process.on("uncaughtException",function(a){if(!(a instanceof na))throw a;});process.on("unhandledRejection",E);ua=function(a){process.exit(a)};x.inspect=
function(){return"[Emscripten Module object]"};var Da;try{Da=require("worker_threads")}catch(a){throw console.error('The "worker_threads" module is not supported in this node.js build - perhaps a newer version is needed?'),a;}global.Worker=Da.Worker}else if(wa)"undefined"!=typeof read&&(ya=function(a){return read(a)}),Aa=function(a){if("function"===typeof readbuffer)return new Uint8Array(readbuffer(a));a=read(a,"binary");assert("object"===typeof a);return a},"undefined"!=typeof scriptArgs?sa=scriptArgs:
"undefined"!=typeof arguments&&(sa=arguments),"function"===typeof quit&&(ua=function(a){quit(a)}),"undefined"!==typeof print&&("undefined"===typeof console&&(console={}),console.log=print,console.warn=console.error="undefined"!==typeof printErr?printErr:print);else if(va||A)A?D=self.location.href:"undefined"!==typeof document&&document.currentScript&&(D=document.currentScript.src),_scriptDir&&(D=_scriptDir),0!==D.indexOf("blob:")?D=D.substr(0,D.lastIndexOf("/")+1):D="",B?(ya=function(a,b){Ba||(Ba=
require("fs"));Ca||(Ca=require("path"));a=Ca.normalize(a);return Ba.readFileSync(a,b?null:"utf8")},Aa=function(a){a=ya(a,!0);a.buffer||(a=new Uint8Array(a));assert(a.buffer);return a}):(ya=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},A&&(Aa=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),za=function(a,b,c){var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";
d.onload=function(){200==d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)});B&&"undefined"===typeof performance&&(global.performance=require("perf_hooks").performance);var pa=x.print||console.log.bind(console),z=x.printErr||console.warn.bind(console);for(ra in qa)qa.hasOwnProperty(ra)&&(x[ra]=qa[ra]);qa=null;x.arguments&&(sa=x.arguments);x.thisProgram&&(ta=x.thisProgram);x.quit&&(ua=x.quit);var Ea,Fa=0,Ga;x.wasmBinary&&(Ga=x.wasmBinary);
var noExitRuntime=x.noExitRuntime||!0;"object"!==typeof WebAssembly&&E("no native wasm support detected");var h,Ha,Ia=!1;function assert(a,b){a||E("Assertion failed: "+b)}function Ja(a){var b=x["_"+a];assert(b,"Cannot call unknown function "+a+", make sure it is exported");return b}
function Ka(a,b,c,d){var f={string:function(p){var r=0;if(null!==p&&void 0!==p&&0!==p){var y=(p.length<<2)+1;r=La(y);Ma(p,r,y)}return r},array:function(p){var r=La(p.length);Na(p,r);return r}},g=Ja(a),k=[];a=0;if(d)for(var m=0;m<d.length;m++){var q=f[c[m]];q?(0===a&&(a=F()),k[m]=q(d[m])):k[m]=d[m]}c=g.apply(null,k);c=function(p){return"string"===b?I(p):"boolean"===b?!!p:p}(c);0!==a&&J(a);return c}
function Oa(a){var b=new TextDecoder(a);this.decode=function(c){c.buffer instanceof SharedArrayBuffer&&(c=new Uint8Array(c));return b.decode.call(b,c)}}var Pa="undefined"!==typeof TextDecoder?new Oa("utf8"):void 0;
function Qa(a,b,c){var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.subarray&&Pa)return Pa.decode(a.subarray(b,c));for(d="";b<c;){var f=a[b++];if(f&128){var g=a[b++]&63;if(192==(f&224))d+=String.fromCharCode((f&31)<<6|g);else{var k=a[b++]&63;f=224==(f&240)?(f&15)<<12|g<<6|k:(f&7)<<18|g<<12|k<<6|a[b++]&63;65536>f?d+=String.fromCharCode(f):(f-=65536,d+=String.fromCharCode(55296|f>>10,56320|f&1023))}}else d+=String.fromCharCode(f)}return d}function I(a){return a?Qa(ca(),a,void 0):""}
function Ra(a,b,c,d){if(!(0<d))return 0;var f=c;d=c+d-1;for(var g=0;g<a.length;++g){var k=a.charCodeAt(g);if(55296<=k&&57343>=k){var m=a.charCodeAt(++g);k=65536+((k&1023)<<10)|m&1023}if(127>=k){if(c>=d)break;b[c++]=k}else{if(2047>=k){if(c+1>=d)break;b[c++]=192|k>>6}else{if(65535>=k){if(c+2>=d)break;b[c++]=224|k>>12}else{if(c+3>=d)break;b[c++]=240|k>>18;b[c++]=128|k>>12&63}b[c++]=128|k>>6&63}b[c++]=128|k&63}}b[c]=0;return c-f}function Ma(a,b,c){return Ra(a,ca(),b,c)}
function Sa(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&(d=65536+((d&1023)<<10)|a.charCodeAt(++c)&1023);127>=d?++b:b=2047>=d?b+2:65535>=d?b+3:b+4}return b}"undefined"!==typeof TextDecoder&&new Oa("utf-16le");function Ta(a){var b=Sa(a)+1,c=K(b);c&&Ra(a,e(),c,b);return c}function Ua(a){var b=Sa(a)+1,c=La(b);Ra(a,e(),c,b);return c}function Na(a,b){e().set(a,b)}function Va(a,b,c){for(var d=0;d<a.length;++d)e()[b++>>0]=a.charCodeAt(d);c||(e()[b>>0]=0)}
var l,ba,da,fa,Wa,ha,ia,Xa,ka;C&&(l=x.buffer);function aa(a){l=a;x.HEAP8=ba=new Int8Array(a);x.HEAP16=fa=new Int16Array(a);x.HEAP32=ha=new Int32Array(a);x.HEAPU8=da=new Uint8Array(a);x.HEAPU16=Wa=new Uint16Array(a);x.HEAPU32=ia=new Uint32Array(a);x.HEAPF32=Xa=new Float32Array(a);x.HEAPF64=ka=new Float64Array(a)}var $a=x.INITIAL_MEMORY||536870912;
if(C)h=x.wasmMemory,l=x.buffer;else if(x.wasmMemory)h=x.wasmMemory;else if(h=new WebAssembly.Memory({initial:$a/65536,maximum:32752,shared:!0}),!(h.buffer instanceof SharedArrayBuffer))throw z("requested a shared WebAssembly.Memory but the returned buffer is not a SharedArrayBuffer, indicating that while the browser has SharedArrayBuffer it does not have WebAssembly threads support - you may need to set a flag"),B&&console.log("(on node you may need: --experimental-wasm-threads --experimental-wasm-bulk-memory and also use a recent version)"),
Error("bad memory");h&&(l=h.buffer);$a=l.byteLength;aa(l);var L,ab=[],bb=[],cb=[],db=[];function eb(){C||(x.noFSInit||M.Lc.yd||M.Lc(),M.ge=!1,N.root=M.Ob(N,{},null),fb(bb))}function gb(){var a=x.preRun.shift();ab.unshift(a)}var hb=0,ib=null,jb=null;function kb(){assert(!C,"addRunDependency cannot be used in a pthread worker");hb++;x.monitorRunDependencies&&x.monitorRunDependencies(hb)}
function lb(){hb--;x.monitorRunDependencies&&x.monitorRunDependencies(hb);if(0==hb&&(null!==ib&&(clearInterval(ib),ib=null),jb)){var a=jb;jb=null;a()}}x.preloadedImages={};x.preloadedAudios={};function E(a){if(x.onAbort)x.onAbort(a);C&&console.error("Pthread aborting at "+Error().stack);z(a);Ia=!0;a=new WebAssembly.RuntimeError("abort("+a+"). Build with -s ASSERTIONS=1 for more info.");ma(a);throw a;}function mb(){return O.startsWith("data:application/octet-stream;base64,")}var O;O="ffmpeg-core.wasm";
mb()||(O=xa(O));function nb(){var a=O;try{if(a==O&&Ga)return new Uint8Array(Ga);if(Aa)return Aa(a);throw"both async and sync fetching of the wasm failed";}catch(b){E(b)}}
function ob(){if(!Ga&&(va||A)){if("function"===typeof fetch&&!O.startsWith("file://"))return fetch(O,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+O+"'";return a.arrayBuffer()}).catch(function(){return nb()});if(za)return new Promise(function(a,b){za(O,function(c){a(new Uint8Array(c))},b)})}return Promise.resolve().then(function(){return nb()})}
var Q,R,qb={5410468:function(){throw"Canceled!";},5410486:function(a,b){setTimeout(function(){pb(a,b)},0)}};function fb(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b(x);else{var c=b.Nf;"number"===typeof c?void 0===b.Kc?L.get(c)():L.get(c)(b.Kc):c(void 0===b.Kc?null:b.Kc)}}}
function rb(a,b){if(0>=a||a>e().length||a&1||0>b)return-28;if(0==b)return 0;2147483647<=b&&(b=Infinity);var c=Atomics.load(t(),sb>>2),d=0;if(c==a&&Atomics.compareExchange(t(),sb>>2,c,0)==c&&(--b,d=1,0>=b))return 1;a=Atomics.notify(t(),a>>2,b);if(0<=a)return a+d;throw"Atomics.notify returned an unexpected value "+a;}x._emscripten_futex_wake=rb;
function tb(a){if(C)throw"Internal Error! cancelThread() can only ever be called from main application thread!";if(!a)throw"Internal Error! Null pthread_ptr in cancelThread!";S.jc[a].worker.postMessage({cmd:"cancel"})}function ub(a){if(C)throw"Internal Error! cleanupThread() can only ever be called from main application thread!";if(!a)throw"Internal Error! Null pthread_ptr in cleanupThread!";var b=S.jc[a];b&&(t()[a+12>>2]=0,S.dd(b.worker))}
var S={pc:[],oc:[],Jd:[],Rf:function(){},Qe:function(){for(var a=K(228),b=0;57>b;++b)u()[a/4+b]=0;t()[a+12>>2]=a;b=a+152;t()[b>>2]=b;var c=K(512);for(b=0;128>b;++b)u()[c/4+b]=0;Atomics.store(u(),a+100>>2,c);Atomics.store(u(),a+40>>2,a);wb(a,!A,1);xb(a)},Re:function(){S.receiveObjectTransfer=S.hf;S.threadInit=S.uf;S.threadCancel=S.sf;S.threadExit=S.tf;S.setExitStatus=S.nf},jc:{},hd:[],kf:function(){for(;0<S.hd.length;)S.hd.pop()();C&&zb()&&Ab()},me:function(a,b){Atomics.store(u(),a+56>>2,1);Atomics.store(u(),
a+60>>2,0);S.kf();Atomics.store(u(),a+4>>2,b);Atomics.store(u(),a+0>>2,1);rb(a+0,2147483647);wb(0,0,0)},nf:function(){},tf:function(a){var b=zb();b&&(S.me(b,a),C&&postMessage({cmd:"exit"}))},sf:function(){S.me(zb(),-1);postMessage({cmd:"cancelDone"})},rf:function(){for(var a in S.jc){var b=S.jc[a];b&&b.worker&&S.dd(b.worker)}S.jc={};for(a=0;a<S.pc.length;++a){var c=S.pc[a];c.terminate()}S.pc=[];for(a=0;a<S.oc.length;++a)c=S.oc[a],b=c.cc,S.ud(b),c.terminate();S.oc=[]},ud:function(a){if(a){if(a.kc){var b=
t()[a.kc+100>>2];t()[a.kc+100>>2]=0;Bb(b);Bb(a.kc)}a.kc=0;a.qd&&a.wc&&Bb(a.wc);a.wc=0;a.worker&&(a.worker.cc=null)}},dd:function(a){S.lf(function(){delete S.jc[a.cc.kc];S.pc.push(a);S.oc.splice(S.oc.indexOf(a),1);S.ud(a.cc);a.cc=void 0})},lf:function(a){t()[Cb>>2]=0;try{a()}finally{t()[Cb>>2]=1}},hf:function(){},uf:function(){for(var a in S.Jd)S.Jd[a]()},Ve:function(a,b){a.onmessage=function(c){var d=c.data,f=d.cmd;a.cc&&(S.He=a.cc.kc);if(d.targetThread&&d.targetThread!=zb()){var g=S.jc[d.ag];g?g.worker.postMessage(c.data,
d.transferList):console.error('Internal error! Worker sent a message "'+f+'" to target pthread '+d.targetThread+", but that thread no longer exists!")}else if("processQueuedMainThreadWork"===f)Db();else if("spawnThread"===f)Eb(c.data);else if("cleanupThread"===f)ub(d.thread);else if("killThread"===f){c=d.thread;if(C)throw"Internal Error! killThread() can only ever be called from main application thread!";if(!c)throw"Internal Error! Null pthread_ptr in killThread!";t()[c+12>>2]=0;c=S.jc[c];c.worker.terminate();
S.ud(c);S.oc.splice(S.oc.indexOf(c.worker),1);c.worker.cc=void 0}else if("cancelThread"===f)tb(d.thread);else if("loaded"===f)a.loaded=!0,b&&b(a),a.Rc&&(a.Rc(),delete a.Rc);else if("print"===f)pa("Thread "+d.threadId+": "+d.text);else if("printErr"===f)z("Thread "+d.threadId+": "+d.text);else if("alert"===f)alert("Thread "+d.threadId+": "+d.text);else if("exit"===f)a.cc&&Atomics.load(u(),a.cc.kc+64>>2)&&S.dd(a);else if("exitProcess"===f)try{oa(d.returnCode)}catch(k){if(k instanceof na)return;throw k;
}else"cancelDone"===f?S.dd(a):"objectTransfer"!==f&&("setimmediate"===c.data.target?a.postMessage(c.data):z("worker sent an unknown command "+f));S.He=void 0};a.onerror=function(c){z("pthread sent an error! "+c.filename+":"+c.lineno+": "+c.message)};B&&(a.on("message",function(c){a.onmessage({data:c})}),a.on("error",function(c){a.onerror(c)}),a.on("exit",function(){}));a.postMessage({cmd:"load",urlOrBlob:x.mainScriptUrlOrBlob||_scriptDir,wasmMemory:h,wasmModule:Ha})},xe:function(){var a=xa("ffmpeg-core.worker.js");
S.pc.push(new Worker(a))},Me:function(){0==S.pc.length&&(S.xe(),S.Ve(S.pc[0]));return S.pc.pop()},Ef:function(a){for(a=performance.now()+a;performance.now()<a;);}};x.establishStackSpace=function(a,b){Fb(a,b);J(a)};x.invokeEntryPoint=function(a,b){return L.get(a)(b)};var Gb=0;function Hb(){return noExitRuntime||0<Gb}x.keepRuntimeAlive=Hb;var Ib;
B?Ib=function(){var a=process.hrtime();return 1E3*a[0]+a[1]/1E6}:C?Ib=function(){return performance.now()-x.__performance_now_clock_drift}:"undefined"!==typeof dateNow?Ib=dateNow:Ib=function(){return performance.now()};function Jb(a,b){if(0===a)a=Date.now();else if(1===a||4===a)a=Ib();else return t()[Kb()>>2]=28,-1;t()[b>>2]=a/1E3|0;t()[b+4>>2]=a%1E3*1E6|0;return 0}function Lb(a,b){S.hd.push(function(){L.get(a)(b)})}
function Mb(a,b){a=new Date(1E3*t()[a>>2]);t()[b>>2]=a.getUTCSeconds();t()[b+4>>2]=a.getUTCMinutes();t()[b+8>>2]=a.getUTCHours();t()[b+12>>2]=a.getUTCDate();t()[b+16>>2]=a.getUTCMonth();t()[b+20>>2]=a.getUTCFullYear()-1900;t()[b+24>>2]=a.getUTCDay();t()[b+36>>2]=0;t()[b+32>>2]=0;a=(a.getTime()-Date.UTC(a.getUTCFullYear(),0,1,0,0,0,0))/864E5|0;t()[b+28>>2]=a;Mb.Md||(Mb.Md=Ta("GMT"));t()[b+40>>2]=Mb.Md;return b}
function Nb(){function a(k){return(k=k.toTimeString().match(/\(([A-Za-z ]+)\)$/))?k[1]:"GMT"}if(C)return V(2,1);if(!Nb.ye){Nb.ye=!0;var b=(new Date).getFullYear(),c=new Date(b,0,1),d=new Date(b,6,1);b=c.getTimezoneOffset();var f=d.getTimezoneOffset(),g=Math.max(b,f);t()[Ob()>>2]=60*g;t()[Pb()>>2]=Number(b!=f);c=a(c);d=a(d);c=Ta(c);d=Ta(d);f<b?(t()[Qb()>>2]=c,t()[Qb()+4>>2]=d):(t()[Qb()>>2]=d,t()[Qb()+4>>2]=c)}}
function Rb(a,b){Nb();a=new Date(1E3*t()[a>>2]);t()[b>>2]=a.getSeconds();t()[b+4>>2]=a.getMinutes();t()[b+8>>2]=a.getHours();t()[b+12>>2]=a.getDate();t()[b+16>>2]=a.getMonth();t()[b+20>>2]=a.getFullYear()-1900;t()[b+24>>2]=a.getDay();var c=new Date(a.getFullYear(),0,1),d=(a.getTime()-c.getTime())/864E5|0;t()[b+28>>2]=d;t()[b+36>>2]=-(60*a.getTimezoneOffset());d=(new Date(a.getFullYear(),6,1)).getTimezoneOffset();c=c.getTimezoneOffset();a=(d!=c&&a.getTimezoneOffset()==Math.min(c,d))|0;t()[b+32>>2]=
a;a=t()[Qb()+(a?4:0)>>2];t()[b+40>>2]=a;return b}function Sb(a,b){for(var c=0,d=a.length-1;0<=d;d--){var f=a[d];"."===f?a.splice(d,1):".."===f?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a}function Tb(a){var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=Sb(a.split("/").filter(function(d){return!!d}),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a}
function Ub(a){var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&(b=b.substr(0,b.length-1));return a+b}function Vb(a){if("/"===a)return"/";a=Tb(a);a=a.replace(/\/$/,"");var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)}function Wb(a,b){return Tb(a+"/"+b)}
function Xb(){if("object"===typeof crypto&&"function"===typeof crypto.getRandomValues){var a=new Uint8Array(1);return function(){crypto.getRandomValues(a);return a[0]}}if(B)try{var b=require("crypto");return function(){return b.randomBytes(1)[0]}}catch(c){}return function(){E("randomDevice")}}
function Yb(){for(var a="",b=!1,c=arguments.length-1;-1<=c&&!b;c--){b=0<=c?arguments[c]:M.cwd();if("string"!==typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b="/"===b.charAt(0)}a=Sb(a.split("/").filter(function(d){return!!d}),!b).join("/");return(b?"/":"")+a||"."}
function Zb(a,b){function c(k){for(var m=0;m<k.length&&""===k[m];m++);for(var q=k.length-1;0<=q&&""===k[q];q--);return m>q?[]:k.slice(m,q-m+1)}a=Yb(a).substr(1);b=Yb(b).substr(1);a=c(a.split("/"));b=c(b.split("/"));for(var d=Math.min(a.length,b.length),f=d,g=0;g<d;g++)if(a[g]!==b[g]){f=g;break}d=[];for(g=f;g<a.length;g++)d.push("..");d=d.concat(b.slice(f));return d.join("/")}var $b=[];function ac(a,b){$b[a]={input:[],output:[],Bc:b};M.Id(a,bc)}
var bc={open:function(a){var b=$b[a.node.rdev];if(!b)throw new M.Ib(43);a.tty=b;a.seekable=!1},close:function(a){a.tty.Bc.flush(a.tty)},flush:function(a){a.tty.Bc.flush(a.tty)},read:function(a,b,c,d){if(!a.tty||!a.tty.Bc.ce)throw new M.Ib(60);for(var f=0,g=0;g<d;g++){try{var k=a.tty.Bc.ce(a.tty)}catch(m){throw new M.Ib(29);}if(void 0===k&&0===f)throw new M.Ib(6);if(null===k||void 0===k)break;f++;b[c+g]=k}f&&(a.node.timestamp=Date.now());return f},write:function(a,b,c,d){if(!a.tty||!a.tty.Bc.Ed)throw new M.Ib(60);
try{for(var f=0;f<d;f++)a.tty.Bc.Ed(a.tty,b[c+f])}catch(g){throw new M.Ib(29);}d&&(a.node.timestamp=Date.now());return f}},dc={ce:function(a){if(!a.input.length){var b=null;if(B){var c=Buffer.xc?Buffer.xc(256):new Buffer(256),d=0;try{d=Ba.readSync(process.stdin.fd,c,0,256,null)}catch(f){if(f.toString().includes("EOF"))d=0;else throw f;}0<d?b=c.slice(0,d).toString("utf-8"):b=null}else"undefined"!=typeof window&&"function"==typeof window.prompt?(b=window.prompt("Input: "),null!==b&&(b+="\n")):"function"==
typeof readline&&(b=readline(),null!==b&&(b+="\n"));if(!b)return null;a.input=cc(b,!0)}return a.input.shift()},Ed:function(a,b){null===b||10===b?(pa(Qa(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(pa(Qa(a.output,0)),a.output=[])}},ec={Ed:function(a,b){null===b||10===b?(z(Qa(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(z(Qa(a.output,0)),a.output=[])}},W={ic:null,Ob:function(){return W.createNode(null,
"/",16895,0)},createNode:function(a,b,c,d){if(M.Se(c)||M.isFIFO(c))throw new M.Ib(63);W.ic||(W.ic={dir:{node:{bc:W.Jb.bc,Tb:W.Jb.Tb,lookup:W.Jb.lookup,fc:W.Jb.fc,rename:W.Jb.rename,unlink:W.Jb.unlink,rmdir:W.Jb.rmdir,readdir:W.Jb.readdir,symlink:W.Jb.symlink},stream:{Wb:W.Kb.Wb}},file:{node:{bc:W.Jb.bc,Tb:W.Jb.Tb},stream:{Wb:W.Kb.Wb,read:W.Kb.read,write:W.Kb.write,Jc:W.Kb.Jc,zc:W.Kb.zc,Ac:W.Kb.Ac}},link:{node:{bc:W.Jb.bc,Tb:W.Jb.Tb,readlink:W.Jb.readlink},stream:{}},Qd:{node:{bc:W.Jb.bc,Tb:W.Jb.Tb},
stream:M.Ae}});c=M.createNode(a,b,c,d);M.Rb(c.mode)?(c.Jb=W.ic.dir.node,c.Kb=W.ic.dir.stream,c.Lb={}):M.isFile(c.mode)?(c.Jb=W.ic.file.node,c.Kb=W.ic.file.stream,c.Pb=0,c.Lb=null):M.rc(c.mode)?(c.Jb=W.ic.link.node,c.Kb=W.ic.link.stream):M.Mc(c.mode)&&(c.Jb=W.ic.Qd.node,c.Kb=W.ic.Qd.stream);c.timestamp=Date.now();a&&(a.Lb[b]=c,a.timestamp=c.timestamp);return c},Of:function(a){return a.Lb?a.Lb.subarray?a.Lb.subarray(0,a.Pb):new Uint8Array(a.Lb):new Uint8Array(0)},Xd:function(a,b){var c=a.Lb?a.Lb.length:
0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)>>>0),0!=c&&(b=Math.max(b,256)),c=a.Lb,a.Lb=new Uint8Array(b),0<a.Pb&&a.Lb.set(c.subarray(0,a.Pb),0))},jf:function(a,b){if(a.Pb!=b)if(0==b)a.Lb=null,a.Pb=0;else{var c=a.Lb;a.Lb=new Uint8Array(b);c&&a.Lb.set(c.subarray(0,Math.min(b,a.Pb)));a.Pb=b}},Jb:{bc:function(a){var b={};b.dev=M.Mc(a.mode)?a.id:1;b.ino=a.id;b.mode=a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=a.rdev;M.Rb(a.mode)?b.size=4096:M.isFile(a.mode)?b.size=a.Pb:M.rc(a.mode)?b.size=a.link.length:b.size=
0;b.atime=new Date(a.timestamp);b.mtime=new Date(a.timestamp);b.ctime=new Date(a.timestamp);b.Od=4096;b.blocks=Math.ceil(b.size/b.Od);return b},Tb:function(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);void 0!==b.size&&W.jf(a,b.size)},lookup:function(){throw M.vd[44];},fc:function(a,b,c,d){return W.createNode(a,b,c,d)},rename:function(a,b,c){if(M.Rb(a.mode)){try{var d=M.ec(b,c)}catch(g){}if(d)for(var f in d.Lb)throw new M.Ib(55);}delete a.parent.Lb[a.name];
a.parent.timestamp=Date.now();a.name=c;b.Lb[c]=a;b.timestamp=a.parent.timestamp;a.parent=b},unlink:function(a,b){delete a.Lb[b];a.timestamp=Date.now()},rmdir:function(a,b){var c=M.ec(a,b),d;for(d in c.Lb)throw new M.Ib(55);delete a.Lb[b];a.timestamp=Date.now()},readdir:function(a){var b=[".",".."],c;for(c in a.Lb)a.Lb.hasOwnProperty(c)&&b.push(c);return b},symlink:function(a,b,c){a=W.createNode(a,b,41471,0);a.link=c;return a},readlink:function(a){if(!M.rc(a.mode))throw new M.Ib(28);return a.link}},
Kb:{read:function(a,b,c,d,f){var g=a.node.Lb;if(f>=a.node.Pb)return 0;a=Math.min(a.node.Pb-f,d);if(8<a&&g.subarray)b.set(g.subarray(f,f+a),c);else for(d=0;d<a;d++)b[c+d]=g[f+d];return a},write:function(a,b,c,d,f,g){b.buffer===e().buffer&&(g=!1);if(!d)return 0;a=a.node;a.timestamp=Date.now();if(b.subarray&&(!a.Lb||a.Lb.subarray)){if(g)return a.Lb=b.subarray(c,c+d),a.Pb=d;if(0===a.Pb&&0===f)return a.Lb=b.slice(c,c+d),a.Pb=d;if(f+d<=a.Pb)return a.Lb.set(b.subarray(c,c+d),f),d}W.Xd(a,f+d);if(a.Lb.subarray&&
b.subarray)a.Lb.set(b.subarray(c,c+d),f);else for(g=0;g<d;g++)a.Lb[f+g]=b[c+g];a.Pb=Math.max(a.Pb,f+d);return d},Wb:function(a,b,c){1===c?b+=a.position:2===c&&M.isFile(a.node.mode)&&(b+=a.node.Pb);if(0>b)throw new M.Ib(28);return b},Jc:function(a,b,c){W.Xd(a.node,b+c);a.node.Pb=Math.max(a.node.Pb,b+c)},zc:function(a,b,c,d,f,g){if(0!==b)throw new M.Ib(28);if(!M.isFile(a.node.mode))throw new M.Ib(43);a=a.node.Lb;if(g&2||a.buffer!==l){if(0<d||d+c<a.length)a.subarray?a=a.subarray(d,d+c):a=Array.prototype.slice.call(a,
d,d+c);d=!0;g=65536*Math.ceil(c/65536);for(b=K(g);c<g;)e()[b+c++]=0;c=b;if(!c)throw new M.Ib(48);e().set(a,c)}else d=!1,c=a.byteOffset;return{gf:c,pd:d}},Ac:function(a,b,c,d,f){if(!M.isFile(a.node.mode))throw new M.Ib(43);if(f&2)return 0;W.Kb.write(a,b,0,d,c,!1);return 0}}},X={md:16895,Ic:33279,Gd:null,Ob:function(a){function b(g){g=g.split("/");for(var k=d,m=0;m<g.length-1;m++){var q=g.slice(0,m+1).join("/");f[q]||(f[q]=X.createNode(k,g[m],X.md,0));k=f[q]}return k}function c(g){g=g.split("/");return g[g.length-
1]}assert(A);X.Gd||(X.Gd=new FileReaderSync);var d=X.createNode(null,"/",X.md,0),f={};Array.prototype.forEach.call(a.Dd.files||[],function(g){X.createNode(b(g.name),c(g.name),X.Ic,0,g,g.lastModifiedDate)});(a.Dd.blobs||[]).forEach(function(g){X.createNode(b(g.name),c(g.name),X.Ic,0,g.data)});(a.Dd.packages||[]).forEach(function(g){g.metadata.files.forEach(function(k){var m=k.filename.substr(1);X.createNode(b(m),c(m),X.Ic,0,g.blob.slice(k.start,k.end))})});return d},createNode:function(a,b,c,d,f,g){d=
M.createNode(a,b,c);d.mode=c;d.Jb=X.Jb;d.Kb=X.Kb;d.timestamp=(g||new Date).getTime();assert(X.Ic!==X.md);c===X.Ic?(d.size=f.size,d.Lb=f):(d.size=4096,d.Lb={});a&&(a.Lb[b]=d);return d},Jb:{bc:function(a){return{dev:1,ino:a.id,mode:a.mode,nlink:1,uid:0,gid:0,rdev:void 0,size:a.size,atime:new Date(a.timestamp),mtime:new Date(a.timestamp),ctime:new Date(a.timestamp),Od:4096,blocks:Math.ceil(a.size/4096)}},Tb:function(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp)},
lookup:function(){throw new M.Ib(44);},fc:function(){throw new M.Ib(63);},rename:function(){throw new M.Ib(63);},unlink:function(){throw new M.Ib(63);},rmdir:function(){throw new M.Ib(63);},readdir:function(a){var b=[".",".."],c;for(c in a.Lb)a.Lb.hasOwnProperty(c)&&b.push(c);return b},symlink:function(){throw new M.Ib(63);},readlink:function(){throw new M.Ib(63);}},Kb:{read:function(a,b,c,d,f){if(f>=a.node.size)return 0;a=a.node.Lb.slice(f,f+d);d=X.Gd.readAsArrayBuffer(a);b.set(new Uint8Array(d),
c);return a.size},write:function(){throw new M.Ib(29);},Wb:function(a,b,c){1===c?b+=a.position:2===c&&M.isFile(a.node.mode)&&(b+=a.node.size);if(0>b)throw new M.Ib(28);return b}}},M={root:null,Pc:[],Ud:{},streams:[],af:1,hc:null,Td:"/",yd:!1,ge:!0,Ub:{},pe:{je:{te:1,ue:2}},Ib:null,vd:{},Yd:null,gd:0,Nb:function(a,b){a=Yb(M.cwd(),a);b=b||{};if(!a)return{path:"",node:null};var c={td:!0,Hd:0},d;for(d in c)void 0===b[d]&&(b[d]=c[d]);if(8<b.Hd)throw new M.Ib(32);a=Sb(a.split("/").filter(function(k){return!!k}),
!1);var f=M.root;c="/";for(d=0;d<a.length;d++){var g=d===a.length-1;if(g&&b.parent)break;f=M.ec(f,a[d]);c=Wb(c,a[d]);M.sc(f)&&(!g||g&&b.td)&&(f=f.Oc.root);if(!g||b.ac)for(g=0;M.rc(f.mode);)if(f=M.readlink(c),c=Yb(Ub(c),f),f=M.Nb(c,{Hd:b.Hd}).node,40<g++)throw new M.Ib(32);}return{path:c,node:f}},mc:function(a){for(var b;;){if(M.Zc(a))return a=a.Ob.he,b?"/"!==a[a.length-1]?a+"/"+b:a+b:a;b=b?a.name+"/"+b:a.name;a=a.parent}},xd:function(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|
0;return(a+c>>>0)%M.hc.length},ee:function(a){var b=M.xd(a.parent.id,a.name);a.uc=M.hc[b];M.hc[b]=a},fe:function(a){var b=M.xd(a.parent.id,a.name);if(M.hc[b]===a)M.hc[b]=a.uc;else for(b=M.hc[b];b;){if(b.uc===a){b.uc=a.uc;break}b=b.uc}},ec:function(a,b){var c=M.Ye(a);if(c)throw new M.Ib(c,a);for(c=M.hc[M.xd(a.id,b)];c;c=c.uc){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return M.lookup(a,b)},createNode:function(a,b,c,d){a=new M.qe(a,b,c,d);M.ee(a);return a},sd:function(a){M.fe(a)},Zc:function(a){return a===
a.parent},sc:function(a){return!!a.Oc},isFile:function(a){return 32768===(a&61440)},Rb:function(a){return 16384===(a&61440)},rc:function(a){return 40960===(a&61440)},Mc:function(a){return 8192===(a&61440)},Se:function(a){return 24576===(a&61440)},isFIFO:function(a){return 4096===(a&61440)},isSocket:function(a){return 49152===(a&49152)},Ke:{r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090},$e:function(a){var b=M.Ke[a];if("undefined"===typeof b)throw Error("Unknown file open mode: "+a);return b},Zd:function(a){var b=
["r","w","rw"][a&3];a&512&&(b+="w");return b},nc:function(a,b){if(M.ge)return 0;if(!b.includes("r")||a.mode&292){if(b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73))return 2}else return 2;return 0},Ye:function(a){var b=M.nc(a,"x");return b?b:a.Jb.lookup?0:2},Cd:function(a,b){try{return M.ec(a,b),20}catch(c){}return M.nc(a,"wx")},$c:function(a,b,c){try{var d=M.ec(a,b)}catch(f){return f.Mb}if(a=M.nc(a,"wx"))return a;if(c){if(!M.Rb(d.mode))return 54;if(M.Zc(d)||M.mc(d)===M.cwd())return 10}else if(M.Rb(d.mode))return 31;
return 0},Ze:function(a,b){return a?M.rc(a.mode)?32:M.Rb(a.mode)&&("r"!==M.Zd(b)||b&512)?31:M.nc(a,M.Zd(b)):44},se:4096,bf:function(a,b){b=b||M.se;for(a=a||0;a<=b;a++)if(!M.streams[a])return a;throw new M.Ib(33);},dc:function(a){return M.streams[a]},Sd:function(a,b,c){M.nd||(M.nd=function(){},M.nd.prototype={object:{get:function(){return this.node},set:function(g){this.node=g}}});var d=new M.nd,f;for(f in a)d[f]=a[f];a=d;b=M.bf(b,c);a.fd=b;return M.streams[b]=a},Be:function(a){M.streams[a]=null},
Ae:{open:function(a){a.Kb=M.Le(a.node.rdev).Kb;a.Kb.open&&a.Kb.open(a)},Wb:function(){throw new M.Ib(70);}},Bd:function(a){return a>>8},Tf:function(a){return a&255},tc:function(a,b){return a<<8|b},Id:function(a,b){M.Ud[a]={Kb:b}},Le:function(a){return M.Ud[a]},be:function(a){var b=[];for(a=[a];a.length;){var c=a.pop();b.push(c);a.push.apply(a,c.Pc)}return b},oe:function(a,b){function c(k){M.gd--;return b(k)}function d(k){if(k){if(!d.Ie)return d.Ie=!0,c(k)}else++g>=f.length&&c(null)}"function"===typeof a&&
(b=a,a=!1);M.gd++;1<M.gd&&z("warning: "+M.gd+" FS.syncfs operations in flight at once, probably just doing extra work");var f=M.be(M.root.Ob),g=0;f.forEach(function(k){if(!k.type.oe)return d(null);k.type.oe(k,a,d)})},Ob:function(a,b,c){var d="/"===c,f=!c;if(d&&M.root)throw new M.Ib(10);if(!d&&!f){var g=M.Nb(c,{td:!1});c=g.path;g=g.node;if(M.sc(g))throw new M.Ib(10);if(!M.Rb(g.mode))throw new M.Ib(54);}b={type:a,Dd:b,he:c,Pc:[]};a=a.Ob(b);a.Ob=b;b.root=a;d?M.root=a:g&&(g.Oc=b,g.Ob&&g.Ob.Pc.push(b));
return a},Bf:function(a){a=M.Nb(a,{td:!1});if(!M.sc(a.node))throw new M.Ib(28);a=a.node;var b=a.Oc,c=M.be(b);Object.keys(M.hc).forEach(function(d){for(d=M.hc[d];d;){var f=d.uc;c.includes(d.Ob)&&M.sd(d);d=f}});a.Oc=null;a.Ob.Pc.splice(a.Ob.Pc.indexOf(b),1)},lookup:function(a,b){return a.Jb.lookup(a,b)},fc:function(a,b,c){var d=M.Nb(a,{parent:!0}).node;a=Vb(a);if(!a||"."===a||".."===a)throw new M.Ib(28);var f=M.Cd(d,a);if(f)throw new M.Ib(f);if(!d.Jb.fc)throw new M.Ib(63);return d.Jb.fc(d,a,b,c)},create:function(a,
b){return M.fc(a,(void 0!==b?b:438)&4095|32768,0)},mkdir:function(a,b){return M.fc(a,(void 0!==b?b:511)&1023|16384,0)},Vf:function(a,b){a=a.split("/");for(var c="",d=0;d<a.length;++d)if(a[d]){c+="/"+a[d];try{M.mkdir(c,b)}catch(f){if(20!=f.Mb)throw f;}}},ad:function(a,b,c){"undefined"===typeof c&&(c=b,b=438);return M.fc(a,b|8192,c)},symlink:function(a,b){if(!Yb(a))throw new M.Ib(44);var c=M.Nb(b,{parent:!0}).node;if(!c)throw new M.Ib(44);b=Vb(b);var d=M.Cd(c,b);if(d)throw new M.Ib(d);if(!c.Jb.symlink)throw new M.Ib(63);
return c.Jb.symlink(c,b,a)},rename:function(a,b){var c=Ub(a),d=Ub(b),f=Vb(a),g=Vb(b);var k=M.Nb(a,{parent:!0});var m=k.node;k=M.Nb(b,{parent:!0});k=k.node;if(!m||!k)throw new M.Ib(44);if(m.Ob!==k.Ob)throw new M.Ib(75);var q=M.ec(m,f);d=Zb(a,d);if("."!==d.charAt(0))throw new M.Ib(28);d=Zb(b,c);if("."!==d.charAt(0))throw new M.Ib(55);try{var p=M.ec(k,g)}catch(r){}if(q!==p){c=M.Rb(q.mode);if(f=M.$c(m,f,c))throw new M.Ib(f);if(f=p?M.$c(k,g,c):M.Cd(k,g))throw new M.Ib(f);if(!m.Jb.rename)throw new M.Ib(63);
if(M.sc(q)||p&&M.sc(p))throw new M.Ib(10);if(k!==m&&(f=M.nc(m,"w")))throw new M.Ib(f);try{M.Ub.willMovePath&&M.Ub.willMovePath(a,b)}catch(r){z("FS.trackingDelegate['willMovePath']('"+a+"', '"+b+"') threw an exception: "+r.message)}M.fe(q);try{m.Jb.rename(q,k,g)}catch(r){throw r;}finally{M.ee(q)}try{if(M.Ub.onMovePath)M.Ub.onMovePath(a,b)}catch(r){z("FS.trackingDelegate['onMovePath']('"+a+"', '"+b+"') threw an exception: "+r.message)}}},rmdir:function(a){var b=M.Nb(a,{parent:!0}).node,c=Vb(a),d=M.ec(b,
c),f=M.$c(b,c,!0);if(f)throw new M.Ib(f);if(!b.Jb.rmdir)throw new M.Ib(63);if(M.sc(d))throw new M.Ib(10);try{M.Ub.willDeletePath&&M.Ub.willDeletePath(a)}catch(g){z("FS.trackingDelegate['willDeletePath']('"+a+"') threw an exception: "+g.message)}b.Jb.rmdir(b,c);M.sd(d);try{if(M.Ub.onDeletePath)M.Ub.onDeletePath(a)}catch(g){z("FS.trackingDelegate['onDeletePath']('"+a+"') threw an exception: "+g.message)}},readdir:function(a){a=M.Nb(a,{ac:!0}).node;if(!a.Jb.readdir)throw new M.Ib(54);return a.Jb.readdir(a)},
unlink:function(a){var b=M.Nb(a,{parent:!0}).node,c=Vb(a),d=M.ec(b,c),f=M.$c(b,c,!1);if(f)throw new M.Ib(f);if(!b.Jb.unlink)throw new M.Ib(63);if(M.sc(d))throw new M.Ib(10);try{M.Ub.willDeletePath&&M.Ub.willDeletePath(a)}catch(g){z("FS.trackingDelegate['willDeletePath']('"+a+"') threw an exception: "+g.message)}b.Jb.unlink(b,c);M.sd(d);try{if(M.Ub.onDeletePath)M.Ub.onDeletePath(a)}catch(g){z("FS.trackingDelegate['onDeletePath']('"+a+"') threw an exception: "+g.message)}},readlink:function(a){a=M.Nb(a).node;
if(!a)throw new M.Ib(44);if(!a.Jb.readlink)throw new M.Ib(28);return Yb(M.mc(a.parent),a.Jb.readlink(a))},stat:function(a,b){a=M.Nb(a,{ac:!b}).node;if(!a)throw new M.Ib(44);if(!a.Jb.bc)throw new M.Ib(63);return a.Jb.bc(a)},lstat:function(a){return M.stat(a,!0)},chmod:function(a,b,c){a="string"===typeof a?M.Nb(a,{ac:!c}).node:a;if(!a.Jb.Tb)throw new M.Ib(63);a.Jb.Tb(a,{mode:b&4095|a.mode&-4096,timestamp:Date.now()})},lchmod:function(a,b){M.chmod(a,b,!0)},fchmod:function(a,b){a=M.dc(a);if(!a)throw new M.Ib(8);
M.chmod(a.node,b)},chown:function(a,b,c,d){a="string"===typeof a?M.Nb(a,{ac:!d}).node:a;if(!a.Jb.Tb)throw new M.Ib(63);a.Jb.Tb(a,{timestamp:Date.now()})},lchown:function(a,b,c){M.chown(a,b,c,!0)},fchown:function(a,b,c){a=M.dc(a);if(!a)throw new M.Ib(8);M.chown(a.node,b,c)},truncate:function(a,b){if(0>b)throw new M.Ib(28);a="string"===typeof a?M.Nb(a,{ac:!0}).node:a;if(!a.Jb.Tb)throw new M.Ib(63);if(M.Rb(a.mode))throw new M.Ib(31);if(!M.isFile(a.mode))throw new M.Ib(28);var c=M.nc(a,"w");if(c)throw new M.Ib(c);
a.Jb.Tb(a,{size:b,timestamp:Date.now()})},Mf:function(a,b){a=M.dc(a);if(!a)throw new M.Ib(8);if(0===(a.flags&2097155))throw new M.Ib(28);M.truncate(a.node,b)},cg:function(a,b,c){a=M.Nb(a,{ac:!0}).node;a.Jb.Tb(a,{timestamp:Math.max(b,c)})},open:function(a,b,c,d,f){if(""===a)throw new M.Ib(44);b="string"===typeof b?M.$e(b):b;c=b&64?("undefined"===typeof c?438:c)&4095|32768:0;if("object"===typeof a)var g=a;else{a=Tb(a);try{g=M.Nb(a,{ac:!(b&131072)}).node}catch(m){}}var k=!1;if(b&64)if(g){if(b&128)throw new M.Ib(20);
}else g=M.fc(a,c,0),k=!0;if(!g)throw new M.Ib(44);M.Mc(g.mode)&&(b&=-513);if(b&65536&&!M.Rb(g.mode))throw new M.Ib(54);if(!k&&(c=M.Ze(g,b)))throw new M.Ib(c);b&512&&M.truncate(g,0);b&=-131713;d=M.Sd({node:g,path:M.mc(g),flags:b,seekable:!0,position:0,Kb:g.Kb,Af:[],error:!1},d,f);d.Kb.open&&d.Kb.open(d);!x.logReadFiles||b&1||(M.Fd||(M.Fd={}),a in M.Fd||(M.Fd[a]=1,z("FS.trackingDelegate error on read file: "+a)));try{M.Ub.onOpenFile&&(f=0,1!==(b&2097155)&&(f|=M.pe.je.te),0!==(b&2097155)&&(f|=M.pe.je.ue),
M.Ub.onOpenFile(a,f))}catch(m){z("FS.trackingDelegate['onOpenFile']('"+a+"', flags) threw an exception: "+m.message)}return d},close:function(a){if(M.Nc(a))throw new M.Ib(8);a.qc&&(a.qc=null);try{a.Kb.close&&a.Kb.close(a)}catch(b){throw b;}finally{M.Be(a.fd)}a.fd=null},Nc:function(a){return null===a.fd},Wb:function(a,b,c){if(M.Nc(a))throw new M.Ib(8);if(!a.seekable||!a.Kb.Wb)throw new M.Ib(70);if(0!=c&&1!=c&&2!=c)throw new M.Ib(28);a.position=a.Kb.Wb(a,b,c);a.Af=[];return a.position},read:function(a,
b,c,d,f){if(0>d||0>f)throw new M.Ib(28);if(M.Nc(a))throw new M.Ib(8);if(1===(a.flags&2097155))throw new M.Ib(8);if(M.Rb(a.node.mode))throw new M.Ib(31);if(!a.Kb.read)throw new M.Ib(28);var g="undefined"!==typeof f;if(!g)f=a.position;else if(!a.seekable)throw new M.Ib(70);b=a.Kb.read(a,b,c,d,f);g||(a.position+=b);return b},write:function(a,b,c,d,f,g){if(0>d||0>f)throw new M.Ib(28);if(M.Nc(a))throw new M.Ib(8);if(0===(a.flags&2097155))throw new M.Ib(8);if(M.Rb(a.node.mode))throw new M.Ib(31);if(!a.Kb.write)throw new M.Ib(28);
a.seekable&&a.flags&1024&&M.Wb(a,0,2);var k="undefined"!==typeof f;if(!k)f=a.position;else if(!a.seekable)throw new M.Ib(70);b=a.Kb.write(a,b,c,d,f,g);k||(a.position+=b);try{if(a.path&&M.Ub.onWriteToFile)M.Ub.onWriteToFile(a.path)}catch(m){z("FS.trackingDelegate['onWriteToFile']('"+a.path+"') threw an exception: "+m.message)}return b},Jc:function(a,b,c){if(M.Nc(a))throw new M.Ib(8);if(0>b||0>=c)throw new M.Ib(28);if(0===(a.flags&2097155))throw new M.Ib(8);if(!M.isFile(a.node.mode)&&!M.Rb(a.node.mode))throw new M.Ib(43);
if(!a.Kb.Jc)throw new M.Ib(138);a.Kb.Jc(a,b,c)},zc:function(a,b,c,d,f,g){if(0!==(f&2)&&0===(g&2)&&2!==(a.flags&2097155))throw new M.Ib(2);if(1===(a.flags&2097155))throw new M.Ib(2);if(!a.Kb.zc)throw new M.Ib(43);return a.Kb.zc(a,b,c,d,f,g)},Ac:function(a,b,c,d,f){return a&&a.Kb.Ac?a.Kb.Ac(a,b,c,d,f):0},Xf:function(){return 0},yc:function(a,b,c){if(!a.Kb.yc)throw new M.Ib(59);return a.Kb.yc(a,b,c)},readFile:function(a,b){b=b||{};b.flags=b.flags||0;b.encoding=b.encoding||"binary";if("utf8"!==b.encoding&&
"binary"!==b.encoding)throw Error('Invalid encoding type "'+b.encoding+'"');var c,d=M.open(a,b.flags);a=M.stat(a).size;var f=new Uint8Array(a);M.read(d,f,0,a,0);"utf8"===b.encoding?c=Qa(f,0):"binary"===b.encoding&&(c=f);M.close(d);return c},writeFile:function(a,b,c){c=c||{};c.flags=c.flags||577;a=M.open(a,c.flags,c.mode);if("string"===typeof b){var d=new Uint8Array(Sa(b)+1);b=Ra(b,d,0,d.length);M.write(a,d,0,b,void 0,c.ze)}else if(ArrayBuffer.isView(b))M.write(a,b,0,b.byteLength,void 0,c.ze);else throw Error("Unsupported data type");
M.close(a)},cwd:function(){return M.Td},chdir:function(a){a=M.Nb(a,{ac:!0});if(null===a.node)throw new M.Ib(44);if(!M.Rb(a.node.mode))throw new M.Ib(54);var b=M.nc(a.node,"x");if(b)throw new M.Ib(b);M.Td=a.path},De:function(){M.mkdir("/tmp");M.mkdir("/home");M.mkdir("/home/web_user")},Ce:function(){M.mkdir("/dev");M.Id(M.tc(1,3),{read:function(){return 0},write:function(b,c,d,f){return f}});M.ad("/dev/null",M.tc(1,3));ac(M.tc(5,0),dc);ac(M.tc(6,0),ec);M.ad("/dev/tty",M.tc(5,0));M.ad("/dev/tty1",M.tc(6,
0));var a=Xb();M.lc("/dev","random",a);M.lc("/dev","urandom",a);M.mkdir("/dev/shm");M.mkdir("/dev/shm/tmp")},Fe:function(){M.mkdir("/proc");var a=M.mkdir("/proc/self");M.mkdir("/proc/self/fd");M.Ob({Ob:function(){var b=M.createNode(a,"fd",16895,73);b.Jb={lookup:function(c,d){var f=M.dc(+d);if(!f)throw new M.Ib(8);c={parent:null,Ob:{he:"fake"},Jb:{readlink:function(){return f.path}}};return c.parent=c}};return b}},{},"/proc/self/fd")},Ge:function(){x.stdin?M.lc("/dev","stdin",x.stdin):M.symlink("/dev/tty",
"/dev/stdin");x.stdout?M.lc("/dev","stdout",null,x.stdout):M.symlink("/dev/tty","/dev/stdout");x.stderr?M.lc("/dev","stderr",null,x.stderr):M.symlink("/dev/tty1","/dev/stderr");M.open("/dev/stdin",0);M.open("/dev/stdout",1);M.open("/dev/stderr",1)},Wd:function(){M.Ib||(M.Ib=function(a,b){this.node=b;this.mf=function(c){this.Mb=c};this.mf(a);this.message="FS error"},M.Ib.prototype=Error(),M.Ib.prototype.constructor=M.Ib,[44].forEach(function(a){M.vd[a]=new M.Ib(a);M.vd[a].stack="<generic error, no stack>"}))},
qf:function(){M.Wd();M.hc=Array(4096);M.Ob(W,{},"/");M.De();M.Ce();M.Fe();M.Yd={MEMFS:W,WORKERFS:X}},Lc:function(a,b,c){M.Lc.yd=!0;M.Wd();x.stdin=a||x.stdin;x.stdout=b||x.stdout;x.stderr=c||x.stderr;M.Ge()},quit:function(){M.Lc.yd=!1;var a=x._fflush;a&&a(0);for(a=0;a<M.streams.length;a++){var b=M.streams[a];b&&M.close(b)}},wd:function(a,b){var c=0;a&&(c|=365);b&&(c|=146);return c},Lf:function(a,b){a=M.rd(a,b);return a.exists?a.object:null},rd:function(a,b){try{var c=M.Nb(a,{ac:!b});a=c.path}catch(f){}var d=
{Zc:!1,exists:!1,error:0,name:null,path:null,object:null,cf:!1,ef:null,df:null};try{c=M.Nb(a,{parent:!0}),d.cf=!0,d.ef=c.path,d.df=c.node,d.name=Vb(a),c=M.Nb(a,{ac:!b}),d.exists=!0,d.path=c.path,d.object=c.node,d.name=c.node.name,d.Zc="/"===c.path}catch(f){d.error=f.Mb}return d},If:function(a,b){a="string"===typeof a?a:M.mc(a);for(b=b.split("/").reverse();b.length;){var c=b.pop();if(c){var d=Wb(a,c);try{M.mkdir(d)}catch(f){}a=d}}return d},Ee:function(a,b,c,d,f){a=Wb("string"===typeof a?a:M.mc(a),
b);return M.create(a,M.wd(d,f))},Rd:function(a,b,c,d,f,g){a=b?Wb("string"===typeof a?a:M.mc(a),b):a;d=M.wd(d,f);f=M.create(a,d);if(c){if("string"===typeof c){a=Array(c.length);b=0;for(var k=c.length;b<k;++b)a[b]=c.charCodeAt(b);c=a}M.chmod(f,d|146);a=M.open(f,577);M.write(a,c,0,c.length,0,g);M.close(a);M.chmod(f,d)}return f},lc:function(a,b,c,d){a=Wb("string"===typeof a?a:M.mc(a),b);b=M.wd(!!c,!!d);M.lc.Bd||(M.lc.Bd=64);var f=M.tc(M.lc.Bd++,0);M.Id(f,{open:function(g){g.seekable=!1},close:function(){d&&
d.buffer&&d.buffer.length&&d(10)},read:function(g,k,m,q){for(var p=0,r=0;r<q;r++){try{var y=c()}catch(G){throw new M.Ib(29);}if(void 0===y&&0===p)throw new M.Ib(6);if(null===y||void 0===y)break;p++;k[m+r]=y}p&&(g.node.timestamp=Date.now());return p},write:function(g,k,m,q){for(var p=0;p<q;p++)try{d(k[m+p])}catch(r){throw new M.Ib(29);}q&&(g.node.timestamp=Date.now());return p}});return M.ad(a,b,f)},$d:function(a){if(a.zd||a.Te||a.link||a.Lb)return!0;if("undefined"!==typeof XMLHttpRequest)throw Error("Lazy loading should have been performed (contents set) in createLazyFile, but it was not. Lazy loading only works in web workers. Use --embed-file or --preload-file in emcc on the main thread.");
if(ya)try{a.Lb=cc(ya(a.url),!0),a.Pb=a.Lb.length}catch(b){throw new M.Ib(29);}else throw Error("Cannot load without read() or XMLHttpRequest.");},Hf:function(a,b,c,d,f){function g(){this.Ad=!1;this.xc=[]}g.prototype.get=function(p){if(!(p>this.length-1||0>p)){var r=p%this.chunkSize;return this.de(p/this.chunkSize|0)[r]}};g.prototype.re=function(p){this.de=p};g.prototype.Pd=function(){var p=new XMLHttpRequest;p.open("HEAD",c,!1);p.send(null);if(!(200<=p.status&&300>p.status||304===p.status))throw Error("Couldn't load "+
c+". Status: "+p.status);var r=Number(p.getResponseHeader("Content-length")),y,G=(y=p.getResponseHeader("Accept-Ranges"))&&"bytes"===y;p=(y=p.getResponseHeader("Content-Encoding"))&&"gzip"===y;var n=1048576;G||(n=r);var v=this;v.re(function(w){var P=w*n,T=(w+1)*n-1;T=Math.min(T,r-1);if("undefined"===typeof v.xc[w]){var vb=v.xc;if(P>T)throw Error("invalid range ("+P+", "+T+") or no bytes requested!");if(T>r-1)throw Error("only "+r+" bytes available! programmer error!");var H=new XMLHttpRequest;H.open("GET",
c,!1);r!==n&&H.setRequestHeader("Range","bytes="+P+"-"+T);"undefined"!=typeof Uint8Array&&(H.responseType="arraybuffer");H.overrideMimeType&&H.overrideMimeType("text/plain; charset=x-user-defined");H.send(null);if(!(200<=H.status&&300>H.status||304===H.status))throw Error("Couldn't load "+c+". Status: "+H.status);P=void 0!==H.response?new Uint8Array(H.response||[]):cc(H.responseText||"",!0);vb[w]=P}if("undefined"===typeof v.xc[w])throw Error("doXHR failed!");return v.xc[w]});if(p||!r)n=r=1,n=r=this.de(0).length,
pa("LazyFiles on gzip forces download of the whole file when length is accessed");this.we=r;this.ve=n;this.Ad=!0};if("undefined"!==typeof XMLHttpRequest){if(!A)throw"Cannot do synchronous binary XHRs outside webworkers in modern browsers. Use --embed-file or --preload-file in emcc";var k=new g;Object.defineProperties(k,{length:{get:function(){this.Ad||this.Pd();return this.we}},chunkSize:{get:function(){this.Ad||this.Pd();return this.ve}}});k={zd:!1,Lb:k}}else k={zd:!1,url:c};var m=M.Ee(a,b,k,d,f);
k.Lb?m.Lb=k.Lb:k.url&&(m.Lb=null,m.url=k.url);Object.defineProperties(m,{Pb:{get:function(){return this.Lb.length}}});var q={};Object.keys(m.Kb).forEach(function(p){var r=m.Kb[p];q[p]=function(){M.$d(m);return r.apply(null,arguments)}});q.read=function(p,r,y,G,n){M.$d(m);p=p.node.Lb;if(n>=p.length)return 0;G=Math.min(p.length-n,G);if(p.slice)for(var v=0;v<G;v++)r[y+v]=p[n+v];else for(v=0;v<G;v++)r[y+v]=p.get(n+v);return G};m.Kb=q;return m},Jf:function(a,b,c,d,f,g,k,m,q,p){function r(G){function n(w){p&&
p();m||M.Rd(a,b,w,d,f,q);g&&g();lb()}var v=!1;x.preloadPlugins.forEach(function(w){!v&&w.canHandle(y)&&(w.handle(G,y,n,function(){k&&k();lb()}),v=!0)});v||n(G)}fc.Lc();var y=b?Yb(Wb(a,b)):a;kb();"string"==typeof c?fc.Cf(c,function(G){r(G)},k):r(c)},indexedDB:function(){return window.indexedDB||window.mozIndexedDB||window.webkitIndexedDB||window.msIndexedDB},Kd:function(){return"EM_FS_"+window.location.pathname},Ld:20,Hc:"FILE_DATA",$f:function(a,b,c){b=b||function(){};c=c||function(){};var d=M.indexedDB();
try{var f=d.open(M.Kd(),M.Ld)}catch(g){return c(g)}f.onupgradeneeded=function(){pa("creating db");f.result.createObjectStore(M.Hc)};f.onsuccess=function(){var g=f.result.transaction([M.Hc],"readwrite"),k=g.objectStore(M.Hc),m=0,q=0,p=a.length;a.forEach(function(r){r=k.put(M.rd(r).object.Lb,r);r.onsuccess=function(){m++;m+q==p&&(0==q?b():c())};r.onerror=function(){q++;m+q==p&&(0==q?b():c())}});g.onerror=c};f.onerror=c},Sf:function(a,b,c){b=b||function(){};c=c||function(){};var d=M.indexedDB();try{var f=
d.open(M.Kd(),M.Ld)}catch(g){return c(g)}f.onupgradeneeded=c;f.onsuccess=function(){var g=f.result;try{var k=g.transaction([M.Hc],"readonly")}catch(y){c(y);return}var m=k.objectStore(M.Hc),q=0,p=0,r=a.length;a.forEach(function(y){var G=m.get(y);G.onsuccess=function(){M.rd(y).exists&&M.unlink(y);M.Rd(Ub(y),Vb(y),G.result,!0,!0,!0);q++;q+p==r&&(0==p?b():c())};G.onerror=function(){p++;q+p==r&&(0==p?b():c())}});k.onerror=c};f.onerror=c}},hc={};
function ic(a,b,c){try{var d=a(b)}catch(f){if(f&&f.node&&Tb(b)!==Tb(M.mc(f.node)))return-54;throw f;}t()[c>>2]=d.dev;t()[c+4>>2]=0;t()[c+8>>2]=d.ino;t()[c+12>>2]=d.mode;t()[c+16>>2]=d.nlink;t()[c+20>>2]=d.uid;t()[c+24>>2]=d.gid;t()[c+28>>2]=d.rdev;t()[c+32>>2]=0;R=[d.size>>>0,(Q=d.size,1<=+Math.abs(Q)?0<Q?(Math.min(+Math.floor(Q/4294967296),4294967295)|0)>>>0:~~+Math.ceil((Q-+(~~Q>>>0))/4294967296)>>>0:0)];t()[c+40>>2]=R[0];t()[c+44>>2]=R[1];t()[c+48>>2]=4096;t()[c+52>>2]=d.blocks;t()[c+56>>2]=d.atime.getTime()/
1E3|0;t()[c+60>>2]=0;t()[c+64>>2]=d.mtime.getTime()/1E3|0;t()[c+68>>2]=0;t()[c+72>>2]=d.ctime.getTime()/1E3|0;t()[c+76>>2]=0;R=[d.ino>>>0,(Q=d.ino,1<=+Math.abs(Q)?0<Q?(Math.min(+Math.floor(Q/4294967296),4294967295)|0)>>>0:~~+Math.ceil((Q-+(~~Q>>>0))/4294967296)>>>0:0)];t()[c+80>>2]=R[0];t()[c+84>>2]=R[1];return 0}var jc=void 0;function kc(){jc+=4;return t()[jc-4>>2]}function lc(a){a=M.dc(a);if(!a)throw new M.Ib(8);return a}
function mc(a,b,c,d,f){if(C)return V(3,1,a,b,c,d,f);try{f=0;for(var g=b?t()[b>>2]:0,k=b?t()[b+4>>2]:0,m=c?t()[c>>2]:0,q=c?t()[c+4>>2]:0,p=d?t()[d>>2]:0,r=d?t()[d+4>>2]:0,y=0,G=0,n=0,v=0,w=0,P=0,T=(b?t()[b>>2]:0)|(c?t()[c>>2]:0)|(d?t()[d>>2]:0),vb=(b?t()[b+4>>2]:0)|(c?t()[c+4>>2]:0)|(d?t()[d+4>>2]:0),H=0;H<a;H++){var U=1<<H%32;if(32>H?T&U:vb&U){var Ya=M.dc(H);if(!Ya)throw new M.Ib(8);var Za=5;Ya.Kb.Cc&&(Za=Ya.Kb.Cc(Ya));Za&1&&(32>H?g&U:k&U)&&(32>H?y|=U:G|=U,f++);Za&4&&(32>H?m&U:q&U)&&(32>H?n|=U:v|=
U,f++);Za&2&&(32>H?p&U:r&U)&&(32>H?w|=U:P|=U,f++)}}b&&(t()[b>>2]=y,t()[b+4>>2]=G);c&&(t()[c>>2]=n,t()[c+4>>2]=v);d&&(t()[d>>2]=w,t()[d+4>>2]=P);return f}catch(yb){return"undefined"!==typeof M&&yb instanceof M.Ib||E(yb),-yb.Mb}}
var N={Ob:function(){x.websocket=x.websocket&&"object"===typeof x.websocket?x.websocket:{};x.websocket.od={};x.websocket.on=function(a,b){"function"===typeof b&&(this.od[a]=b);return this};x.websocket.emit=function(a,b){"function"===typeof this.od[a]&&this.od[a].call(this,b)};return M.createNode(null,"/",16895,0)},createSocket:function(a,b,c){b&=-526337;c&&assert(1==b==(6==c));a={family:a,type:b,protocol:c,Sb:null,error:null,Qc:{},pending:[],Dc:[],Zb:N.Vb};b=N.bd();c=M.createNode(N.root,b,49152,0);
c.Ec=a;b=M.Sd({path:b,node:c,flags:2,seekable:!1,Kb:N.Kb});a.stream=b;return a},Ne:function(a){return(a=M.dc(a))&&M.isSocket(a.node.mode)?a.node.Ec:null},Kb:{Cc:function(a){a=a.node.Ec;return a.Zb.Cc(a)},yc:function(a,b,c){a=a.node.Ec;return a.Zb.yc(a,b,c)},read:function(a,b,c,d){a=a.node.Ec;d=a.Zb.ke(a,d);if(!d)return 0;b.set(d.buffer,c);return d.buffer.length},write:function(a,b,c,d){a=a.node.Ec;return a.Zb.ne(a,b,c,d)},close:function(a){a=a.node.Ec;a.Zb.close(a)}},bd:function(){N.bd.current||(N.bd.current=
0);return"socket["+N.bd.current++ +"]"},Vb:{Wc:function(a,b,c){if("object"===typeof b){var d=b;c=b=null}if(d)if(d._socket)b=d._socket.remoteAddress,c=d._socket.remotePort;else{c=/ws[s]?:\/\/([^:]+):(\d+)/.exec(d.url);if(!c)throw Error("WebSocket URL must be in the format ws(s)://address:port");b=c[1];c=parseInt(c[2],10)}else try{var f=x.websocket&&"object"===typeof x.websocket,g="ws:#".replace("#","//");f&&"string"===typeof x.websocket.url&&(g=x.websocket.url);if("ws://"===g||"wss://"===g){var k=
b.split("/");g=g+k[0]+":"+c+"/"+k.slice(1).join("/")}k="binary";f&&"string"===typeof x.websocket.subprotocol&&(k=x.websocket.subprotocol);var m=void 0;"null"!==k&&(k=k.replace(/^ +| +$/g,"").split(/ *, */),m=B?{protocol:k.toString()}:k);f&&null===x.websocket.subprotocol&&(m=void 0);d=new (B?require("ws"):WebSocket)(g,m);d.binaryType="arraybuffer"}catch(q){throw new M.Ib(23);}b={Qb:b,port:c,socket:d,Xc:[]};N.Vb.Nd(a,b);N.Vb.Oe(a,b);2===a.type&&"undefined"!==typeof a.vc&&b.Xc.push(new Uint8Array([255,
255,255,255,112,111,114,116,(a.vc&65280)>>8,a.vc&255]));return b},Yc:function(a,b,c){return a.Qc[b+":"+c]},Nd:function(a,b){a.Qc[b.Qb+":"+b.port]=b},le:function(a,b){delete a.Qc[b.Qb+":"+b.port]},Oe:function(a,b){function c(){x.websocket.emit("open",a.stream.fd);try{for(var g=b.Xc.shift();g;)b.socket.send(g),g=b.Xc.shift()}catch(k){b.socket.close()}}function d(g){if("string"===typeof g)g=(new TextEncoder).encode(g);else{assert(void 0!==g.byteLength);if(0==g.byteLength)return;g=new Uint8Array(g)}var k=
f;f=!1;k&&10===g.length&&255===g[0]&&255===g[1]&&255===g[2]&&255===g[3]&&112===g[4]&&111===g[5]&&114===g[6]&&116===g[7]?(g=g[8]<<8|g[9],N.Vb.le(a,b),b.port=g,N.Vb.Nd(a,b)):(a.Dc.push({Qb:b.Qb,port:b.port,data:g}),x.websocket.emit("message",a.stream.fd))}var f=!0;B?(b.socket.on("open",c),b.socket.on("message",function(g,k){k.Df&&d((new Uint8Array(g)).buffer)}),b.socket.on("close",function(){x.websocket.emit("close",a.stream.fd)}),b.socket.on("error",function(){a.error=14;x.websocket.emit("error",[a.stream.fd,
a.error,"ECONNREFUSED: Connection refused"])})):(b.socket.onopen=c,b.socket.onclose=function(){x.websocket.emit("close",a.stream.fd)},b.socket.onmessage=function(g){d(g.data)},b.socket.onerror=function(){a.error=14;x.websocket.emit("error",[a.stream.fd,a.error,"ECONNREFUSED: Connection refused"])})},Cc:function(a){if(1===a.type&&a.Sb)return a.pending.length?65:0;var b=0,c=1===a.type?N.Vb.Yc(a,a.Yb,a.$b):null;if(a.Dc.length||!c||c&&c.socket.readyState===c.socket.CLOSING||c&&c.socket.readyState===c.socket.CLOSED)b|=
65;if(!c||c&&c.socket.readyState===c.socket.OPEN)b|=4;if(c&&c.socket.readyState===c.socket.CLOSING||c&&c.socket.readyState===c.socket.CLOSED)b|=16;return b},yc:function(a,b,c){switch(b){case 21531:return b=0,a.Dc.length&&(b=a.Dc[0].data.length),t()[c>>2]=b,0;default:return 28}},close:function(a){if(a.Sb){try{a.Sb.close()}catch(f){}a.Sb=null}for(var b=Object.keys(a.Qc),c=0;c<b.length;c++){var d=a.Qc[b[c]];try{d.socket.close()}catch(f){}N.Vb.le(a,d)}return 0},bind:function(a,b,c){if("undefined"!==typeof a.ed||
"undefined"!==typeof a.vc)throw new M.Ib(28);a.ed=b;a.vc=c;if(2===a.type){a.Sb&&(a.Sb.close(),a.Sb=null);try{a.Zb.listen(a,0)}catch(d){if(!(d instanceof M.Ib))throw d;if(138!==d.Mb)throw d;}}},connect:function(a,b,c){if(a.Sb)throw new M.Ib(138);if("undefined"!==typeof a.Yb&&"undefined"!==typeof a.$b){var d=N.Vb.Yc(a,a.Yb,a.$b);if(d){if(d.socket.readyState===d.socket.CONNECTING)throw new M.Ib(7);throw new M.Ib(30);}}b=N.Vb.Wc(a,b,c);a.Yb=b.Qb;a.$b=b.port;throw new M.Ib(26);},listen:function(a){if(!B)throw new M.Ib(138);
if(a.Sb)throw new M.Ib(28);var b=require("ws").Server;a.Sb=new b({host:a.ed,port:a.vc});x.websocket.emit("listen",a.stream.fd);a.Sb.on("connection",function(c){if(1===a.type){var d=N.createSocket(a.family,a.type,a.protocol);c=N.Vb.Wc(d,c);d.Yb=c.Qb;d.$b=c.port;a.pending.push(d);x.websocket.emit("connection",d.stream.fd)}else N.Vb.Wc(a,c),x.websocket.emit("connection",a.stream.fd)});a.Sb.on("closed",function(){x.websocket.emit("close",a.stream.fd);a.Sb=null});a.Sb.on("error",function(){a.error=23;
x.websocket.emit("error",[a.stream.fd,a.error,"EHOSTUNREACH: Host is unreachable"])})},accept:function(a){if(!a.Sb)throw new M.Ib(28);var b=a.pending.shift();b.stream.flags=a.stream.flags;return b},Pf:function(a,b){if(b){if(void 0===a.Yb||void 0===a.$b)throw new M.Ib(53);b=a.Yb;a=a.$b}else b=a.ed||0,a=a.vc||0;return{Qb:b,port:a}},ne:function(a,b,c,d,f,g){if(2===a.type){if(void 0===f||void 0===g)f=a.Yb,g=a.$b;if(void 0===f||void 0===g)throw new M.Ib(17);}else f=a.Yb,g=a.$b;var k=N.Vb.Yc(a,f,g);if(1===
a.type){if(!k||k.socket.readyState===k.socket.CLOSING||k.socket.readyState===k.socket.CLOSED)throw new M.Ib(53);if(k.socket.readyState===k.socket.CONNECTING)throw new M.Ib(6);}ArrayBuffer.isView(b)&&(c+=b.byteOffset,b=b.buffer);var m;b instanceof SharedArrayBuffer?m=(new Uint8Array(new Uint8Array(b.slice(c,c+d)))).buffer:m=b.slice(c,c+d);if(2===a.type&&(!k||k.socket.readyState!==k.socket.OPEN))return k&&k.socket.readyState!==k.socket.CLOSING&&k.socket.readyState!==k.socket.CLOSED||(k=N.Vb.Wc(a,f,
g)),k.Xc.push(m),d;try{return k.socket.send(m),d}catch(q){throw new M.Ib(28);}},ke:function(a,b){if(1===a.type&&a.Sb)throw new M.Ib(53);var c=a.Dc.shift();if(!c){if(1===a.type){if(a=N.Vb.Yc(a,a.Yb,a.$b)){if(a.socket.readyState===a.socket.CLOSING||a.socket.readyState===a.socket.CLOSED)return null;throw new M.Ib(6);}throw new M.Ib(53);}throw new M.Ib(6);}var d=c.data.byteLength||c.data.length,f=c.data.byteOffset||0,g=c.data.buffer||c.data;b=Math.min(b,d);var k={buffer:new Uint8Array(g,f,b),Qb:c.Qb,
port:c.port};1===a.type&&b<d&&(c.data=new Uint8Array(g,f+b,d-b),a.Dc.unshift(c));return k}}};function nc(a){a=N.Ne(a);if(!a)throw new M.Ib(8);return a}function oc(a){a=a.split(".");for(var b=0;4>b;b++){var c=Number(a[b]);if(isNaN(c))return null;a[b]=c}return(a[0]|a[1]<<8|a[2]<<16|a[3]<<24)>>>0}
function pc(a){var b,c,d=[];if(!/^((?=.*::)(?!.*::.+::)(::)?([\dA-F]{1,4}:(:|\b)|){5}|([\dA-F]{1,4}:){6})((([\dA-F]{1,4}((?!\3)::|:\b|$))|(?!\2\3)){2}|(((2[0-4]|1\d|[1-9])?\d|25[0-5])\.?\b){4})$/i.test(a))return null;if("::"===a)return[0,0,0,0,0,0,0,0];a=a.startsWith("::")?a.replace("::","Z:"):a.replace("::",":Z:");0<a.indexOf(".")?(a=a.replace(/[.]/g,":"),a=a.split(":"),a[a.length-4]=parseInt(a[a.length-4])+256*parseInt(a[a.length-3]),a[a.length-3]=parseInt(a[a.length-2])+256*parseInt(a[a.length-
1]),a=a.slice(0,a.length-2)):a=a.split(":");for(b=c=0;b<a.length;b++)if("string"===typeof a[b])if("Z"===a[b]){for(c=0;c<8-a.length+1;c++)d[b+c]=0;--c}else d[b+c]=qc(parseInt(a[b],16));else d[b+c]=a[b];return[d[1]<<16|d[0],d[3]<<16|d[2],d[5]<<16|d[4],d[7]<<16|d[6]]}
function rc(a,b,c,d,f){switch(b){case 2:c=oc(c);f&&(t()[f>>2]=16);ea()[a>>1]=b;t()[a+4>>2]=c;ea()[a+2>>1]=qc(d);R=[0,(Q=0,1<=+Math.abs(Q)?0<Q?(Math.min(+Math.floor(Q/4294967296),4294967295)|0)>>>0:~~+Math.ceil((Q-+(~~Q>>>0))/4294967296)>>>0:0)];t()[a+8>>2]=R[0];t()[a+12>>2]=R[1];break;case 10:c=pc(c);f&&(t()[f>>2]=28);t()[a>>2]=b;t()[a+8>>2]=c[0];t()[a+12>>2]=c[1];t()[a+16>>2]=c[2];t()[a+20>>2]=c[3];ea()[a+2>>1]=qc(d);t()[a+4>>2]=0;t()[a+24>>2]=0;break;default:return 5}return 0}
var sc=1,tc={},uc={};function vc(a){var b=oc(a);if(null!==b)return a;b=pc(a);if(null!==b)return a;tc[a]?b=tc[a]:(b=sc++,assert(65535>b,"exceeded max address mappings of 65535"),b="172.29."+(b&255)+"."+(b&65280),uc[b]=a,tc[a]=b);return b}function wc(a,b,c,d){if(C)return V(4,1,a,b,c,d);try{var f=nc(a),g=f.Zb.accept(f);b&&rc(b,g.family,vc(g.Yb),g.$b,c);return g.stream.fd}catch(k){return"undefined"!==typeof M&&k instanceof M.Ib||E(k),-k.Mb}}
function xc(a,b){if(C)return V(5,1,a,b);try{a=I(a);if(b&-8)var c=-28;else{var d;(d=M.Nb(a,{ac:!0}).node)?(a="",b&4&&(a+="r"),b&2&&(a+="w"),b&1&&(a+="x"),c=a&&M.nc(d,a)?-2:0):c=-44}return c}catch(f){return"undefined"!==typeof M&&f instanceof M.Ib||E(f),-f.Mb}}function yc(a){return(a&255)+"."+(a>>8&255)+"."+(a>>16&255)+"."+(a>>24&255)}
function zc(a){var b="",c,d=0,f=0,g=0,k=0;a=[a[0]&65535,a[0]>>16,a[1]&65535,a[1]>>16,a[2]&65535,a[2]>>16,a[3]&65535,a[3]>>16];var m=!0;for(c=0;5>c;c++)if(0!==a[c]){m=!1;break}if(m){c=yc(a[6]|a[7]<<16);if(-1===a[5])return"::ffff:"+c;if(0===a[5])return"0.0.0.0"===c&&(c=""),"0.0.0.1"===c&&(c="1"),"::"+c}for(c=0;8>c;c++)0===a[c]&&(1<c-f&&(k=0),f=c,k++),k>d&&(d=k,g=c-d+1);for(c=0;8>c;c++)1<d&&0===a[c]&&c>=g&&c<g+d?c===g&&(b+=":",0===g&&(b+=":")):(b+=Number(Ac(a[c]&65535)).toString(16),b+=7>c?":":"");return b}
function Bc(a,b){var c=ea()[a>>1],d=Ac;h.buffer!=l&&aa(h.buffer);d=d(Wa[a+2>>1]);switch(c){case 2:if(16!==b)return{Mb:28};a=t()[a+4>>2];a=yc(a);break;case 10:if(28!==b)return{Mb:28};a=[t()[a+8>>2],t()[a+12>>2],t()[a+16>>2],t()[a+20>>2]];a=zc(a);break;default:return{Mb:5}}return{family:c,Qb:a,port:d}}function Cc(a,b,c){if(c&&0===a)return null;a=Bc(a,b);if(a.Mb)throw new M.Ib(a.Mb);b=a.Qb;a.Qb=(uc[b]?uc[b]:null)||a.Qb;return a}
function Dc(a,b,c){if(C)return V(6,1,a,b,c);try{var d=nc(a),f=Cc(b,c);d.Zb.bind(d,f.Qb,f.port);return 0}catch(g){return"undefined"!==typeof M&&g instanceof M.Ib||E(g),-g.Mb}}function Ec(a,b,c){if(C)return V(7,1,a,b,c);try{var d=nc(a),f=Cc(b,c);d.Zb.connect(d,f.Qb,f.port);return 0}catch(g){return"undefined"!==typeof M&&g instanceof M.Ib||E(g),-g.Mb}}
function Fc(a,b,c){if(C)return V(8,1,a,b,c);jc=c;try{var d=lc(a);switch(b){case 0:var f=kc();return 0>f?-28:M.open(d.path,d.flags,0,f).fd;case 1:case 2:return 0;case 3:return d.flags;case 4:return f=kc(),d.flags|=f,0;case 12:return f=kc(),ea()[f+0>>1]=2,0;case 13:case 14:return 0;case 16:case 8:return-28;case 9:return t()[Kb()>>2]=28,-1;default:return-28}}catch(g){return"undefined"!==typeof M&&g instanceof M.Ib||E(g),-g.Mb}}
function Gc(a,b){if(C)return V(9,1,a,b);try{var c=lc(a);return ic(M.stat,c.path,b)}catch(d){return"undefined"!==typeof M&&d instanceof M.Ib||E(d),-d.Mb}}
function Hc(a,b,c){if(C)return V(10,1,a,b,c);try{var d=lc(a);d.qc||(d.qc=M.readdir(d.path));a=0;for(var f=M.Wb(d,0,1),g=Math.floor(f/280);g<d.qc.length&&a+280<=c;){var k=d.qc[g];if("."===k[0]){var m=1;var q=4}else{var p=M.ec(d.node,k);m=p.id;q=M.Mc(p.mode)?2:M.Rb(p.mode)?4:M.rc(p.mode)?10:8}R=[m>>>0,(Q=m,1<=+Math.abs(Q)?0<Q?(Math.min(+Math.floor(Q/4294967296),4294967295)|0)>>>0:~~+Math.ceil((Q-+(~~Q>>>0))/4294967296)>>>0:0)];t()[b+a>>2]=R[0];t()[b+a+4>>2]=R[1];R=[280*(g+1)>>>0,(Q=280*(g+1),1<=+Math.abs(Q)?
0<Q?(Math.min(+Math.floor(Q/4294967296),4294967295)|0)>>>0:~~+Math.ceil((Q-+(~~Q>>>0))/4294967296)>>>0:0)];t()[b+a+8>>2]=R[0];t()[b+a+12>>2]=R[1];ea()[b+a+16>>1]=280;e()[b+a+18>>0]=q;Ma(k,b+a+19,256);a+=280;g+=1}M.Wb(d,280*g,0);return a}catch(r){return"undefined"!==typeof M&&r instanceof M.Ib||E(r),-r.Mb}}function Ic(a,b,c){if(C)return V(11,1,a,b,c);try{var d=nc(a);if(!d.Yb)return-53;rc(b,d.family,vc(d.Yb),d.$b,c);return 0}catch(f){return"undefined"!==typeof M&&f instanceof M.Ib||E(f),-f.Mb}}
function Jc(a,b){if(C)return V(12,1,a,b);try{return Kc(b,0,136),t()[b>>2]=1,t()[b+4>>2]=2,t()[b+8>>2]=3,t()[b+12>>2]=4,0}catch(c){return"undefined"!==typeof M&&c instanceof M.Ib||E(c),-c.Mb}}function Lc(a,b,c){if(C)return V(13,1,a,b,c);try{z("__sys_getsockname "+a);var d=nc(a);rc(b,d.family,vc(d.ed||"0.0.0.0"),d.vc,c);return 0}catch(f){return"undefined"!==typeof M&&f instanceof M.Ib||E(f),-f.Mb}}
function Mc(a,b,c,d,f){if(C)return V(14,1,a,b,c,d,f);try{var g=nc(a);return 1===b&&4===c?(t()[d>>2]=g.error,t()[f>>2]=4,g.error=null,0):-50}catch(k){return"undefined"!==typeof M&&k instanceof M.Ib||E(k),-k.Mb}}
function Nc(a,b,c){if(C)return V(15,1,a,b,c);jc=c;try{var d=lc(a);switch(b){case 21509:case 21505:return d.tty?0:-59;case 21510:case 21511:case 21512:case 21506:case 21507:case 21508:return d.tty?0:-59;case 21519:if(!d.tty)return-59;var f=kc();return t()[f>>2]=0;case 21520:return d.tty?-28:-59;case 21531:return f=kc(),M.yc(d,b,f);case 21523:return d.tty?0:-59;case 21524:return d.tty?0:-59;default:E("bad ioctl syscall "+b)}}catch(g){return"undefined"!==typeof M&&g instanceof M.Ib||E(g),-g.Mb}}
function Oc(a,b){if(C)return V(16,1,a,b);try{var c=nc(a);c.Zb.listen(c,b);return 0}catch(d){return"undefined"!==typeof M&&d instanceof M.Ib||E(d),-d.Mb}}function Pc(a,b){if(C)return V(17,1,a,b);try{return a=I(a),ic(M.lstat,a,b)}catch(c){return"undefined"!==typeof M&&c instanceof M.Ib||E(c),-c.Mb}}function Qc(a,b){if(C)return V(18,1,a,b);try{return a=I(a),a=Tb(a),"/"===a[a.length-1]&&(a=a.substr(0,a.length-1)),M.mkdir(a,b,0),0}catch(c){return"undefined"!==typeof M&&c instanceof M.Ib||E(c),-c.Mb}}
function Rc(a,b,c,d,f,g){if(C)return V(19,1,a,b,c,d,f,g);try{a:{g<<=12;var k=!1;if(0!==(d&16)&&0!==a%65536)var m=-28;else{if(0!==(d&32)){var q=Sc(65536,b);if(!q){m=-48;break a}Kc(q,0,b);k=!0}else{var p=M.dc(f);if(!p){m=-8;break a}var r=M.zc(p,a,b,g,c,d);q=r.gf;k=r.pd}hc[q]={Xe:q,Ue:b,pd:k,fd:f,ff:c,flags:d,offset:g};m=q}}return m}catch(y){return"undefined"!==typeof M&&y instanceof M.Ib||E(y),-y.Mb}}
function Tc(a,b){if(C)return V(20,1,a,b);try{if(-1===(a|0)||0===b)var c=-28;else{var d=hc[a];if(d&&b===d.Ue){var f=M.dc(d.fd);if(f&&d.ff&2){var g=d.flags,k=d.offset,m=ca().slice(a,a+b);M.Ac(f,m,k,b,g)}hc[a]=null;d.pd&&Bb(d.Xe)}c=0}return c}catch(q){return"undefined"!==typeof M&&q instanceof M.Ib||E(q),-q.Mb}}function Uc(a,b,c){if(C)return V(21,1,a,b,c);jc=c;try{var d=I(a),f=c?kc():0;return M.open(d,b,f).fd}catch(g){return"undefined"!==typeof M&&g instanceof M.Ib||E(g),-g.Mb}}
function Vc(a,b,c){if(C)return V(22,1,a,b,c);try{for(var d=c=0;d<b;d++){var f=a+8*d,g=t()[f>>2],k=ea()[f+4>>1],m=32,q=M.dc(g);q&&(m=5,q.Kb.Cc&&(m=q.Kb.Cc(q)));(m&=k|24)&&c++;ea()[f+6>>1]=m}return c}catch(p){return"undefined"!==typeof M&&p instanceof M.Ib||E(p),-p.Mb}}function Wc(a,b,c,d){if(C)return V(23,1,a,b,c,d);try{return d&&(t()[d>>2]=-1,t()[d+4>>2]=-1,t()[d+8>>2]=-1,t()[d+12>>2]=-1),0}catch(f){return"undefined"!==typeof M&&f instanceof M.Ib||E(f),-f.Mb}}
function Xc(a,b,c,d,f,g){if(C)return V(24,1,a,b,c,d,f,g);try{var k=nc(a),m=k.Zb.ke(k,c);if(!m)return 0;f&&rc(f,k.family,vc(m.Qb),m.port,g);ca().set(m.buffer,b);return m.buffer.byteLength}catch(q){return"undefined"!==typeof M&&q instanceof M.Ib||E(q),-q.Mb}}function Yc(a,b){if(C)return V(25,1,a,b);try{return a=I(a),b=I(b),M.rename(a,b),0}catch(c){return"undefined"!==typeof M&&c instanceof M.Ib||E(c),-c.Mb}}
function Zc(a){if(C)return V(26,1,a);try{return a=I(a),M.rmdir(a),0}catch(b){return"undefined"!==typeof M&&b instanceof M.Ib||E(b),-b.Mb}}function $c(a,b,c,d,f,g){if(C)return V(27,1,a,b,c,d,f,g);try{var k=nc(a),m=Cc(f,g,!0);return m?k.Zb.ne(k,e(),b,c,m.Qb,m.port):M.write(k.stream,e(),b,c)}catch(q){return"undefined"!==typeof M&&q instanceof M.Ib||E(q),-q.Mb}}function ad(a){return C?V(28,1,a):-50}
function bd(a,b){if(C)return V(29,1,a,b);try{return nc(a),-52}catch(c){return"undefined"!==typeof M&&c instanceof M.Ib||E(c),-c.Mb}}function cd(a,b,c){if(C)return V(30,1,a,b,c);try{return N.createSocket(a,b,c).stream.fd}catch(d){return"undefined"!==typeof M&&d instanceof M.Ib||E(d),-d.Mb}}function dd(a,b){if(C)return V(31,1,a,b);try{return a=I(a),ic(M.stat,a,b)}catch(c){return"undefined"!==typeof M&&c instanceof M.Ib||E(c),-c.Mb}}
function ed(a){if(C)return V(32,1,a);try{return a=I(a),M.unlink(a),0}catch(b){return"undefined"!==typeof M&&b instanceof M.Ib||E(b),-b.Mb}}function fd(){void 0===fd.start&&(fd.start=Date.now());return 1E3*(Date.now()-fd.start)|0}var gd=[];
function hd(){B||A||(Ea||(Ea={}),Ea["Blocking on the main thread is very dangerous, see https://emscripten.org/docs/porting/pthreads.html#blocking-on-the-main-browser-thread"]||(Ea["Blocking on the main thread is very dangerous, see https://emscripten.org/docs/porting/pthreads.html#blocking-on-the-main-browser-thread"]=1,z("Blocking on the main thread is very dangerous, see https://emscripten.org/docs/porting/pthreads.html#blocking-on-the-main-browser-thread")))}
function jd(a,b,c){if(0>=a||a>e().length||a&1)return-28;if(va){if(Atomics.load(t(),a>>2)!=b)return-6;var d=performance.now();c=d+c;for(Atomics.exchange(t(),sb>>2,a);;){d=performance.now();if(d>c)return Atomics.exchange(t(),sb>>2,0),-73;d=Atomics.exchange(t(),sb>>2,0);if(0==d)break;Db();if(Atomics.load(t(),a>>2)!=b)return-6;Atomics.exchange(t(),sb>>2,a)}return 0}a=Atomics.wait(t(),a>>2,b,c);if("timed-out"===a)return-73;if("not-equal"===a)return-6;if("ok"===a)return 0;throw"Atomics.wait returned an unexpected value "+
a;}function V(a,b){for(var c=arguments.length-2,d=F(),f=La(8*c),g=f>>3,k=0;k<c;k++){var m=arguments[2+k];ja()[g+k]=m}c=kd(a,c,f,b);J(d);return c}var ld=[],md=[0,"undefined"!==typeof document?document:0,"undefined"!==typeof window?window:0];function nd(a){a=2<a?I(a):a;return md[a]||("undefined"!==typeof document?document.querySelector(a):void 0)}
function od(a,b,c){var d=nd(a);if(!d)return-4;d.Vc&&(t()[d.Vc>>2]=b,t()[d.Vc+4>>2]=c);if(d.ie||!d.Gf)d.ie&&(d=d.ie),a=!1,d.Uc&&d.Uc.Tc&&(a=d.Uc.Tc.getParameter(2978),a=0===a[0]&&0===a[1]&&a[2]===d.width&&a[3]===d.height),d.width=b,d.height=c,a&&d.Uc.Tc.viewport(0,0,b,c);else{if(d.Vc){d=t()[d.Vc+8>>2];a=a?I(a):"";var f=F(),g=La(12),k=0;if(a){k=Sa(a)+1;var m=K(k);Ma(a,m,k);k=m}t()[g>>2]=k;t()[g+4>>2]=b;t()[g+8>>2]=c;pd(0,d,657457152,0,k,g);J(f);return 1}return-4}return 0}
function qd(a,b,c){return C?V(33,1,a,b,c):od(a,b,c)}function rd(a){var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=function(c,d){b.vertexAttribDivisorANGLE(c,d)},a.drawArraysInstanced=function(c,d,f,g){b.drawArraysInstancedANGLE(c,d,f,g)},a.drawElementsInstanced=function(c,d,f,g,k){b.drawElementsInstancedANGLE(c,d,f,g,k)})}
function sd(a){var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=function(){return b.createVertexArrayOES()},a.deleteVertexArray=function(c){b.deleteVertexArrayOES(c)},a.bindVertexArray=function(c){b.bindVertexArrayOES(c)},a.isVertexArray=function(c){return b.isVertexArrayOES(c)})}function td(a){var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=function(c,d){b.drawBuffersWEBGL(c,d)})}
function ud(a,b){a.ae||(a.ae=a.getContext,a.getContext=function(d,f){f=a.ae(d,f);return"webgl"==d==f instanceof WebGLRenderingContext?f:null});var c=a.getContext("webgl",b);return c?vd(c,b):0}function vd(a,b){var c=K(8);t()[c+4>>2]=zb();var d={Qf:c,attributes:b,version:b.We,Tc:a};a.canvas&&(a.canvas.Uc=d);("undefined"===typeof b.Vd||b.Vd)&&wd(d);return c}
function wd(a){a||(a=xd);if(!a.Pe){a.Pe=!0;var b=a.Tc;rd(b);sd(b);td(b);b.Kf=b.getExtension("EXT_disjoint_timer_query");b.Wf=b.getExtension("WEBGL_multi_draw");(b.getSupportedExtensions()||[]).forEach(function(c){c.includes("lose_context")||c.includes("debug")||b.getExtension(c)})}}var xd,yd=["default","low-power","high-performance"],zd={};
function Ad(){if(!Bd){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"===typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:ta||"./this.program"},b;for(b in zd)void 0===zd[b]?delete a[b]:a[b]=zd[b];var c=[];for(b in a)c.push(b+"="+a[b]);Bd=c}return Bd}var Bd;
function Cd(a,b){if(C)return V(34,1,a,b);try{var c=0;Ad().forEach(function(d,f){var g=b+c;t()[a+4*f>>2]=g;Va(d,g);c+=d.length+1});return 0}catch(d){return"undefined"!==typeof M&&d instanceof M.Ib||E(d),d.Mb}}function Dd(a,b){if(C)return V(35,1,a,b);try{var c=Ad();t()[a>>2]=c.length;var d=0;c.forEach(function(f){d+=f.length+1});t()[b>>2]=d;return 0}catch(f){return"undefined"!==typeof M&&f instanceof M.Ib||E(f),f.Mb}}
function Ed(a){if(C)return V(36,1,a);try{var b=lc(a);M.close(b);return 0}catch(c){return"undefined"!==typeof M&&c instanceof M.Ib||E(c),c.Mb}}function Fd(a,b){if(C)return V(37,1,a,b);try{var c=lc(a),d=c.tty?2:M.Rb(c.mode)?3:M.rc(c.mode)?7:4;e()[b>>0]=d;return 0}catch(f){return"undefined"!==typeof M&&f instanceof M.Ib||E(f),f.Mb}}
function Gd(a,b,c,d){if(C)return V(38,1,a,b,c,d);try{a:{for(var f=lc(a),g=a=0;g<c;g++){var k=t()[b+8*g>>2],m=t()[b+(8*g+4)>>2],q=M.read(f,e(),k,m,void 0);if(0>q){var p=-1;break a}a+=q;if(q<m)break}p=a}t()[d>>2]=p;return 0}catch(r){return"undefined"!==typeof M&&r instanceof M.Ib||E(r),r.Mb}}
function Hd(a,b,c,d,f){if(C)return V(39,1,a,b,c,d,f);try{var g=lc(a);a=4294967296*c+(b>>>0);if(-9007199254740992>=a||9007199254740992<=a)return-61;M.Wb(g,a,d);R=[g.position>>>0,(Q=g.position,1<=+Math.abs(Q)?0<Q?(Math.min(+Math.floor(Q/4294967296),4294967295)|0)>>>0:~~+Math.ceil((Q-+(~~Q>>>0))/4294967296)>>>0:0)];t()[f>>2]=R[0];t()[f+4>>2]=R[1];g.qc&&0===a&&0===d&&(g.qc=null);return 0}catch(k){return"undefined"!==typeof M&&k instanceof M.Ib||E(k),k.Mb}}
function Id(a,b,c,d){if(C)return V(40,1,a,b,c,d);try{a:{for(var f=lc(a),g=a=0;g<c;g++){var k=t()[b+8*g>>2],m=t()[b+(8*g+4)>>2],q=M.write(f,e(),k,m,void 0);if(0>q){var p=-1;break a}a+=q}p=a}t()[d>>2]=p;return 0}catch(r){return"undefined"!==typeof M&&r instanceof M.Ib||E(r),r.Mb}}var Y={};
function Jd(a){Jd.buffer||(Jd.buffer=K(256),Y["0"]="Success",Y["-1"]="Invalid value for 'ai_flags' field",Y["-2"]="NAME or SERVICE is unknown",Y["-3"]="Temporary failure in name resolution",Y["-4"]="Non-recoverable failure in name res",Y["-6"]="'ai_family' not supported",Y["-7"]="'ai_socktype' not supported",Y["-8"]="SERVICE not supported for 'ai_socktype'",Y["-10"]="Memory allocation failure",Y["-11"]="System error returned in 'errno'",Y["-12"]="Argument buffer overflow");var b="Unknown error";a in
Y&&(255<Y[a].length?b="Message too long":b=Y[a]);Va(b,Jd.buffer);return Jd.buffer}
function Kd(a,b,c,d){function f(y,G,n,v,w,P){var T=10===y?28:16;w=10===y?zc(w):yc(w);T=K(T);w=rc(T,y,w,P);assert(!w);w=K(32);t()[w+4>>2]=y;t()[w+8>>2]=G;t()[w+12>>2]=n;t()[w+24>>2]=v;t()[w+20>>2]=T;10===y?t()[w+16>>2]=28:t()[w+16>>2]=16;t()[w+28>>2]=0;return w}if(C)return V(41,1,a,b,c,d);var g=0,k=0,m=0,q=0,p=0,r=0;c&&(m=t()[c>>2],q=t()[c+4>>2],p=t()[c+8>>2],r=t()[c+12>>2]);p&&!r&&(r=2===p?17:6);!p&&r&&(p=17===r?2:1);0===r&&(r=6);0===p&&(p=1);if(!a&&!b)return-2;if(m&-1088||0!==c&&t()[c>>2]&2&&!a)return-1;
if(m&32)return-2;if(0!==p&&1!==p&&2!==p)return-7;if(0!==q&&2!==q&&10!==q)return-6;if(b&&(b=I(b),k=parseInt(b,10),isNaN(k)))return m&1024?-2:-8;if(!a)return 0===q&&(q=2),0===(m&1)&&(2===q?g=Ld(2130706433):g=[0,0,0,1]),a=f(q,p,r,null,g,k),t()[d>>2]=a,0;a=I(a);g=oc(a);if(null!==g)if(0===q||2===q)q=2;else if(10===q&&m&8)g=[0,0,Ld(65535),g],q=10;else return-2;else if(g=pc(a),null!==g)if(0===q||10===q)q=10;else return-2;if(null!=g)return a=f(q,p,r,a,g,k),t()[d>>2]=a,0;if(m&4)return-2;a=vc(a);g=oc(a);0===
q?q=2:10===q&&(g=[0,0,Ld(65535),g]);a=f(q,p,r,null,g,k);t()[d>>2]=a;return 0}
function Eb(a){if(C)throw"Internal Error! spawnThread() can only ever be called from main application thread!";var b=S.Me();if(!b)return 6;if(void 0!==b.cc)throw"Internal error!";if(!a.cd)throw"Internal error, no pthread ptr!";S.oc.push(b);for(var c=K(512),d=0;128>d;++d)t()[c+4*d>>2]=0;var f=a.wc+a.Fc;d=S.jc[a.cd]={worker:b,wc:a.wc,Fc:a.Fc,qd:a.qd,kc:a.cd};var g=d.kc>>2;Atomics.store(u(),g+16,a.detached);Atomics.store(u(),g+25,c);Atomics.store(u(),g+10,d.kc);Atomics.store(u(),g+20,a.Fc);Atomics.store(u(),
g+19,f);Atomics.store(u(),g+26,a.Fc);Atomics.store(u(),g+28,f);Atomics.store(u(),g+29,a.detached);c=Md()+40;Atomics.store(u(),g+43,c);b.cc=d;var k={cmd:"run",start_routine:a.pf,arg:a.Kc,threadInfoStruct:a.cd,stackBase:a.wc,stackSize:a.Fc};b.Rc=function(){k.time=performance.now();b.postMessage(k,a.zf)};b.loaded&&(b.Rc(),delete b.Rc);return 0}
function Nd(a,b){if(!a)return z("pthread_join attempted on a null thread pointer!"),71;if(C&&zb()==a)return z("PThread "+a+" is attempting to join to itself!"),16;if(!C&&Od()==a)return z("Main thread "+a+" is attempting to join to itself!"),16;if(t()[a+12>>2]!==a)return z("pthread_join attempted on thread "+a+", which does not point to a valid thread, or does not exist anymore!"),71;if(Atomics.load(u(),a+64>>2))return z("Attempted to join thread "+a+", which was already detached!"),28;for(hd();;){var c=
Atomics.load(u(),a+0>>2);if(1==c)return c=Atomics.load(u(),a+4>>2),b&&(t()[b>>2]=c),Atomics.store(u(),a+64>>2,1),C?postMessage({cmd:"cleanupThread",thread:a}):ub(a),0;if(C){var d=zb();if(d&&!Atomics.load(u(),d+56>>2)&&2==Atomics.load(u(),d+0>>2))throw"Canceled!";}C||Db();jd(a+0,c,C?100:1)}}function Pd(a){return 0===a%4&&(0!==a%100||0===a%400)}function Qd(a,b){for(var c=0,d=0;d<=b;c+=a[d++]);return c}var Rd=[31,29,31,30,31,30,31,31,30,31,30,31],Sd=[31,28,31,30,31,30,31,31,30,31,30,31];
function Td(a,b){for(a=new Date(a.getTime());0<b;){var c=a.getMonth(),d=(Pd(a.getFullYear())?Rd:Sd)[c];if(b>d-a.getDate())b-=d-a.getDate()+1,a.setDate(1),11>c?a.setMonth(c+1):(a.setMonth(0),a.setFullYear(a.getFullYear()+1));else{a.setDate(a.getDate()+b);break}}return a}function Ud(a,b,c,d){a||(a=this);this.parent=a;this.Ob=a.Ob;this.Oc=null;this.id=M.af++;this.name=b;this.mode=c;this.Jb={};this.Kb={};this.rdev=d}
Object.defineProperties(Ud.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(a){a?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(a){a?this.mode|=146:this.mode&=-147}},Te:{get:function(){return M.Rb(this.mode)}},zd:{get:function(){return M.Mc(this.mode)}}});M.qe=Ud;M.qf();var fc;x.FS_mount=M.Ob;x.FS_unmount=M.Bf;x.FS_filesystems=M.Yd;
var Vd=[null,function(a,b){if(C)return V(1,1,a,b)},Nb,mc,wc,xc,Dc,Ec,Fc,Gc,Hc,Ic,Jc,Lc,Mc,Nc,Oc,Pc,Qc,Rc,Tc,Uc,Vc,Wc,Xc,Yc,Zc,$c,ad,bd,cd,dd,ed,qd,Cd,Dd,Ed,Fd,Gd,Hd,Id,Kd];function cc(a,b){var c=Array(Sa(a)+1);a=Ra(a,c,0,c.length);b&&(c.length=a);return c}
var oe={c:function(a,b,c,d){E("Assertion failed: "+I(a)+", at: "+[b?I(b):"unknown filename",c,d?I(d):"unknown function"])},Ja:function(a,b){Wd(a,b)},J:function(a,b){return Jb(a,b)},Qa:function(a,b){return Lb(a,b)},na:function(a,b){return Mb(a,b)},ma:function(a,b){return Rb(a,b)},ya:mc,ca:wc,Ba:xc,fa:Dc,ea:Ec,q:Fc,Ga:Gc,ra:Hc,aa:Ic,ua:Jc,ba:Lc,Z:Mc,O:Nc,da:Oc,Ha:Pc,Ia:Qc,pa:Rc,qa:function(){return 0},oa:Tc,Ea:function(){return-63},Q:Uc,xa:Vc,ta:Wc,_:Xc,Fa:Yc,Ca:Zc,$:$c,sa:function(){return 0},Y:ad,
ga:bd,I:cd,R:dd,va:function(a){try{if(!a)return-21;var b={__size__:390,domainname:325,machine:260,nodename:65,release:130,sysname:0,version:195};Va("Emscripten",a+b.sysname);Va("emscripten",a+b.nodename);Va("1.0",a+b.release);Va("#1",a+b.version);Va("wasm32",a+b.machine);return 0}catch(c){return"undefined"!==typeof M&&c instanceof M.Ib||E(c),-c.Mb}},Da:ed,Oa:function(a,b){if(a==b)postMessage({cmd:"processQueuedMainThreadWork"});else if(C)postMessage({targetThread:a,cmd:"processThreadQueue"});else{a=
(a=S.jc[a])&&a.worker;if(!a)return;a.postMessage({cmd:"processThreadQueue"})}return 1},ja:function(){throw"longjmp";},b:function(){E()},Pa:fd,Ta:Jb,W:function(){E("To use dlopen, you need to use Emscripten's linking support, see https://github.com/emscripten-core/emscripten/wiki/Linking")},Ua:function(){E("To use dlopen, you need to use Emscripten's linking support, see https://github.com/emscripten-core/emscripten/wiki/Linking")},T:function(a,b,c){gd.length=0;var d;for(c>>=2;d=ca()[b++];)(d=105>
d)&&c&1&&c++,gd.push(d?ja()[c++>>1]:t()[c]),++c;return qb[a].apply(null,gd)},wa:hd,C:function(){},w:jd,v:rb,za:function(){return 2146435072},u:Ib,ha:function(a,b,c){ca().copyWithin(a,b,b+c)},Aa:function(){return B?require("os").cpus().length:navigator.hardwareConcurrency},La:function(a,b,c){ld.length=b;c>>=3;for(var d=0;d<b;d++)ld[d]=ja()[c+d];return(0>a?qb[-a-1]:Vd[a]).apply(null,ld)},ia:function(a){var b=ca().length;a>>>=0;if(a<=b||2146435072<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=
Math.min(d,a+100663296);d=Math.max(a,d);0<d%65536&&(d+=65536-d%65536);a:{try{h.grow(Math.min(2146435072,d)-l.byteLength+65535>>>16);aa(h.buffer);var f=1;break a}catch(g){}f=void 0}if(f)return!0}return!1},Ma:function(a,b,c){return nd(a)?od(a,b,c):qd(a,b,c)},S:function(){},Ka:function(){},Na:function(a,b){b>>=2;var c=t()[b+6];b={alpha:!!t()[b],depth:!!t()[b+1],stencil:!!t()[b+2],antialias:!!t()[b+3],premultipliedAlpha:!!t()[b+4],preserveDrawingBuffer:!!t()[b+5],powerPreference:yd[c],failIfMajorPerformanceCaveat:!!t()[b+
7],We:t()[b+8],Uf:t()[b+9],Vd:t()[b+10],Je:t()[b+11],Yf:t()[b+12],Zf:t()[b+13]};a=nd(a);return!a||b.Je?0:ud(a,b)},ka:Cd,la:Dd,B:function(a){oa(a)},A:Ed,N:Fd,P:Gd,Va:Hd,E:Id,x:Jd,d:function(){return Fa},t:Kd,r:function(a,b,c,d,f,g,k){b=Bc(a,b);if(b.Mb)return-6;a=b.port;var m=b.Qb;b=!1;if(c&&d){var q;if(k&1||!(q=uc[m]?uc[m]:null)){if(k&8)return-2}else m=q;c=Ma(m,c,d);c+1>=d&&(b=!0)}f&&g&&(c=Ma(""+a,f,g),c+1>=g&&(b=!0));return b?-12:0},i:function(a){var b=Date.now();t()[a>>2]=b/1E3|0;t()[a+4>>2]=b%1E3*
1E3|0;return 0},o:Mb,Za:function(){S.Qe()},X:Xd,h:Yd,g:Zd,y:$d,H:ae,V:be,G:ce,Xa:de,Wa:ee,j:fe,s:ge,D:he,f:ie,F:je,Sa:ke,U:le,Ya:me,n:Rb,a:h||x.wasmMemory,L:function(a){Nb();var b=new Date(t()[a+20>>2]+1900,t()[a+16>>2],t()[a+12>>2],t()[a+8>>2],t()[a+4>>2],t()[a>>2],0),c=t()[a+32>>2],d=b.getTimezoneOffset(),f=new Date(b.getFullYear(),0,1),g=(new Date(b.getFullYear(),6,1)).getTimezoneOffset(),k=f.getTimezoneOffset(),m=Math.min(k,g);0>c?t()[a+32>>2]=Number(g!=k&&m==d):0<c!=(m==d)&&(g=Math.max(k,g),
b.setTime(b.getTime()+6E4*((0<c?m:g)-d)));t()[a+24>>2]=b.getDay();c=(b.getTime()-f.getTime())/864E5|0;t()[a+28>>2]=c;t()[a>>2]=b.getSeconds();t()[a+4>>2]=b.getMinutes();t()[a+8>>2]=b.getHours();t()[a+12>>2]=b.getDate();t()[a+16>>2]=b.getMonth();return b.getTime()/1E3|0},Ra:function(a){if(a===Od())return z("Main thread (id="+a+") cannot be canceled!"),71;if(!a)return z("pthread_cancel attempted on a null thread pointer!"),71;if(t()[a+12>>2]!==a)return z("pthread_cancel attempted on thread "+a+", which does not point to a valid thread, or does not exist anymore!"),
71;Atomics.compareExchange(u(),a+0>>2,0,2);C?postMessage({cmd:"cancelThread",thread:a}):tb(a);return 0},K:function(a){var b=S.hd.pop();a&&b()},M:Lb,l:function(a,b,c,d){if("undefined"===typeof SharedArrayBuffer)return z("Current environment does not support SharedArrayBuffer, pthreads are not available!"),6;if(!a)return z("pthread_create called with a null thread pointer!"),28;var f=[];if(C&&0===f.length)return ne(687865856,a,b,c,d);var g=0,k=0;if(b&&-1!=b){var m=t()[b>>2];m+=81920;g=t()[b+8>>2];k=
0!==t()[b+12>>2]}else m=2097152;(b=0==g)?g=Sc(16,m):(g-=m,assert(0<g));for(var q=K(228),p=0;57>p;++p)u()[(q>>2)+p]=0;t()[a>>2]=q;t()[q+12>>2]=q;a=q+152;t()[a>>2]=a;c={wc:g,Fc:m,qd:b,detached:k,pf:c,cd:q,Kc:d,zf:f};return C?(c.Ff="spawnThread",postMessage(c,f),0):Eb(c)},m:function(a,b){return Nd(a,b)},e:function(a){Fa=a},z:function(){return 0},k:function(a,b,c,d){function f(n,v,w){for(n="number"===typeof n?n.toString():n||"";n.length<v;)n=w[0]+n;return n}function g(n,v){return f(n,v,"0")}function k(n,
v){function w(T){return 0>T?-1:0<T?1:0}var P;0===(P=w(n.getFullYear()-v.getFullYear()))&&0===(P=w(n.getMonth()-v.getMonth()))&&(P=w(n.getDate()-v.getDate()));return P}function m(n){switch(n.getDay()){case 0:return new Date(n.getFullYear()-1,11,29);case 1:return n;case 2:return new Date(n.getFullYear(),0,3);case 3:return new Date(n.getFullYear(),0,2);case 4:return new Date(n.getFullYear(),0,1);case 5:return new Date(n.getFullYear()-1,11,31);case 6:return new Date(n.getFullYear()-1,11,30)}}function q(n){n=
Td(new Date(n.Xb+1900,0,1),n.ld);var v=new Date(n.getFullYear()+1,0,4),w=m(new Date(n.getFullYear(),0,4));v=m(v);return 0>=k(w,n)?0>=k(v,n)?n.getFullYear()+1:n.getFullYear():n.getFullYear()-1}var p=t()[d+40>>2];d={xf:t()[d>>2],wf:t()[d+4>>2],jd:t()[d+8>>2],Sc:t()[d+12>>2],Gc:t()[d+16>>2],Xb:t()[d+20>>2],kd:t()[d+24>>2],ld:t()[d+28>>2],bg:t()[d+32>>2],vf:t()[d+36>>2],yf:p?I(p):""};c=I(c);p={"%c":"%a %b %d %H:%M:%S %Y","%D":"%m/%d/%y","%F":"%Y-%m-%d","%h":"%b","%r":"%I:%M:%S %p","%R":"%H:%M","%T":"%H:%M:%S",
"%x":"%m/%d/%y","%X":"%H:%M:%S","%Ec":"%c","%EC":"%C","%Ex":"%m/%d/%y","%EX":"%H:%M:%S","%Ey":"%y","%EY":"%Y","%Od":"%d","%Oe":"%e","%OH":"%H","%OI":"%I","%Om":"%m","%OM":"%M","%OS":"%S","%Ou":"%u","%OU":"%U","%OV":"%V","%Ow":"%w","%OW":"%W","%Oy":"%y"};for(var r in p)c=c.replace(new RegExp(r,"g"),p[r]);var y="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),G="January February March April May June July August September October November December".split(" ");p={"%a":function(n){return y[n.kd].substring(0,
3)},"%A":function(n){return y[n.kd]},"%b":function(n){return G[n.Gc].substring(0,3)},"%B":function(n){return G[n.Gc]},"%C":function(n){return g((n.Xb+1900)/100|0,2)},"%d":function(n){return g(n.Sc,2)},"%e":function(n){return f(n.Sc,2," ")},"%g":function(n){return q(n).toString().substring(2)},"%G":function(n){return q(n)},"%H":function(n){return g(n.jd,2)},"%I":function(n){n=n.jd;0==n?n=12:12<n&&(n-=12);return g(n,2)},"%j":function(n){return g(n.Sc+Qd(Pd(n.Xb+1900)?Rd:Sd,n.Gc-1),3)},"%m":function(n){return g(n.Gc+
1,2)},"%M":function(n){return g(n.wf,2)},"%n":function(){return"\n"},"%p":function(n){return 0<=n.jd&&12>n.jd?"AM":"PM"},"%S":function(n){return g(n.xf,2)},"%t":function(){return"\t"},"%u":function(n){return n.kd||7},"%U":function(n){var v=new Date(n.Xb+1900,0,1),w=0===v.getDay()?v:Td(v,7-v.getDay());n=new Date(n.Xb+1900,n.Gc,n.Sc);return 0>k(w,n)?g(Math.ceil((31-w.getDate()+(Qd(Pd(n.getFullYear())?Rd:Sd,n.getMonth()-1)-31)+n.getDate())/7),2):0===k(w,v)?"01":"00"},"%V":function(n){var v=new Date(n.Xb+
1901,0,4),w=m(new Date(n.Xb+1900,0,4));v=m(v);var P=Td(new Date(n.Xb+1900,0,1),n.ld);return 0>k(P,w)?"53":0>=k(v,P)?"01":g(Math.ceil((w.getFullYear()<n.Xb+1900?n.ld+32-w.getDate():n.ld+1-w.getDate())/7),2)},"%w":function(n){return n.kd},"%W":function(n){var v=new Date(n.Xb,0,1),w=1===v.getDay()?v:Td(v,0===v.getDay()?1:7-v.getDay()+1);n=new Date(n.Xb+1900,n.Gc,n.Sc);return 0>k(w,n)?g(Math.ceil((31-w.getDate()+(Qd(Pd(n.getFullYear())?Rd:Sd,n.getMonth()-1)-31)+n.getDate())/7),2):0===k(w,v)?"01":"00"},
"%y":function(n){return(n.Xb+1900).toString().substring(2)},"%Y":function(n){return n.Xb+1900},"%z":function(n){n=n.vf;var v=0<=n;n=Math.abs(n)/60;return(v?"+":"-")+String("0000"+(n/60*100+n%60)).slice(-4)},"%Z":function(n){return n.yf},"%%":function(){return"%"}};for(r in p)c.includes(r)&&(c=c.replace(new RegExp(r,"g"),p[r](d)));r=cc(c,!1);if(r.length>b)return 0;Na(r,a);return r.length-1},p:function(a){var b=Date.now()/1E3|0;a&&(t()[a>>2]=b);return b}};
(function(){function a(f,g){x.asm=f.exports;L=x.asm.bb;bb.unshift(x.asm._a);S.Jd.push(x.asm.hb);Ha=g;C||lb()}function b(f){a(f.instance,f.module)}function c(f){return ob().then(function(g){return WebAssembly.instantiate(g,d)}).then(f,function(g){z("failed to asynchronously prepare wasm: "+g);E(g)})}var d={a:oe};C||kb();if(x.instantiateWasm)try{return x.instantiateWasm(d,a)}catch(f){return z("Module.instantiateWasm callback failed with error: "+f),!1}(function(){return Ga||"function"!==typeof WebAssembly.instantiateStreaming||
mb()||O.startsWith("file://")||"function"!==typeof fetch?c(b):fetch(O,{credentials:"same-origin"}).then(function(f){return WebAssembly.instantiateStreaming(f,d).then(b,function(g){z("wasm streaming compile failed: "+g);z("falling back to ArrayBuffer instantiation");return c(b)})})})().catch(ma);return{}})();x.___wasm_call_ctors=function(){return(x.___wasm_call_ctors=x.asm._a).apply(null,arguments)};
var Bb=x._free=function(){return(Bb=x._free=x.asm.$a).apply(null,arguments)},K=x._malloc=function(){return(K=x._malloc=x.asm.ab).apply(null,arguments)},Kb=x.___errno_location=function(){return(Kb=x.___errno_location=x.asm.cb).apply(null,arguments)},Sc=x._memalign=function(){return(Sc=x._memalign=x.asm.db).apply(null,arguments)},Ac=x._ntohs=function(){return(Ac=x._ntohs=x.asm.eb).apply(null,arguments)},qc=x._htons=function(){return(qc=x._htons=x.asm.fb).apply(null,arguments)},Wd=x._main=function(){return(Wd=
x._main=x.asm.gb).apply(null,arguments)};x._emscripten_tls_init=function(){return(x._emscripten_tls_init=x.asm.hb).apply(null,arguments)};var zb=x._pthread_self=function(){return(zb=x._pthread_self=x.asm.ib).apply(null,arguments)};x._emscripten_current_thread_process_queued_calls=function(){return(x._emscripten_current_thread_process_queued_calls=x.asm.jb).apply(null,arguments)};
var xb=x._emscripten_register_main_browser_thread_id=function(){return(xb=x._emscripten_register_main_browser_thread_id=x.asm.kb).apply(null,arguments)},Od=x._emscripten_main_browser_thread_id=function(){return(Od=x._emscripten_main_browser_thread_id=x.asm.lb).apply(null,arguments)},pb=x.__emscripten_do_dispatch_to_thread=function(){return(pb=x.__emscripten_do_dispatch_to_thread=x.asm.mb).apply(null,arguments)},ne=x._emscripten_sync_run_in_main_thread_4=function(){return(ne=x._emscripten_sync_run_in_main_thread_4=
x.asm.nb).apply(null,arguments)},Db=x._emscripten_main_thread_process_queued_calls=function(){return(Db=x._emscripten_main_thread_process_queued_calls=x.asm.ob).apply(null,arguments)},kd=x._emscripten_run_in_main_runtime_thread_js=function(){return(kd=x._emscripten_run_in_main_runtime_thread_js=x.asm.pb).apply(null,arguments)},pd=x.__emscripten_call_on_thread=function(){return(pd=x.__emscripten_call_on_thread=x.asm.qb).apply(null,arguments)};
x._emscripten_proxy_main=function(){return(x._emscripten_proxy_main=x.asm.rb).apply(null,arguments)};
var wb=x.__emscripten_thread_init=function(){return(wb=x.__emscripten_thread_init=x.asm.sb).apply(null,arguments)},Kc=x._memset=function(){return(Kc=x._memset=x.asm.tb).apply(null,arguments)},Ab=x.___pthread_tsd_run_dtors=function(){return(Ab=x.___pthread_tsd_run_dtors=x.asm.ub).apply(null,arguments)},Md=x._emscripten_get_global_libc=function(){return(Md=x._emscripten_get_global_libc=x.asm.vb).apply(null,arguments)},Ld=x._htonl=function(){return(Ld=x._htonl=x.asm.wb).apply(null,arguments)},Qb=x.__get_tzname=
function(){return(Qb=x.__get_tzname=x.asm.xb).apply(null,arguments)},Pb=x.__get_daylight=function(){return(Pb=x.__get_daylight=x.asm.yb).apply(null,arguments)},Ob=x.__get_timezone=function(){return(Ob=x.__get_timezone=x.asm.zb).apply(null,arguments)},F=x.stackSave=function(){return(F=x.stackSave=x.asm.Ab).apply(null,arguments)},J=x.stackRestore=function(){return(J=x.stackRestore=x.asm.Bb).apply(null,arguments)},La=x.stackAlloc=function(){return(La=x.stackAlloc=x.asm.Cb).apply(null,arguments)},Fb=
x._emscripten_stack_set_limits=function(){return(Fb=x._emscripten_stack_set_limits=x.asm.Db).apply(null,arguments)},Z=x._setThrew=function(){return(Z=x._setThrew=x.asm.Eb).apply(null,arguments)},pe=x.dynCall_vijjjid=function(){return(pe=x.dynCall_vijjjid=x.asm.Fb).apply(null,arguments)},qe=x.dynCall_iiiijj=function(){return(qe=x.dynCall_iiiijj=x.asm.Gb).apply(null,arguments)},re=x.dynCall_iij=function(){return(re=x.dynCall_iij=x.asm.Hb).apply(null,arguments)};x._ff_h264_cabac_tables=2558924;
var Cb=x.__emscripten_allow_main_runtime_queued_calls=5410016,sb=x.__emscripten_main_thread_futex=16979940;function Zd(a,b,c){var d=F();try{return L.get(a)(b,c)}catch(f){J(d);if(f!==f+0&&"longjmp"!==f)throw f;Z(1,0)}}function fe(a,b){var c=F();try{L.get(a)(b)}catch(d){J(c);if(d!==d+0&&"longjmp"!==d)throw d;Z(1,0)}}function ie(a,b,c,d,f){var g=F();try{L.get(a)(b,c,d,f)}catch(k){J(g);if(k!==k+0&&"longjmp"!==k)throw k;Z(1,0)}}
function ge(a,b,c){var d=F();try{L.get(a)(b,c)}catch(f){J(d);if(f!==f+0&&"longjmp"!==f)throw f;Z(1,0)}}function Yd(a,b){var c=F();try{return L.get(a)(b)}catch(d){J(c);if(d!==d+0&&"longjmp"!==d)throw d;Z(1,0)}}function ae(a,b,c,d,f){var g=F();try{return L.get(a)(b,c,d,f)}catch(k){J(g);if(k!==k+0&&"longjmp"!==k)throw k;Z(1,0)}}function ce(a,b,c,d,f,g,k,m,q){var p=F();try{return L.get(a)(b,c,d,f,g,k,m,q)}catch(r){J(p);if(r!==r+0&&"longjmp"!==r)throw r;Z(1,0)}}
function he(a,b,c,d){var f=F();try{L.get(a)(b,c,d)}catch(g){J(f);if(g!==g+0&&"longjmp"!==g)throw g;Z(1,0)}}function Xd(a){var b=F();try{return L.get(a)()}catch(c){J(b);if(c!==c+0&&"longjmp"!==c)throw c;Z(1,0)}}function je(a,b,c,d,f,g){var k=F();try{L.get(a)(b,c,d,f,g)}catch(m){J(k);if(m!==m+0&&"longjmp"!==m)throw m;Z(1,0)}}function $d(a,b,c,d){var f=F();try{return L.get(a)(b,c,d)}catch(g){J(f);if(g!==g+0&&"longjmp"!==g)throw g;Z(1,0)}}
function be(a,b,c,d,f,g){var k=F();try{return L.get(a)(b,c,d,f,g)}catch(m){J(k);if(m!==m+0&&"longjmp"!==m)throw m;Z(1,0)}}function le(a,b,c,d,f,g,k,m,q){var p=F();try{L.get(a)(b,c,d,f,g,k,m,q)}catch(r){J(p);if(r!==r+0&&"longjmp"!==r)throw r;Z(1,0)}}function ke(a,b,c,d,f,g,k){var m=F();try{L.get(a)(b,c,d,f,g,k)}catch(q){J(m);if(q!==q+0&&"longjmp"!==q)throw q;Z(1,0)}}function me(a,b,c,d,f,g,k,m,q,p){var r=F();try{pe(a,b,c,d,f,g,k,m,q,p)}catch(y){J(r);if(y!==y+0&&"longjmp"!==y)throw y;Z(1,0)}}
function de(a,b,c,d,f,g,k,m){var q=F();try{return qe(a,b,c,d,f,g,k,m)}catch(p){J(q);if(p!==p+0&&"longjmp"!==p)throw p;Z(1,0)}}function ee(a,b,c,d){var f=F();try{return re(a,b,c,d)}catch(g){J(f);if(g!==g+0&&"longjmp"!==g)throw g;Z(1,0)}}x.ccall=Ka;x.cwrap=function(a,b,c,d){c=c||[];var f=c.every(function(g){return"number"===g});return"string"!==b&&f&&!d?Ja(a):function(){return Ka(a,b,c,arguments,d)}};
x.setValue=function(a,b,c){c=c||"i8";"*"===c.charAt(c.length-1)&&(c="i32");switch(c){case "i1":e()[a>>0]=b;break;case "i8":e()[a>>0]=b;break;case "i16":ea()[a>>1]=b;break;case "i32":t()[a>>2]=b;break;case "i64":R=[b>>>0,(Q=b,1<=+Math.abs(Q)?0<Q?(Math.min(+Math.floor(Q/4294967296),4294967295)|0)>>>0:~~+Math.ceil((Q-+(~~Q>>>0))/4294967296)>>>0:0)];t()[a>>2]=R[0];t()[a+4>>2]=R[1];break;case "float":h.buffer!=l&&aa(h.buffer);Xa[a>>2]=b;break;case "double":ja()[a>>3]=b;break;default:E("invalid type for setValue: "+
c)}};x.writeAsciiToMemory=Va;x.FS=M;x.PThread=S;x.PThread=S;x.wasmMemory=h;x.ExitStatus=na;var se;function na(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}jb=function te(){se||ue();se||(jb=te)};
function ue(a){function b(){if(!se&&(se=!0,x.calledRun=!0,!Ia)){eb();C||fb(cb);la(x);if(x.onRuntimeInitialized)x.onRuntimeInitialized();if(ve){var c=a,d=x._emscripten_proxy_main;c=c||[];var f=c.length+1,g=La(4*(f+1));t()[g>>2]=Ua(ta);for(var k=1;k<f;k++)t()[(g>>2)+k]=Ua(c[k-1]);t()[(g>>2)+f]=0;d(f,g)}if(!C){if(x.postRun)for("function"==typeof x.postRun&&(x.postRun=[x.postRun]);x.postRun.length;)c=x.postRun.shift(),db.unshift(c);fb(db)}}}a=a||sa;if(!(0<hb))if(C)la(x),eb(),postMessage({cmd:"loaded"});
else{if(!C){if(x.preRun)for("function"==typeof x.preRun&&(x.preRun=[x.preRun]);x.preRun.length;)gb();fb(ab)}0<hb||(x.setStatus?(x.setStatus("Running..."),setTimeout(function(){setTimeout(function(){x.setStatus("")},1);b()},1)):b())}}x.run=ue;function oa(a,b){if(!b||!Hb()||0!==a){if(!b&&C)throw postMessage({cmd:"exitProcess",returnCode:a}),new na(a);if(!Hb()){S.rf();if(x.onExit)x.onExit(a);Ia=!0}ua(a,new na(a))}}if(x.preInit)for("function"==typeof x.preInit&&(x.preInit=[x.preInit]);0<x.preInit.length;)x.preInit.pop()();
var ve=!1;x.noInitialRun&&(ve=!1);C&&(noExitRuntime=!1,S.Re());ue();


  return createFFmpegCore.ready
}
);
})();
if (typeof exports === 'object' && typeof module === 'object')
  module.exports = createFFmpegCore;
else if (typeof define === 'function' && define['amd'])
  define([], function() { return createFFmpegCore; });
else if (typeof exports === 'object')
  exports["createFFmpegCore"] = createFFmpegCore;
