
var createFFmpegCore = (() => {
  var _scriptDir = typeof document !== 'undefined' && document.currentScript ? document.currentScript.src : undefined;
  if (typeof __filename !== 'undefined') _scriptDir = _scriptDir || __filename;
  return (
function(createFFmpegCore) {
  createFFmpegCore = createFFmpegCore || {};


function e(){h.buffer!=n&&t(h.buffer);return aa}function v(){h.buffer!=n&&t(h.buffer);return ba}function ca(){h.buffer!=n&&t(h.buffer);return da}function y(){h.buffer!=n&&t(h.buffer);return ea}function z(){h.buffer!=n&&t(h.buffer);return ha}function ia(){h.buffer!=n&&t(h.buffer);return ja}var A;A||(A=typeof createFFmpegCore !== 'undefined' ? createFFmpegCore : {});var ka,la;A.ready=new Promise(function(a,b){ka=a;la=b});A.quit=function(a){if(A.onExit)A.onExit(a);throw new ma(a);};na=D=function(){};
var oa=Object.assign({},A),pa=[],qa="./this.program",ra=(a,b)=>{throw b;},sa="object"==typeof window,ta="function"==typeof importScripts,E="object"==typeof process&&"object"==typeof process.versions&&"string"==typeof process.versions.node,F=A.ENVIRONMENT_IS_PTHREAD||!1,G="";function ua(a){return A.locateFile?A.locateFile(a,G):G+a}var va,wa,xa,fs,ya,za;
if(E){G=ta?require("path").dirname(G)+"/":__dirname+"/";za=()=>{ya||(fs=require("fs"),ya=require("path"))};va=function(b,c){za();b=ya.normalize(b);return fs.readFileSync(b,c?void 0:"utf8")};xa=b=>{b=va(b,!0);b.buffer||(b=new Uint8Array(b));return b};wa=(b,c,d)=>{za();b=ya.normalize(b);fs.readFile(b,function(f,g){f?d(f):c(g.buffer)})};1<process.argv.length&&(qa=process.argv[1].replace(/\\/g,"/"));pa=process.argv.slice(2);process.on("uncaughtException",function(b){if(!(b instanceof ma))throw b;});process.on("unhandledRejection",
function(b){throw b;});ra=(b,c)=>{if(noExitRuntime)throw process.exitCode=b,c;c instanceof ma||D("exiting due to exception: "+c);process.exit(b)};A.inspect=function(){return"[Emscripten Module object]"};let a;try{a=require("worker_threads")}catch(b){throw console.error('The "worker_threads" module is not supported in this node.js build - perhaps a newer version is needed?'),b;}global.Worker=a.Worker}else if(sa||ta)ta?G=self.location.href:"undefined"!=typeof document&&document.currentScript&&(G=document.currentScript.src),
_scriptDir&&(G=_scriptDir),0!==G.indexOf("blob:")?G=G.substr(0,G.replace(/[?#].*/,"").lastIndexOf("/")+1):G="",E||(va=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},ta&&(xa=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),wa=(a,b,c)=>{var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=()=>{200==d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=
c;d.send(null)});E&&"undefined"==typeof performance&&(global.performance=require("perf_hooks").performance);var Aa=console.log.bind(console),Ba=console.warn.bind(console);E&&(za(),Aa=a=>fs.writeSync(1,a+"\n"),Ba=a=>fs.writeSync(2,a+"\n"));var na=A.print||Aa,D=A.printErr||Ba;Object.assign(A,oa);oa=null;A.arguments&&(pa=A.arguments);A.thisProgram&&(qa=A.thisProgram);A.quit&&(ra=A.quit);var Ca;A.wasmBinary&&(Ca=A.wasmBinary);var noExitRuntime=A.noExitRuntime||!0;"object"!=typeof WebAssembly&&H("no native wasm support detected");
var h,Da,Ea=!1,Fa="undefined"!=typeof TextDecoder?new TextDecoder("utf8"):void 0;
function Ga(a,b,c){var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.buffer&&Fa)return Fa.decode(a.buffer instanceof SharedArrayBuffer?a.slice(b,c):a.subarray(b,c));for(d="";b<c;){var f=a[b++];if(f&128){var g=a[b++]&63;if(192==(f&224))d+=String.fromCharCode((f&31)<<6|g);else{var k=a[b++]&63;f=224==(f&240)?(f&15)<<12|g<<6|k:(f&7)<<18|g<<12|k<<6|a[b++]&63;65536>f?d+=String.fromCharCode(f):(f-=65536,d+=String.fromCharCode(55296|f>>10,56320|f&1023))}}else d+=String.fromCharCode(f)}return d}
function I(a,b){return a?Ga(v(),a,b):""}function Ha(a,b,c,d){if(!(0<d))return 0;var f=c;d=c+d-1;for(var g=0;g<a.length;++g){var k=a.charCodeAt(g);if(55296<=k&&57343>=k){var l=a.charCodeAt(++g);k=65536+((k&1023)<<10)|l&1023}if(127>=k){if(c>=d)break;b[c++]=k}else{if(2047>=k){if(c+1>=d)break;b[c++]=192|k>>6}else{if(65535>=k){if(c+2>=d)break;b[c++]=224|k>>12}else{if(c+3>=d)break;b[c++]=240|k>>18;b[c++]=128|k>>12&63}b[c++]=128|k>>6&63}b[c++]=128|k&63}}b[c]=0;return c-f}
function Ia(a,b,c){return Ha(a,v(),b,c)}function Ja(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b}var n,aa,ba,da,Ka,ea,ha,La,ja;F&&(n=A.buffer);function t(a){n=a;A.HEAP8=aa=new Int8Array(a);A.HEAP16=da=new Int16Array(a);A.HEAP32=ea=new Int32Array(a);A.HEAPU8=ba=new Uint8Array(a);A.HEAPU16=Ka=new Uint16Array(a);A.HEAPU32=ha=new Uint32Array(a);A.HEAPF32=La=new Float32Array(a);A.HEAPF64=ja=new Float64Array(a)}
var Oa=A.INITIAL_MEMORY||536870912;
if(F)h=A.wasmMemory,n=A.buffer;else if(A.wasmMemory)h=A.wasmMemory;else if(h=new WebAssembly.Memory({initial:Oa/65536,maximum:32752,shared:!0}),!(h.buffer instanceof SharedArrayBuffer))throw D("requested a shared WebAssembly.Memory but the returned buffer is not a SharedArrayBuffer, indicating that while the browser has SharedArrayBuffer it does not have WebAssembly threads support - you may need to set a flag"),E&&console.log("(on node you may need: --experimental-wasm-threads --experimental-wasm-bulk-memory and also use a recent version)"),Error("bad memory");
h&&(n=h.buffer);Oa=n.byteLength;t(n);var Pa,Qa=[],Ra=[],Sa=[],Ta=[];function Ua(){F||(A.noFSInit||J.Sb.Fc||J.Sb(),J.ld=!1,L.root=J.jb(L,{},null),Va(Ra))}function Wa(){var a=A.preRun.shift();Qa.unshift(a)}var Xa=0,Ya=null,Za=null;function $a(){Xa++;A.monitorRunDependencies&&A.monitorRunDependencies(Xa)}function ab(){Xa--;A.monitorRunDependencies&&A.monitorRunDependencies(Xa);if(0==Xa&&(null!==Ya&&(clearInterval(Ya),Ya=null),Za)){var a=Za;Za=null;a()}}
function H(a){if(F)postMessage({cmd:"onAbort",arg:a});else if(A.onAbort)A.onAbort(a);a="Aborted("+a+")";D(a);Ea=!0;a=new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");la(a);throw a;}function bb(){return M.startsWith("data:application/octet-stream;base64,")}var M;M="ffmpeg-core.wasm";bb()||(M=ua(M));function cb(){var a=M;try{if(a==M&&Ca)return new Uint8Array(Ca);if(xa)return xa(a);throw"both async and sync fetching of the wasm failed";}catch(b){H(b)}}
function db(){if(!Ca&&(sa||ta)){if("function"==typeof fetch&&!M.startsWith("file://"))return fetch(M,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+M+"'";return a.arrayBuffer()}).catch(function(){return cb()});if(wa)return new Promise(function(a,b){wa(M,function(c){a(new Uint8Array(c))},b)})}return Promise.resolve().then(function(){return cb()})}var N,O,eb={};
function ma(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}function gb(a){var b=P.Eb[a];delete P.Eb[a];b.terminate();hb(a);P.Yb.splice(P.Yb.indexOf(b),1);b.Db=0}function ib(a){P.Eb[a].postMessage({cmd:"cancel"})}function jb(a){(a=P.Eb[a])||H();P.qd(a)}
function kb(a){var b=P.Qd();if(!b)return 6;P.Yb.push(b);P.Eb[a.Db]=b;b.Db=a.Db;var c={cmd:"run",start_routine:a.he,arg:a.Bd,pthread_ptr:a.Db};b.ic=()=>{c.time=performance.now();b.postMessage(c,a.oe)};b.loaded&&(b.ic(),delete b.ic);return 0}
var lb=(a,b)=>{for(var c=0,d=a.length-1;0<=d;d--){var f=a[d];"."===f?a.splice(d,1):".."===f?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a},Q=a=>{var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=lb(a.split("/").filter(d=>!!d),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a},mb=a=>{var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&(b=b.substr(0,b.length-1));return a+b},nb=a=>{if("/"===
a)return"/";a=Q(a);a=a.replace(/\/$/,"");var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)},ob=(a,b)=>Q(a+"/"+b);function pb(){if("object"==typeof crypto&&"function"==typeof crypto.getRandomValues){var a=new Uint8Array(1);return()=>{crypto.getRandomValues(a);return a[0]}}if(E)try{var b=require("crypto");return()=>b.randomBytes(1)[0]}catch(c){}return()=>H("randomDevice")}
function qb(){for(var a="",b=!1,c=arguments.length-1;-1<=c&&!b;c--){b=0<=c?arguments[c]:J.cwd();if("string"!=typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b="/"===b.charAt(0)}a=lb(a.split("/").filter(d=>!!d),!b).join("/");return(b?"/":"")+a||"."}
var rb=(a,b)=>{function c(k){for(var l=0;l<k.length&&""===k[l];l++);for(var p=k.length-1;0<=p&&""===k[p];p--);return l>p?[]:k.slice(l,p-l+1)}a=qb(a).substr(1);b=qb(b).substr(1);a=c(a.split("/"));b=c(b.split("/"));for(var d=Math.min(a.length,b.length),f=d,g=0;g<d;g++)if(a[g]!==b[g]){f=g;break}d=[];for(g=f;g<a.length;g++)d.push("..");d=d.concat(b.slice(f));return d.join("/")};function sb(a,b){var c=Array(Ja(a)+1);a=Ha(a,c,0,c.length);b&&(c.length=a);return c}var tb=[];
function ub(a,b){tb[a]={input:[],output:[],Vb:b};J.Pc(a,vb)}
var vb={open:function(a){var b=tb[a.node.rdev];if(!b)throw new J.cb(43);a.tty=b;a.seekable=!1},close:function(a){a.tty.Vb.fsync(a.tty)},fsync:function(a){a.tty.Vb.fsync(a.tty)},read:function(a,b,c,d){if(!a.tty||!a.tty.Vb.gd)throw new J.cb(60);for(var f=0,g=0;g<d;g++){try{var k=a.tty.Vb.gd(a.tty)}catch(l){throw new J.cb(29);}if(void 0===k&&0===f)throw new J.cb(6);if(null===k||void 0===k)break;f++;b[c+g]=k}f&&(a.node.timestamp=Date.now());return f},write:function(a,b,c,d){if(!a.tty||!a.tty.Vb.Lc)throw new J.cb(60);
try{for(var f=0;f<d;f++)a.tty.Vb.Lc(a.tty,b[c+f])}catch(g){throw new J.cb(29);}d&&(a.node.timestamp=Date.now());return f}},wb={gd:function(a){if(!a.input.length){var b=null;if(E){var c=Buffer.alloc(256),d=0;try{d=fs.readSync(process.stdin.fd,c,0,256,-1)}catch(f){if(f.toString().includes("EOF"))d=0;else throw f;}0<d?b=c.slice(0,d).toString("utf-8"):b=null}else"undefined"!=typeof window&&"function"==typeof window.prompt?(b=window.prompt("Input: "),null!==b&&(b+="\n")):"function"==typeof readline&&(b=
readline(),null!==b&&(b+="\n"));if(!b)return null;a.input=sb(b,!0)}return a.input.shift()},Lc:function(a,b){null===b||10===b?(na(Ga(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},fsync:function(a){a.output&&0<a.output.length&&(na(Ga(a.output,0)),a.output=[])}},xb={Lc:function(a,b){null===b||10===b?(D(Ga(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},fsync:function(a){a.output&&0<a.output.length&&(D(Ga(a.output,0)),a.output=[])}};
function yb(a){a=65536*Math.ceil(a/65536);var b=zb(65536,a);if(!b)return 0;v().fill(0,b,b+a);return b}
var R={Ab:null,jb:function(){return R.createNode(null,"/",16895,0)},createNode:function(a,b,c,d){if(J.Ud(c)||J.isFIFO(c))throw new J.cb(63);R.Ab||(R.Ab={dir:{node:{wb:R.eb.wb,ob:R.eb.ob,lookup:R.eb.lookup,yb:R.eb.yb,rename:R.eb.rename,unlink:R.eb.unlink,rmdir:R.eb.rmdir,readdir:R.eb.readdir,symlink:R.eb.symlink},stream:{qb:R.fb.qb}},file:{node:{wb:R.eb.wb,ob:R.eb.ob},stream:{qb:R.fb.qb,read:R.fb.read,write:R.fb.write,bc:R.fb.bc,Mb:R.fb.Mb,Ub:R.fb.Ub}},link:{node:{wb:R.eb.wb,ob:R.eb.ob,readlink:R.eb.readlink},
stream:{}},Xc:{node:{wb:R.eb.wb,ob:R.eb.ob},stream:J.Ed}});c=J.createNode(a,b,c,d);J.mb(c.mode)?(c.eb=R.Ab.dir.node,c.fb=R.Ab.dir.stream,c.gb={}):J.isFile(c.mode)?(c.eb=R.Ab.file.node,c.fb=R.Ab.file.stream,c.kb=0,c.gb=null):J.Jb(c.mode)?(c.eb=R.Ab.link.node,c.fb=R.Ab.link.stream):J.cc(c.mode)&&(c.eb=R.Ab.Xc.node,c.fb=R.Ab.Xc.stream);c.timestamp=Date.now();a&&(a.gb[b]=c,a.timestamp=c.timestamp);return c},xe:function(a){return a.gb?a.gb.subarray?a.gb.subarray(0,a.kb):new Uint8Array(a.gb):new Uint8Array(0)},
bd:function(a,b){var c=a.gb?a.gb.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)>>>0),0!=c&&(b=Math.max(b,256)),c=a.gb,a.gb=new Uint8Array(b),0<a.kb&&a.gb.set(c.subarray(0,a.kb),0))},fe:function(a,b){if(a.kb!=b)if(0==b)a.gb=null,a.kb=0;else{var c=a.gb;a.gb=new Uint8Array(b);c&&a.gb.set(c.subarray(0,Math.min(b,a.kb)));a.kb=b}},eb:{wb:function(a){var b={};b.dev=J.cc(a.mode)?a.id:1;b.ino=a.id;b.mode=a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=a.rdev;J.mb(a.mode)?b.size=4096:J.isFile(a.mode)?b.size=a.kb:
J.Jb(a.mode)?b.size=a.link.length:b.size=0;b.atime=new Date(a.timestamp);b.mtime=new Date(a.timestamp);b.ctime=new Date(a.timestamp);b.Vc=4096;b.blocks=Math.ceil(b.size/b.Vc);return b},ob:function(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);void 0!==b.size&&R.fe(a,b.size)},lookup:function(){throw J.Cc[44];},yb:function(a,b,c,d){return R.createNode(a,b,c,d)},rename:function(a,b,c){if(J.mb(a.mode)){try{var d=J.xb(b,c)}catch(g){}if(d)for(var f in d.gb)throw new J.cb(55);
}delete a.parent.gb[a.name];a.parent.timestamp=Date.now();a.name=c;b.gb[c]=a;b.timestamp=a.parent.timestamp;a.parent=b},unlink:function(a,b){delete a.gb[b];a.timestamp=Date.now()},rmdir:function(a,b){var c=J.xb(a,b),d;for(d in c.gb)throw new J.cb(55);delete a.gb[b];a.timestamp=Date.now()},readdir:function(a){var b=[".",".."],c;for(c in a.gb)a.gb.hasOwnProperty(c)&&b.push(c);return b},symlink:function(a,b,c){a=R.createNode(a,b,41471,0);a.link=c;return a},readlink:function(a){if(!J.Jb(a.mode))throw new J.cb(28);
return a.link}},fb:{read:function(a,b,c,d,f){var g=a.node.gb;if(f>=a.node.kb)return 0;a=Math.min(a.node.kb-f,d);if(8<a&&g.subarray)b.set(g.subarray(f,f+a),c);else for(d=0;d<a;d++)b[c+d]=g[f+d];return a},write:function(a,b,c,d,f,g){b.buffer===e().buffer&&(g=!1);if(!d)return 0;a=a.node;a.timestamp=Date.now();if(b.subarray&&(!a.gb||a.gb.subarray)){if(g)return a.gb=b.subarray(c,c+d),a.kb=d;if(0===a.kb&&0===f)return a.gb=b.slice(c,c+d),a.kb=d;if(f+d<=a.kb)return a.gb.set(b.subarray(c,c+d),f),d}R.bd(a,
f+d);if(a.gb.subarray&&b.subarray)a.gb.set(b.subarray(c,c+d),f);else for(g=0;g<d;g++)a.gb[f+g]=b[c+g];a.kb=Math.max(a.kb,f+d);return d},qb:function(a,b,c){1===c?b+=a.position:2===c&&J.isFile(a.node.mode)&&(b+=a.node.kb);if(0>b)throw new J.cb(28);return b},bc:function(a,b,c){R.bd(a.node,b+c);a.node.kb=Math.max(a.node.kb,b+c)},Mb:function(a,b,c,d,f){if(!J.isFile(a.node.mode))throw new J.cb(43);a=a.node.gb;if(f&2||a.buffer!==n){if(0<c||c+b<a.length)a.subarray?a=a.subarray(c,c+b):a=Array.prototype.slice.call(a,
c,c+b);c=!0;b=yb(b);if(!b)throw new J.cb(48);e().set(a,b)}else c=!1,b=a.byteOffset;return{nd:b,Uc:c}},Ub:function(a,b,c,d,f){if(!J.isFile(a.node.mode))throw new J.cb(43);if(f&2)return 0;R.fb.write(a,b,0,d,c,!1);return 0}}};function Ab(a,b,c){var d="al "+a;wa(a,f=>{f||H('Loading data file "'+a+'" failed (no arrayBuffer).');b(new Uint8Array(f));d&&ab()},()=>{if(c)c();else throw'Loading data file "'+a+'" failed.';});d&&$a()}
var T={vc:16895,ac:33279,Nc:null,jb:function(a){function b(g){g=g.split("/");for(var k=d,l=0;l<g.length-1;l++){var p=g.slice(0,l+1).join("/");f[p]||(f[p]=T.createNode(k,g[l],T.vc,0));k=f[p]}return k}function c(g){g=g.split("/");return g[g.length-1]}ta||H();T.Nc||(T.Nc=new FileReaderSync);var d=T.createNode(null,"/",T.vc,0),f={};Array.prototype.forEach.call(a.Kc.files||[],function(g){T.createNode(b(g.name),c(g.name),T.ac,0,g,g.lastModifiedDate)});(a.Kc.blobs||[]).forEach(function(g){T.createNode(b(g.name),
c(g.name),T.ac,0,g.data)});(a.Kc.packages||[]).forEach(function(g){g.metadata.files.forEach(function(k){var l=k.filename.substr(1);T.createNode(b(l),c(l),T.ac,0,g.blob.slice(k.start,k.end))})});return d},createNode:function(a,b,c,d,f,g){d=J.createNode(a,b,c);d.mode=c;d.eb=T.eb;d.fb=T.fb;d.timestamp=(g||new Date).getTime();T.ac!==T.vc||H();c===T.ac?(d.size=f.size,d.gb=f):(d.size=4096,d.gb={});a&&(a.gb[b]=d);return d},eb:{wb:function(a){return{dev:1,ino:a.id,mode:a.mode,nlink:1,uid:0,gid:0,rdev:void 0,
size:a.size,atime:new Date(a.timestamp),mtime:new Date(a.timestamp),ctime:new Date(a.timestamp),Vc:4096,blocks:Math.ceil(a.size/4096)}},ob:function(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp)},lookup:function(){throw new J.cb(44);},yb:function(){throw new J.cb(63);},rename:function(){throw new J.cb(63);},unlink:function(){throw new J.cb(63);},rmdir:function(){throw new J.cb(63);},readdir:function(a){var b=[".",".."],c;for(c in a.gb)a.gb.hasOwnProperty(c)&&
b.push(c);return b},symlink:function(){throw new J.cb(63);},readlink:function(){throw new J.cb(63);}},fb:{read:function(a,b,c,d,f){if(f>=a.node.size)return 0;a=a.node.gb.slice(f,f+d);d=T.Nc.readAsArrayBuffer(a);b.set(new Uint8Array(d),c);return a.size},write:function(){throw new J.cb(29);},qb:function(a,b,c){1===c?b+=a.position:2===c&&J.isFile(a.node.mode)&&(b+=a.node.size);if(0>b)throw new J.cb(28);return b}}},J={root:null,fc:[],$c:{},streams:[],$d:1,zb:null,Zc:"/",Fc:!1,ld:!0,cb:null,Cc:{},cd:null,
sc:0,ib:(a,b={})=>{a=qb(J.cwd(),a);if(!a)return{path:"",node:null};b=Object.assign({Ac:!0,Oc:0},b);if(8<b.Oc)throw new J.cb(32);a=lb(a.split("/").filter(k=>!!k),!1);for(var c=J.root,d="/",f=0;f<a.length;f++){var g=f===a.length-1;if(g&&b.parent)break;c=J.xb(c,a[f]);d=Q(d+"/"+a[f]);J.Kb(c)&&(!g||g&&b.Ac)&&(c=c.ec.root);if(!g||b.ub)for(g=0;J.Jb(c.mode);)if(c=J.readlink(d),d=qb(mb(d),c),c=J.ib(d,{Oc:b.Oc+1}).node,40<g++)throw new J.cb(32);}return{path:d,node:c}},Gb:a=>{for(var b;;){if(J.nc(a))return a=
a.jb.md,b?"/"!==a[a.length-1]?a+"/"+b:a+b:a;b=b?a.name+"/"+b:a.name;a=a.parent}},Ec:(a,b)=>{for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%J.zb.length},jd:a=>{var b=J.Ec(a.parent.id,a.name);a.Nb=J.zb[b];J.zb[b]=a},kd:a=>{var b=J.Ec(a.parent.id,a.name);if(J.zb[b]===a)J.zb[b]=a.Nb;else for(b=J.zb[b];b;){if(b.Nb===a){b.Nb=a.Nb;break}b=b.Nb}},xb:(a,b)=>{var c=J.Xd(a);if(c)throw new J.cb(c,a);for(c=J.zb[J.Ec(a.id,b)];c;c=c.Nb){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return J.lookup(a,
b)},createNode:(a,b,c,d)=>{a=new J.wd(a,b,c,d);J.jd(a);return a},zc:a=>{J.kd(a)},nc:a=>a===a.parent,Kb:a=>!!a.ec,isFile:a=>32768===(a&61440),mb:a=>16384===(a&61440),Jb:a=>40960===(a&61440),cc:a=>8192===(a&61440),Ud:a=>24576===(a&61440),isFIFO:a=>4096===(a&61440),isSocket:a=>49152===(a&49152),Od:{r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090},Zd:a=>{var b=J.Od[a];if("undefined"==typeof b)throw Error("Unknown file open mode: "+a);return b},dd:a=>{var b=["r","w","rw"][a&3];a&512&&(b+="w");return b},Hb:(a,
b)=>{if(J.ld)return 0;if(!b.includes("r")||a.mode&292){if(b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73))return 2}else return 2;return 0},Xd:a=>{var b=J.Hb(a,"x");return b?b:a.eb.lookup?0:2},Jc:(a,b)=>{try{return J.xb(a,b),20}catch(c){}return J.Hb(a,"wx")},oc:(a,b,c)=>{try{var d=J.xb(a,b)}catch(f){return f.hb}if(a=J.Hb(a,"wx"))return a;if(c){if(!J.mb(d.mode))return 54;if(J.nc(d)||J.Gb(d)===J.cwd())return 10}else if(J.mb(d.mode))return 31;return 0},Yd:(a,b)=>a?J.Jb(a.mode)?32:J.mb(a.mode)&&
("r"!==J.dd(b)||b&512)?31:J.Hb(a,J.dd(b)):44,xd:4096,ae:(a=0,b=J.xd)=>{for(;a<=b;a++)if(!J.streams[a])return a;throw new J.cb(33);},vb:a=>J.streams[a],yc:(a,b,c)=>{J.jc||(J.jc=function(){this.Cb={}},J.jc.prototype={},Object.defineProperties(J.jc.prototype,{object:{get:function(){return this.node},set:function(d){this.node=d}},flags:{get:function(){return this.Cb.flags},set:function(d){this.Cb.flags=d}},position:{get:function(){return this.Cb.position},set:function(d){this.Cb.position=d}}}));a=Object.assign(new J.jc,
a);b=J.ae(b,c);a.fd=b;return J.streams[b]=a},Fd:a=>{J.streams[a]=null},Ed:{open:a=>{a.fb=J.Pd(a.node.rdev).fb;a.fb.open&&a.fb.open(a)},qb:()=>{throw new J.cb(70);}},Ic:a=>a>>8,Ce:a=>a&255,Lb:(a,b)=>a<<8|b,Pc:(a,b)=>{J.$c[a]={fb:b}},Pd:a=>J.$c[a],ed:a=>{var b=[];for(a=[a];a.length;){var c=a.pop();b.push(c);a.push.apply(a,c.fc)}return b},td:(a,b)=>{function c(k){J.sc--;return b(k)}function d(k){if(k){if(!d.Nd)return d.Nd=!0,c(k)}else++g>=f.length&&c(null)}"function"==typeof a&&(b=a,a=!1);J.sc++;1<J.sc&&
D("warning: "+J.sc+" FS.syncfs operations in flight at once, probably just doing extra work");var f=J.ed(J.root.jb),g=0;f.forEach(k=>{if(!k.type.td)return d(null);k.type.td(k,a,d)})},jb:(a,b,c)=>{var d="/"===c,f=!c;if(d&&J.root)throw new J.cb(10);if(!d&&!f){var g=J.ib(c,{Ac:!1});c=g.path;g=g.node;if(J.Kb(g))throw new J.cb(10);if(!J.mb(g.mode))throw new J.cb(54);}b={type:a,Kc:b,md:c,fc:[]};a=a.jb(b);a.jb=b;b.root=a;d?J.root=a:g&&(g.ec=b,g.jb&&g.jb.fc.push(b));return a},qe:a=>{a=J.ib(a,{Ac:!1});if(!J.Kb(a.node))throw new J.cb(28);
a=a.node;var b=a.ec,c=J.ed(b);Object.keys(J.zb).forEach(d=>{for(d=J.zb[d];d;){var f=d.Nb;c.includes(d.jb)&&J.zc(d);d=f}});a.ec=null;a.jb.fc.splice(a.jb.fc.indexOf(b),1)},lookup:(a,b)=>a.eb.lookup(a,b),yb:(a,b,c)=>{var d=J.ib(a,{parent:!0}).node;a=nb(a);if(!a||"."===a||".."===a)throw new J.cb(28);var f=J.Jc(d,a);if(f)throw new J.cb(f);if(!d.eb.yb)throw new J.cb(63);return d.eb.yb(d,a,b,c)},create:(a,b)=>J.yb(a,(void 0!==b?b:438)&4095|32768,0),mkdir:(a,b)=>J.yb(a,(void 0!==b?b:511)&1023|16384,0),De:(a,
b)=>{a=a.split("/");for(var c="",d=0;d<a.length;++d)if(a[d]){c+="/"+a[d];try{J.mkdir(c,b)}catch(f){if(20!=f.hb)throw f;}}},pc:(a,b,c)=>{"undefined"==typeof c&&(c=b,b=438);return J.yb(a,b|8192,c)},symlink:(a,b)=>{if(!qb(a))throw new J.cb(44);var c=J.ib(b,{parent:!0}).node;if(!c)throw new J.cb(44);b=nb(b);var d=J.Jc(c,b);if(d)throw new J.cb(d);if(!c.eb.symlink)throw new J.cb(63);return c.eb.symlink(c,b,a)},rename:(a,b)=>{var c=mb(a),d=mb(b),f=nb(a),g=nb(b);var k=J.ib(a,{parent:!0});var l=k.node;k=J.ib(b,
{parent:!0});k=k.node;if(!l||!k)throw new J.cb(44);if(l.jb!==k.jb)throw new J.cb(75);var p=J.xb(l,f);a=rb(a,d);if("."!==a.charAt(0))throw new J.cb(28);a=rb(b,c);if("."!==a.charAt(0))throw new J.cb(55);try{var r=J.xb(k,g)}catch(q){}if(p!==r){b=J.mb(p.mode);if(f=J.oc(l,f,b))throw new J.cb(f);if(f=r?J.oc(k,g,b):J.Jc(k,g))throw new J.cb(f);if(!l.eb.rename)throw new J.cb(63);if(J.Kb(p)||r&&J.Kb(r))throw new J.cb(10);if(k!==l&&(f=J.Hb(l,"w")))throw new J.cb(f);J.kd(p);try{l.eb.rename(p,k,g)}catch(q){throw q;
}finally{J.jd(p)}}},rmdir:a=>{var b=J.ib(a,{parent:!0}).node;a=nb(a);var c=J.xb(b,a),d=J.oc(b,a,!0);if(d)throw new J.cb(d);if(!b.eb.rmdir)throw new J.cb(63);if(J.Kb(c))throw new J.cb(10);b.eb.rmdir(b,a);J.zc(c)},readdir:a=>{a=J.ib(a,{ub:!0}).node;if(!a.eb.readdir)throw new J.cb(54);return a.eb.readdir(a)},unlink:a=>{var b=J.ib(a,{parent:!0}).node;if(!b)throw new J.cb(44);a=nb(a);var c=J.xb(b,a),d=J.oc(b,a,!1);if(d)throw new J.cb(d);if(!b.eb.unlink)throw new J.cb(63);if(J.Kb(c))throw new J.cb(10);
b.eb.unlink(b,a);J.zc(c)},readlink:a=>{a=J.ib(a).node;if(!a)throw new J.cb(44);if(!a.eb.readlink)throw new J.cb(28);return qb(J.Gb(a.parent),a.eb.readlink(a))},stat:(a,b)=>{a=J.ib(a,{ub:!b}).node;if(!a)throw new J.cb(44);if(!a.eb.wb)throw new J.cb(63);return a.eb.wb(a)},lstat:a=>J.stat(a,!0),chmod:(a,b,c)=>{a="string"==typeof a?J.ib(a,{ub:!c}).node:a;if(!a.eb.ob)throw new J.cb(63);a.eb.ob(a,{mode:b&4095|a.mode&-4096,timestamp:Date.now()})},lchmod:(a,b)=>{J.chmod(a,b,!0)},fchmod:(a,b)=>{a=J.vb(a);
if(!a)throw new J.cb(8);J.chmod(a.node,b)},chown:(a,b,c,d)=>{a="string"==typeof a?J.ib(a,{ub:!d}).node:a;if(!a.eb.ob)throw new J.cb(63);a.eb.ob(a,{timestamp:Date.now()})},lchown:(a,b,c)=>{J.chown(a,b,c,!0)},fchown:(a,b,c)=>{a=J.vb(a);if(!a)throw new J.cb(8);J.chown(a.node,b,c)},truncate:(a,b)=>{if(0>b)throw new J.cb(28);a="string"==typeof a?J.ib(a,{ub:!0}).node:a;if(!a.eb.ob)throw new J.cb(63);if(J.mb(a.mode))throw new J.cb(31);if(!J.isFile(a.mode))throw new J.cb(28);var c=J.Hb(a,"w");if(c)throw new J.cb(c);
a.eb.ob(a,{size:b,timestamp:Date.now()})},we:(a,b)=>{a=J.vb(a);if(!a)throw new J.cb(8);if(0===(a.flags&2097155))throw new J.cb(28);J.truncate(a.node,b)},Je:(a,b,c)=>{a=J.ib(a,{ub:!0}).node;a.eb.ob(a,{timestamp:Math.max(b,c)})},open:(a,b,c)=>{if(""===a)throw new J.cb(44);b="string"==typeof b?J.Zd(b):b;c=b&64?("undefined"==typeof c?438:c)&4095|32768:0;if("object"==typeof a)var d=a;else{a=Q(a);try{d=J.ib(a,{ub:!(b&131072)}).node}catch(g){}}var f=!1;if(b&64)if(d){if(b&128)throw new J.cb(20);}else d=J.yb(a,
c,0),f=!0;if(!d)throw new J.cb(44);J.cc(d.mode)&&(b&=-513);if(b&65536&&!J.mb(d.mode))throw new J.cb(54);if(!f&&(c=J.Yd(d,b)))throw new J.cb(c);b&512&&!f&&J.truncate(d,0);b&=-131713;d=J.yc({node:d,path:J.Gb(d),flags:b,seekable:!0,position:0,fb:d.fb,pe:[],error:!1});d.fb.open&&d.fb.open(d);!A.logReadFiles||b&1||(J.Mc||(J.Mc={}),a in J.Mc||(J.Mc[a]=1));return d},close:a=>{if(J.dc(a))throw new J.cb(8);a.Ib&&(a.Ib=null);try{a.fb.close&&a.fb.close(a)}catch(b){throw b;}finally{J.Fd(a.fd)}a.fd=null},dc:a=>
null===a.fd,qb:(a,b,c)=>{if(J.dc(a))throw new J.cb(8);if(!a.seekable||!a.fb.qb)throw new J.cb(70);if(0!=c&&1!=c&&2!=c)throw new J.cb(28);a.position=a.fb.qb(a,b,c);a.pe=[];return a.position},read:(a,b,c,d,f)=>{if(0>d||0>f)throw new J.cb(28);if(J.dc(a))throw new J.cb(8);if(1===(a.flags&2097155))throw new J.cb(8);if(J.mb(a.node.mode))throw new J.cb(31);if(!a.fb.read)throw new J.cb(28);var g="undefined"!=typeof f;if(!g)f=a.position;else if(!a.seekable)throw new J.cb(70);b=a.fb.read(a,b,c,d,f);g||(a.position+=
b);return b},write:(a,b,c,d,f,g)=>{if(0>d||0>f)throw new J.cb(28);if(J.dc(a))throw new J.cb(8);if(0===(a.flags&2097155))throw new J.cb(8);if(J.mb(a.node.mode))throw new J.cb(31);if(!a.fb.write)throw new J.cb(28);a.seekable&&a.flags&1024&&J.qb(a,0,2);var k="undefined"!=typeof f;if(!k)f=a.position;else if(!a.seekable)throw new J.cb(70);b=a.fb.write(a,b,c,d,f,g);k||(a.position+=b);return b},bc:(a,b,c)=>{if(J.dc(a))throw new J.cb(8);if(0>b||0>=c)throw new J.cb(28);if(0===(a.flags&2097155))throw new J.cb(8);
if(!J.isFile(a.node.mode)&&!J.mb(a.node.mode))throw new J.cb(43);if(!a.fb.bc)throw new J.cb(138);a.fb.bc(a,b,c)},Mb:(a,b,c,d,f)=>{if(0!==(d&2)&&0===(f&2)&&2!==(a.flags&2097155))throw new J.cb(2);if(1===(a.flags&2097155))throw new J.cb(2);if(!a.fb.Mb)throw new J.cb(43);return a.fb.Mb(a,b,c,d,f)},Ub:(a,b,c,d,f)=>a&&a.fb.Ub?a.fb.Ub(a,b,c,d,f):0,Ee:()=>0,Tb:(a,b,c)=>{if(!a.fb.Tb)throw new J.cb(59);return a.fb.Tb(a,b,c)},readFile:(a,b={})=>{b.flags=b.flags||0;b.encoding=b.encoding||"binary";if("utf8"!==
b.encoding&&"binary"!==b.encoding)throw Error('Invalid encoding type "'+b.encoding+'"');var c,d=J.open(a,b.flags);a=J.stat(a).size;var f=new Uint8Array(a);J.read(d,f,0,a,0);"utf8"===b.encoding?c=Ga(f,0):"binary"===b.encoding&&(c=f);J.close(d);return c},writeFile:(a,b,c={})=>{c.flags=c.flags||577;a=J.open(a,c.flags,c.mode);if("string"==typeof b){var d=new Uint8Array(Ja(b)+1);b=Ha(b,d,0,d.length);J.write(a,d,0,b,void 0,c.Dd)}else if(ArrayBuffer.isView(b))J.write(a,b,0,b.byteLength,void 0,c.Dd);else throw Error("Unsupported data type");
J.close(a)},cwd:()=>J.Zc,chdir:a=>{a=J.ib(a,{ub:!0});if(null===a.node)throw new J.cb(44);if(!J.mb(a.node.mode))throw new J.cb(54);var b=J.Hb(a.node,"x");if(b)throw new J.cb(b);J.Zc=a.path},Hd:()=>{J.mkdir("/tmp");J.mkdir("/home");J.mkdir("/home/web_user")},Gd:()=>{J.mkdir("/dev");J.Pc(J.Lb(1,3),{read:()=>0,write:(b,c,d,f)=>f});J.pc("/dev/null",J.Lb(1,3));ub(J.Lb(5,0),wb);ub(J.Lb(6,0),xb);J.pc("/dev/tty",J.Lb(5,0));J.pc("/dev/tty1",J.Lb(6,0));var a=pb();J.Fb("/dev","random",a);J.Fb("/dev","urandom",
a);J.mkdir("/dev/shm");J.mkdir("/dev/shm/tmp")},Jd:()=>{J.mkdir("/proc");var a=J.mkdir("/proc/self");J.mkdir("/proc/self/fd");J.jb({jb:()=>{var b=J.createNode(a,"fd",16895,73);b.eb={lookup:(c,d)=>{var f=J.vb(+d);if(!f)throw new J.cb(8);c={parent:null,jb:{md:"fake"},eb:{readlink:()=>f.path}};return c.parent=c}};return b}},{},"/proc/self/fd")},Kd:()=>{A.stdin?J.Fb("/dev","stdin",A.stdin):J.symlink("/dev/tty","/dev/stdin");A.stdout?J.Fb("/dev","stdout",null,A.stdout):J.symlink("/dev/tty","/dev/stdout");
A.stderr?J.Fb("/dev","stderr",null,A.stderr):J.symlink("/dev/tty1","/dev/stderr");J.open("/dev/stdin",0);J.open("/dev/stdout",1);J.open("/dev/stderr",1)},ad:()=>{J.cb||(J.cb=function(a,b){this.node=b;this.ge=function(c){this.hb=c};this.ge(a);this.message="FS error"},J.cb.prototype=Error(),J.cb.prototype.constructor=J.cb,[44].forEach(a=>{J.Cc[a]=new J.cb(a);J.Cc[a].stack="<generic error, no stack>"}))},ie:()=>{J.ad();J.zb=Array(4096);J.jb(R,{},"/");J.Hd();J.Gd();J.Jd();J.cd={MEMFS:R,WORKERFS:T}},Sb:(a,
b,c)=>{J.Sb.Fc=!0;J.ad();A.stdin=a||A.stdin;A.stdout=b||A.stdout;A.stderr=c||A.stderr;J.Kd()},Fe:()=>{J.Sb.Fc=!1;for(var a=0;a<J.streams.length;a++){var b=J.streams[a];b&&J.close(b)}},Dc:(a,b)=>{var c=0;a&&(c|=365);b&&(c|=146);return c},ve:(a,b)=>{a=J.xc(a,b);return a.exists?a.object:null},xc:(a,b)=>{try{var c=J.ib(a,{ub:!b});a=c.path}catch(f){}var d={nc:!1,exists:!1,error:0,name:null,path:null,object:null,be:!1,de:null,ce:null};try{c=J.ib(a,{parent:!0}),d.be=!0,d.de=c.path,d.ce=c.node,d.name=nb(a),
c=J.ib(a,{ub:!b}),d.exists=!0,d.path=c.path,d.object=c.node,d.name=c.node.name,d.nc="/"===c.path}catch(f){d.error=f.hb}return d},te:(a,b)=>{a="string"==typeof a?a:J.Gb(a);for(b=b.split("/").reverse();b.length;){var c=b.pop();if(c){var d=Q(a+"/"+c);try{J.mkdir(d)}catch(f){}a=d}}return d},Id:(a,b,c,d,f)=>{a="string"==typeof a?a:J.Gb(a);b=Q(a+"/"+b);return J.create(b,J.Dc(d,f))},Yc:(a,b,c,d,f,g)=>{var k=b;a&&(a="string"==typeof a?a:J.Gb(a),k=b?Q(a+"/"+b):a);a=J.Dc(d,f);k=J.create(k,a);if(c){if("string"==
typeof c){b=Array(c.length);d=0;for(f=c.length;d<f;++d)b[d]=c.charCodeAt(d);c=b}J.chmod(k,a|146);b=J.open(k,577);J.write(b,c,0,c.length,0,g);J.close(b);J.chmod(k,a)}return k},Fb:(a,b,c,d)=>{a=ob("string"==typeof a?a:J.Gb(a),b);b=J.Dc(!!c,!!d);J.Fb.Ic||(J.Fb.Ic=64);var f=J.Lb(J.Fb.Ic++,0);J.Pc(f,{open:g=>{g.seekable=!1},close:()=>{d&&d.buffer&&d.buffer.length&&d(10)},read:(g,k,l,p)=>{for(var r=0,q=0;q<p;q++){try{var w=c()}catch(B){throw new J.cb(29);}if(void 0===w&&0===r)throw new J.cb(6);if(null===
w||void 0===w)break;r++;k[l+q]=w}r&&(g.node.timestamp=Date.now());return r},write:(g,k,l,p)=>{for(var r=0;r<p;r++)try{d(k[l+r])}catch(q){throw new J.cb(29);}p&&(g.node.timestamp=Date.now());return r}});return J.pc(a,b,f)},Bc:a=>{if(a.Gc||a.Vd||a.link||a.gb)return!0;if("undefined"!=typeof XMLHttpRequest)throw Error("Lazy loading should have been performed (contents set) in createLazyFile, but it was not. Lazy loading only works in web workers. Use --embed-file or --preload-file in emcc on the main thread.");
if(va)try{a.gb=sb(va(a.url),!0),a.kb=a.gb.length}catch(b){throw new J.cb(29);}else throw Error("Cannot load without read() or XMLHttpRequest.");},se:(a,b,c,d,f)=>{function g(){this.Hc=!1;this.Cb=[]}function k(q,w,B,m,x){q=q.node.gb;if(x>=q.length)return 0;m=Math.min(q.length-x,m);if(q.slice)for(var u=0;u<m;u++)w[B+u]=q[x+u];else for(u=0;u<m;u++)w[B+u]=q.get(x+u);return m}g.prototype.get=function(q){if(!(q>this.length-1||0>q)){var w=q%this.chunkSize;return this.hd(q/this.chunkSize|0)[w]}};g.prototype.Md=
function(q){this.hd=q};g.prototype.Wc=function(){var q=new XMLHttpRequest;q.open("HEAD",c,!1);q.send(null);if(!(200<=q.status&&300>q.status||304===q.status))throw Error("Couldn't load "+c+". Status: "+q.status);var w=Number(q.getResponseHeader("Content-length")),B,m=(B=q.getResponseHeader("Accept-Ranges"))&&"bytes"===B;q=(B=q.getResponseHeader("Content-Encoding"))&&"gzip"===B;var x=1048576;m||(x=w);var u=this;u.Md(K=>{var S=K*x,fa=(K+1)*x-1;fa=Math.min(fa,w-1);if("undefined"==typeof u.Cb[K]){var U=
u.Cb;if(S>fa)throw Error("invalid range ("+S+", "+fa+") or no bytes requested!");if(fa>w-1)throw Error("only "+w+" bytes available! programmer error!");var C=new XMLHttpRequest;C.open("GET",c,!1);w!==x&&C.setRequestHeader("Range","bytes="+S+"-"+fa);C.responseType="arraybuffer";C.overrideMimeType&&C.overrideMimeType("text/plain; charset=x-user-defined");C.send(null);if(!(200<=C.status&&300>C.status||304===C.status))throw Error("Couldn't load "+c+". Status: "+C.status);S=void 0!==C.response?new Uint8Array(C.response||
[]):sb(C.responseText||"",!0);U[K]=S}if("undefined"==typeof u.Cb[K])throw Error("doXHR failed!");return u.Cb[K]});if(q||!w)x=w=1,x=w=this.hd(0).length,na("LazyFiles on gzip forces download of the whole file when length is accessed");this.zd=w;this.yd=x;this.Hc=!0};if("undefined"!=typeof XMLHttpRequest){if(!ta)throw"Cannot do synchronous binary XHRs outside webworkers in modern browsers. Use --embed-file or --preload-file in emcc";var l=new g;Object.defineProperties(l,{length:{get:function(){this.Hc||
this.Wc();return this.zd}},chunkSize:{get:function(){this.Hc||this.Wc();return this.yd}}});l={Gc:!1,gb:l}}else l={Gc:!1,url:c};var p=J.Id(a,b,l,d,f);l.gb?p.gb=l.gb:l.url&&(p.gb=null,p.url=l.url);Object.defineProperties(p,{kb:{get:function(){return this.gb.length}}});var r={};Object.keys(p.fb).forEach(q=>{var w=p.fb[q];r[q]=function(){J.Bc(p);return w.apply(null,arguments)}});r.read=(q,w,B,m,x)=>{J.Bc(p);return k(q,w,B,m,x)};r.Mb=(q,w,B)=>{J.Bc(p);var m=yb(w);if(!m)throw new J.cb(48);k(q,e(),m,w,B);
return{nd:m,Uc:!0}};p.fb=r;return p},ue:(a,b,c,d,f,g,k,l,p,r)=>{function q(B){function m(x){r&&r();l||J.Yc(a,b,x,d,f,p);g&&g();ab()}Bb.ze(B,w,m,()=>{k&&k();ab()})||m(B)}var w=b?qb(Q(a+"/"+b)):a;$a();"string"==typeof c?Ab(c,B=>q(B),k):q(c)},indexedDB:()=>window.indexedDB||window.mozIndexedDB||window.webkitIndexedDB||window.msIndexedDB,Rc:()=>"EM_FS_"+window.location.pathname,Sc:20,$b:"FILE_DATA",Ge:(a,b,c)=>{b=b||(()=>{});c=c||(()=>{});var d=J.indexedDB();try{var f=d.open(J.Rc(),J.Sc)}catch(g){return c(g)}f.onupgradeneeded=
()=>{na("creating db");f.result.createObjectStore(J.$b)};f.onsuccess=()=>{var g=f.result.transaction([J.$b],"readwrite"),k=g.objectStore(J.$b),l=0,p=0,r=a.length;a.forEach(q=>{q=k.put(J.xc(q).object.gb,q);q.onsuccess=()=>{l++;l+p==r&&(0==p?b():c())};q.onerror=()=>{p++;l+p==r&&(0==p?b():c())}});g.onerror=c};f.onerror=c},Be:(a,b,c)=>{b=b||(()=>{});c=c||(()=>{});var d=J.indexedDB();try{var f=d.open(J.Rc(),J.Sc)}catch(g){return c(g)}f.onupgradeneeded=c;f.onsuccess=()=>{var g=f.result;try{var k=g.transaction([J.$b],
"readonly")}catch(w){c(w);return}var l=k.objectStore(J.$b),p=0,r=0,q=a.length;a.forEach(w=>{var B=l.get(w);B.onsuccess=()=>{J.xc(w).exists&&J.unlink(w);J.Yc(mb(w),nb(w),B.result,!0,!0,!0);p++;p+r==q&&(0==r?b():c())};B.onerror=()=>{r++;p+r==q&&(0==r?b():c())}});k.onerror=c};f.onerror=c}};function Cb(a,b,c){if("/"===b.charAt(0))return b;if(-100===a)a=J.cwd();else{a=J.vb(a);if(!a)throw new J.cb(8);a=a.path}if(0==b.length){if(!c)throw new J.cb(44);return a}return Q(a+"/"+b)}
function Db(a,b,c){try{var d=a(b)}catch(f){if(f&&f.node&&Q(b)!==Q(J.Gb(f.node)))return-54;throw f;}y()[c>>2]=d.dev;y()[c+8>>2]=d.ino;y()[c+12>>2]=d.mode;y()[c+16>>2]=d.nlink;y()[c+20>>2]=d.uid;y()[c+24>>2]=d.gid;y()[c+28>>2]=d.rdev;O=[d.size>>>0,(N=d.size,1<=+Math.abs(N)?0<N?(Math.min(+Math.floor(N/4294967296),4294967295)|0)>>>0:~~+Math.ceil((N-+(~~N>>>0))/4294967296)>>>0:0)];y()[c+40>>2]=O[0];y()[c+44>>2]=O[1];y()[c+48>>2]=4096;y()[c+52>>2]=d.blocks;O=[Math.floor(d.atime.getTime()/1E3)>>>0,(N=Math.floor(d.atime.getTime()/
1E3),1<=+Math.abs(N)?0<N?(Math.min(+Math.floor(N/4294967296),4294967295)|0)>>>0:~~+Math.ceil((N-+(~~N>>>0))/4294967296)>>>0:0)];y()[c+56>>2]=O[0];y()[c+60>>2]=O[1];y()[c+64>>2]=0;O=[Math.floor(d.mtime.getTime()/1E3)>>>0,(N=Math.floor(d.mtime.getTime()/1E3),1<=+Math.abs(N)?0<N?(Math.min(+Math.floor(N/4294967296),4294967295)|0)>>>0:~~+Math.ceil((N-+(~~N>>>0))/4294967296)>>>0:0)];y()[c+72>>2]=O[0];y()[c+76>>2]=O[1];y()[c+80>>2]=0;O=[Math.floor(d.ctime.getTime()/1E3)>>>0,(N=Math.floor(d.ctime.getTime()/
1E3),1<=+Math.abs(N)?0<N?(Math.min(+Math.floor(N/4294967296),4294967295)|0)>>>0:~~+Math.ceil((N-+(~~N>>>0))/4294967296)>>>0:0)];y()[c+88>>2]=O[0];y()[c+92>>2]=O[1];y()[c+96>>2]=0;O=[d.ino>>>0,(N=d.ino,1<=+Math.abs(N)?0<N?(Math.min(+Math.floor(N/4294967296),4294967295)|0)>>>0:~~+Math.ceil((N-+(~~N>>>0))/4294967296)>>>0:0)];y()[c+104>>2]=O[0];y()[c+108>>2]=O[1];return 0}var Eb=void 0;function Fb(){Eb+=4;return y()[Eb-4>>2]}function Gb(a){a=J.vb(a);if(!a)throw new J.cb(8);return a}
function Hb(a){if(F)return V(1,1,a);if(!noExitRuntime){P.je();if(A.onExit)A.onExit(a);Ea=!0}ra(a,new ma(a))}function Ib(a,b){if(!b&&F)throw Jb(a),"unwind";Hb(a)}
var P={Rb:[],Yb:[],vd:[],Eb:{},Sb:function(){F&&P.Td()},Ae:function(){},Td:function(){P.receiveObjectTransfer=P.ee;P.threadInitTLS=P.ud;P.setExitStatus=P.sd;noExitRuntime=!1},sd:function(){},je:function(){for(var a of Object.values(P.Eb))P.qd(a);for(a of P.Rb)a.terminate();P.Rb=[]},qd:function(a){var b=a.Db;delete P.Eb[b];P.Rb.push(a);P.Yb.splice(P.Yb.indexOf(a),1);a.Db=0;hb(b)},ee:function(){},ud:function(){P.vd.forEach(a=>a())},Wd:function(a,b){a.onmessage=c=>{c=c.data;var d=c.cmd;a.Db&&(P.Ld=a.Db);
if(c.targetThread&&c.targetThread!=Kb()){var f=P.Eb[c.He];f?f.postMessage(c,c.transferList):D('Internal error! Worker sent a message "'+d+'" to target pthread '+c.targetThread+", but that thread no longer exists!")}else if("processProxyingQueue"===d)Lb(c.queue);else if("spawnThread"===d)kb(c);else if("cleanupThread"===d)jb(c.thread);else if("killThread"===d)gb(c.thread);else if("cancelThread"===d)ib(c.thread);else if("loaded"===d)a.loaded=!0,b&&b(a),a.ic&&(a.ic(),delete a.ic);else if("print"===d)na("Thread "+
c.threadId+": "+c.text);else if("printErr"===d)D("Thread "+c.threadId+": "+c.text);else if("alert"===d)alert("Thread "+c.threadId+": "+c.text);else if("setimmediate"===c.target)a.postMessage(c);else if("onAbort"===d){if(A.onAbort)A.onAbort(c.arg)}else d&&D("worker sent an unknown command "+d);P.Ld=void 0};a.onerror=c=>{D("worker sent an error! "+c.filename+":"+c.lineno+": "+c.message);throw c;};E&&(a.on("message",function(c){a.onmessage({data:c})}),a.on("error",function(c){a.onerror(c)}),a.on("detachedExit",
function(){}));a.postMessage({cmd:"load",urlOrBlob:A.mainScriptUrlOrBlob||_scriptDir,wasmMemory:h,wasmModule:Da})},Ad:function(){var a=ua("ffmpeg-core.worker.js");P.Rb.push(new Worker(a))},Qd:function(){0==P.Rb.length&&(P.Ad(),P.Wd(P.Rb[0]));return P.Rb.pop()}};A.PThread=P;function Va(a){for(;0<a.length;)a.shift()(A)}function Mb(a){var b=W();a=a();X(b);return a}var Nb=[];function Y(a){var b=Nb[a];b||(a>=Nb.length&&(Nb.length=a+1),Nb[a]=b=Pa.get(a));return b}
A.establishStackSpace=function(){var a=Kb(),b=y()[a+44>>2];a=y()[a+48>>2];Ob(b,b-a);X(b)};function Jb(a){if(F)return V(2,0,a);try{Ib(a)}catch(b){b instanceof ma||"unwind"==b||ra(1,b)}}A.invokeEntryPoint=function(a,b){a=Y(a)(b);noExitRuntime?P.sd(a):Pb(a)};function Qb(a,b){e().set(a,b)}function Rb(a,b,c,d){return F?V(3,1,a,b,c,d):Sb(a,b,c,d)}
function Sb(a,b,c,d){if("undefined"==typeof SharedArrayBuffer)return D("Current environment does not support SharedArrayBuffer, pthreads are not available!"),6;var f=[];if(F&&0===f.length)return Rb(a,b,c,d);a={he:c,Db:a,Bd:d,oe:f};return F?(a.re="spawnThread",postMessage(a,f),0):kb(a)}
function Tb(a,b,c,d,f){if(F)return V(4,1,a,b,c,d,f);try{f=0;for(var g=b?y()[b>>2]:0,k=b?y()[b+4>>2]:0,l=c?y()[c>>2]:0,p=c?y()[c+4>>2]:0,r=d?y()[d>>2]:0,q=d?y()[d+4>>2]:0,w=0,B=0,m=0,x=0,u=0,K=0,S=(b?y()[b>>2]:0)|(c?y()[c>>2]:0)|(d?y()[d>>2]:0),fa=(b?y()[b+4>>2]:0)|(c?y()[c+4>>2]:0)|(d?y()[d+4>>2]:0),U=0;U<a;U++){var C=1<<U%32;if(32>U?S&C:fa&C){var Ma=J.vb(U);if(!Ma)throw new J.cb(8);var Na=5;Ma.fb.Wb&&(Na=Ma.fb.Wb(Ma));Na&1&&(32>U?g&C:k&C)&&(32>U?w|=C:B|=C,f++);Na&4&&(32>U?l&C:p&C)&&(32>U?m|=C:x|=
C,f++);Na&2&&(32>U?r&C:q&C)&&(32>U?u|=C:K|=C,f++)}}b&&(y()[b>>2]=w,y()[b+4>>2]=B);c&&(y()[c>>2]=m,y()[c+4>>2]=x);d&&(y()[d>>2]=u,y()[d+4>>2]=K);return f}catch(fb){if("undefined"==typeof J||!(fb instanceof J.cb))throw fb;return-fb.hb}}
var L={jb:function(){A.websocket=A.websocket&&"object"===typeof A.websocket?A.websocket:{};A.websocket.wc={};A.websocket.on=function(a,b){"function"===typeof b&&(this.wc[a]=b);return this};A.websocket.emit=function(a,b){"function"===typeof this.wc[a]&&this.wc[a].call(this,b)};return J.createNode(null,"/",16895,0)},createSocket:function(a,b,c){b&=-526337;if(1==b&&c&&6!=c)throw new J.cb(66);a={family:a,type:b,protocol:c,nb:null,error:null,hc:{},pending:[],Xb:[],sb:L.pb};b=L.qc();c=J.createNode(L.root,
b,49152,0);c.Zb=a;b=J.yc({path:b,node:c,flags:2,seekable:!1,fb:L.fb});a.stream=b;return a},Rd:function(a){return(a=J.vb(a))&&J.isSocket(a.node.mode)?a.node.Zb:null},fb:{Wb:function(a){a=a.node.Zb;return a.sb.Wb(a)},Tb:function(a,b,c){a=a.node.Zb;return a.sb.Tb(a,b,c)},read:function(a,b,c,d){a=a.node.Zb;d=a.sb.od(a,d);if(!d)return 0;b.set(d.buffer,c);return d.buffer.length},write:function(a,b,c,d){a=a.node.Zb;return a.sb.rd(a,b,c,d)},close:function(a){a=a.node.Zb;a.sb.close(a)}},qc:function(){L.qc.current||
(L.qc.current=0);return"socket["+L.qc.current++ +"]"},pb:{kc:function(a,b,c){if("object"==typeof b){var d=b;c=b=null}if(d)if(d._socket)b=d._socket.remoteAddress,c=d._socket.remotePort;else{c=/ws[s]?:\/\/([^:]+):(\d+)/.exec(d.url);if(!c)throw Error("WebSocket URL must be in the format ws(s)://address:port");b=c[1];c=parseInt(c[2],10)}else try{var f=A.websocket&&"object"===typeof A.websocket,g="ws://";f&&"string"===typeof A.websocket.url&&(g=A.websocket.url);if("ws://"===g||"wss://"===g){var k=b.split("/");
g=g+k[0]+":"+c+"/"+k.slice(1).join("/")}k="binary";f&&"string"===typeof A.websocket.subprotocol&&(k=A.websocket.subprotocol);var l=void 0;"null"!==k&&(l=k=k.replace(/^ +| +$/g,"").split(/ *, */));f&&null===A.websocket.subprotocol&&(l=void 0);d=new (E?require("ws"):WebSocket)(g,l);d.binaryType="arraybuffer"}catch(p){throw new J.cb(23);}b={lb:b,port:c,socket:d,lc:[]};L.pb.Tc(a,b);L.pb.Sd(a,b);2===a.type&&"undefined"!=typeof a.Ob&&b.lc.push(new Uint8Array([255,255,255,255,112,111,114,116,(a.Ob&65280)>>
8,a.Ob&255]));return b},mc:function(a,b,c){return a.hc[b+":"+c]},Tc:function(a,b){a.hc[b.lb+":"+b.port]=b},pd:function(a,b){delete a.hc[b.lb+":"+b.port]},Sd:function(a,b){function c(){A.websocket.emit("open",a.stream.fd);try{for(var g=b.lc.shift();g;)b.socket.send(g),g=b.lc.shift()}catch(k){b.socket.close()}}function d(g){if("string"==typeof g)g=(new TextEncoder).encode(g);else{void 0!==g.byteLength||H();if(0==g.byteLength)return;g=new Uint8Array(g)}var k=f;f=!1;k&&10===g.length&&255===g[0]&&255===
g[1]&&255===g[2]&&255===g[3]&&112===g[4]&&111===g[5]&&114===g[6]&&116===g[7]?(g=g[8]<<8|g[9],L.pb.pd(a,b),b.port=g,L.pb.Tc(a,b)):(a.Xb.push({lb:b.lb,port:b.port,data:g}),A.websocket.emit("message",a.stream.fd))}var f=!0;E?(b.socket.on("open",c),b.socket.on("message",function(g,k){k&&d((new Uint8Array(g)).buffer)}),b.socket.on("close",function(){A.websocket.emit("close",a.stream.fd)}),b.socket.on("error",function(){a.error=14;A.websocket.emit("error",[a.stream.fd,a.error,"ECONNREFUSED: Connection refused"])})):
(b.socket.onopen=c,b.socket.onclose=function(){A.websocket.emit("close",a.stream.fd)},b.socket.onmessage=function(g){d(g.data)},b.socket.onerror=function(){a.error=14;A.websocket.emit("error",[a.stream.fd,a.error,"ECONNREFUSED: Connection refused"])})},Wb:function(a){if(1===a.type&&a.nb)return a.pending.length?65:0;var b=0,c=1===a.type?L.pb.mc(a,a.rb,a.tb):null;if(a.Xb.length||!c||c&&c.socket.readyState===c.socket.CLOSING||c&&c.socket.readyState===c.socket.CLOSED)b|=65;if(!c||c&&c.socket.readyState===
c.socket.OPEN)b|=4;if(c&&c.socket.readyState===c.socket.CLOSING||c&&c.socket.readyState===c.socket.CLOSED)b|=16;return b},Tb:function(a,b,c){switch(b){case 21531:return b=0,a.Xb.length&&(b=a.Xb[0].data.length),y()[c>>2]=b,0;default:return 28}},close:function(a){if(a.nb){try{a.nb.close()}catch(f){}a.nb=null}for(var b=Object.keys(a.hc),c=0;c<b.length;c++){var d=a.hc[b[c]];try{d.socket.close()}catch(f){}L.pb.pd(a,d)}return 0},bind:function(a,b,c){if("undefined"!=typeof a.rc||"undefined"!=typeof a.Ob)throw new J.cb(28);
a.rc=b;a.Ob=c;if(2===a.type){a.nb&&(a.nb.close(),a.nb=null);try{a.sb.listen(a,0)}catch(d){if(!(d instanceof J.cb))throw d;if(138!==d.hb)throw d;}}},connect:function(a,b,c){if(a.nb)throw new J.cb(138);if("undefined"!=typeof a.rb&&"undefined"!=typeof a.tb){var d=L.pb.mc(a,a.rb,a.tb);if(d){if(d.socket.readyState===d.socket.CONNECTING)throw new J.cb(7);throw new J.cb(30);}}b=L.pb.kc(a,b,c);a.rb=b.lb;a.tb=b.port;throw new J.cb(26);},listen:function(a){if(!E)throw new J.cb(138);if(a.nb)throw new J.cb(28);
var b=require("ws").Server;a.nb=new b({host:a.rc,port:a.Ob});A.websocket.emit("listen",a.stream.fd);a.nb.on("connection",function(c){if(1===a.type){var d=L.createSocket(a.family,a.type,a.protocol);c=L.pb.kc(d,c);d.rb=c.lb;d.tb=c.port;a.pending.push(d);A.websocket.emit("connection",d.stream.fd)}else L.pb.kc(a,c),A.websocket.emit("connection",a.stream.fd)});a.nb.on("close",function(){A.websocket.emit("close",a.stream.fd);a.nb=null});a.nb.on("error",function(){a.error=23;A.websocket.emit("error",[a.stream.fd,
a.error,"EHOSTUNREACH: Host is unreachable"])})},accept:function(a){if(!a.nb||!a.pending.length)throw new J.cb(28);var b=a.pending.shift();b.stream.flags=a.stream.flags;return b},ye:function(a,b){if(b){if(void 0===a.rb||void 0===a.tb)throw new J.cb(53);b=a.rb;a=a.tb}else b=a.rc||0,a=a.Ob||0;return{lb:b,port:a}},rd:function(a,b,c,d,f,g){if(2===a.type){if(void 0===f||void 0===g)f=a.rb,g=a.tb;if(void 0===f||void 0===g)throw new J.cb(17);}else f=a.rb,g=a.tb;var k=L.pb.mc(a,f,g);if(1===a.type){if(!k||
k.socket.readyState===k.socket.CLOSING||k.socket.readyState===k.socket.CLOSED)throw new J.cb(53);if(k.socket.readyState===k.socket.CONNECTING)throw new J.cb(6);}ArrayBuffer.isView(b)&&(c+=b.byteOffset,b=b.buffer);var l;b instanceof SharedArrayBuffer?l=(new Uint8Array(new Uint8Array(b.slice(c,c+d)))).buffer:l=b.slice(c,c+d);if(2===a.type&&(!k||k.socket.readyState!==k.socket.OPEN))return k&&k.socket.readyState!==k.socket.CLOSING&&k.socket.readyState!==k.socket.CLOSED||(k=L.pb.kc(a,f,g)),k.lc.push(l),
d;try{return k.socket.send(l),d}catch(p){throw new J.cb(28);}},od:function(a,b){if(1===a.type&&a.nb)throw new J.cb(53);var c=a.Xb.shift();if(!c){if(1===a.type){a=L.pb.mc(a,a.rb,a.tb);if(!a)throw new J.cb(53);if(a.socket.readyState===a.socket.CLOSING||a.socket.readyState===a.socket.CLOSED)return null}throw new J.cb(6);}var d=c.data.byteLength||c.data.length,f=c.data.byteOffset||0,g=c.data.buffer||c.data;b=Math.min(b,d);var k={buffer:new Uint8Array(g,f,b),lb:c.lb,port:c.port};1===a.type&&b<d&&(c.data=
new Uint8Array(g,f+b,d-b),a.Xb.unshift(c));return k}}};function Ub(a){a=L.Rd(a);if(!a)throw new J.cb(8);return a}function Vb(a){a=a.split(".");for(var b=0;4>b;b++){var c=Number(a[b]);if(isNaN(c))return null;a[b]=c}return(a[0]|a[1]<<8|a[2]<<16|a[3]<<24)>>>0}
function Wb(a){var b,c,d=[];if(!/^((?=.*::)(?!.*::.+::)(::)?([\dA-F]{1,4}:(:|\b)|){5}|([\dA-F]{1,4}:){6})((([\dA-F]{1,4}((?!\3)::|:\b|$))|(?!\2\3)){2}|(((2[0-4]|1\d|[1-9])?\d|25[0-5])\.?\b){4})$/i.test(a))return null;if("::"===a)return[0,0,0,0,0,0,0,0];a=a.startsWith("::")?a.replace("::","Z:"):a.replace("::",":Z:");0<a.indexOf(".")?(a=a.replace(RegExp("[.]","g"),":"),a=a.split(":"),a[a.length-4]=parseInt(a[a.length-4])+256*parseInt(a[a.length-3]),a[a.length-3]=parseInt(a[a.length-2])+256*parseInt(a[a.length-
1]),a=a.slice(0,a.length-2)):a=a.split(":");for(b=c=0;b<a.length;b++)if("string"==typeof a[b])if("Z"===a[b]){for(c=0;c<8-a.length+1;c++)d[b+c]=0;--c}else d[b+c]=Xb(parseInt(a[b],16));else d[b+c]=a[b];return[d[1]<<16|d[0],d[3]<<16|d[2],d[5]<<16|d[4],d[7]<<16|d[6]]}
function Yb(a,b,c,d,f){switch(b){case 2:c=Vb(c);v().fill(0,a,a+16);f&&(y()[f>>2]=16);ca()[a>>1]=b;y()[a+4>>2]=c;ca()[a+2>>1]=Xb(d);break;case 10:c=Wb(c);v().fill(0,a,a+28);f&&(y()[f>>2]=28);y()[a>>2]=b;y()[a+8>>2]=c[0];y()[a+12>>2]=c[1];y()[a+16>>2]=c[2];y()[a+20>>2]=c[3];ca()[a+2>>1]=Xb(d);break;default:return 5}return 0}var Zb=1,$b={},ac={};
function bc(a){var b=Vb(a);if(null!==b)return a;b=Wb(a);if(null!==b)return a;$b[a]?b=$b[a]:(b=Zb++,65535>b||H("exceeded max address mappings of 65535"),b="172.29."+(b&255)+"."+(b&65280),ac[b]=a,$b[a]=b);return b}function cc(a,b,c,d){if(F)return V(5,1,a,b,c,d);try{var f=Ub(a),g=f.sb.accept(f);b&&Yb(b,g.family,bc(g.rb),g.tb,c);return g.stream.fd}catch(k){if("undefined"==typeof J||!(k instanceof J.cb))throw k;return-k.hb}}function dc(a){return(a&255)+"."+(a>>8&255)+"."+(a>>16&255)+"."+(a>>24&255)}
function ec(a){var b="",c,d=0,f=0,g=0,k=0;a=[a[0]&65535,a[0]>>16,a[1]&65535,a[1]>>16,a[2]&65535,a[2]>>16,a[3]&65535,a[3]>>16];var l=!0;for(c=0;5>c;c++)if(0!==a[c]){l=!1;break}if(l){c=dc(a[6]|a[7]<<16);if(-1===a[5])return"::ffff:"+c;if(0===a[5])return"0.0.0.0"===c&&(c=""),"0.0.0.1"===c&&(c="1"),"::"+c}for(c=0;8>c;c++)0===a[c]&&(1<c-f&&(k=0),f=c,k++),k>d&&(d=k,g=c-d+1);for(c=0;8>c;c++)1<d&&0===a[c]&&c>=g&&c<g+d?c===g&&(b+=":",0===g&&(b+=":")):(b+=Number(fc(a[c]&65535)).toString(16),b+=7>c?":":"");return b}
function gc(a,b){var c=ca()[a>>1],d=fc;h.buffer!=n&&t(h.buffer);d=d(Ka[a+2>>1]);switch(c){case 2:if(16!==b)return{hb:28};a=y()[a+4>>2];a=dc(a);break;case 10:if(28!==b)return{hb:28};a=[y()[a+8>>2],y()[a+12>>2],y()[a+16>>2],y()[a+20>>2]];a=ec(a);break;default:return{hb:5}}return{family:c,lb:a,port:d}}function hc(a,b,c){if(c&&0===a)return null;a=gc(a,b);if(a.hb)throw new J.cb(a.hb);b=a.lb;a.lb=(ac[b]?ac[b]:null)||a.lb;return a}
function ic(a,b,c){if(F)return V(6,1,a,b,c);try{var d=Ub(a),f=hc(b,c);d.sb.bind(d,f.lb,f.port);return 0}catch(g){if("undefined"==typeof J||!(g instanceof J.cb))throw g;return-g.hb}}function jc(a,b,c){if(F)return V(7,1,a,b,c);try{var d=Ub(a),f=hc(b,c);d.sb.connect(d,f.lb,f.port);return 0}catch(g){if("undefined"==typeof J||!(g instanceof J.cb))throw g;return-g.hb}}
function kc(a,b,c,d){if(F)return V(8,1,a,b,c,d);try{b=I(b);b=Cb(a,b);if(c&-8)return-28;var f=J.ib(b,{ub:!0}).node;if(!f)return-44;a="";c&4&&(a+="r");c&2&&(a+="w");c&1&&(a+="x");return a&&J.Hb(f,a)?-2:0}catch(g){if("undefined"==typeof J||!(g instanceof J.cb))throw g;return-g.hb}}
function lc(a,b,c){if(F)return V(9,1,a,b,c);Eb=c;try{var d=Gb(a);switch(b){case 0:var f=Fb();return 0>f?-28:J.yc(d,f).fd;case 1:case 2:return 0;case 3:return d.flags;case 4:return f=Fb(),d.flags|=f,0;case 5:return f=Fb(),ca()[f+0>>1]=2,0;case 6:case 7:return 0;case 16:case 8:return-28;case 9:return y()[mc()>>2]=28,-1;default:return-28}}catch(g){if("undefined"==typeof J||!(g instanceof J.cb))throw g;return-g.hb}}
function nc(a,b){if(F)return V(10,1,a,b);try{var c=Gb(a);return Db(J.stat,c.path,b)}catch(d){if("undefined"==typeof J||!(d instanceof J.cb))throw d;return-d.hb}}
function oc(a,b,c){if(F)return V(11,1,a,b,c);try{var d=Gb(a);d.Ib||(d.Ib=J.readdir(d.path));a=0;for(var f=J.qb(d,0,1),g=Math.floor(f/280);g<d.Ib.length&&a+280<=c;){var k=d.Ib[g];if("."===k){var l=d.node.id;var p=4}else if(".."===k)l=J.ib(d.path,{parent:!0}).node.id,p=4;else{var r=J.xb(d.node,k);l=r.id;p=J.cc(r.mode)?2:J.mb(r.mode)?4:J.Jb(r.mode)?10:8}O=[l>>>0,(N=l,1<=+Math.abs(N)?0<N?(Math.min(+Math.floor(N/4294967296),4294967295)|0)>>>0:~~+Math.ceil((N-+(~~N>>>0))/4294967296)>>>0:0)];y()[b+a>>2]=
O[0];y()[b+a+4>>2]=O[1];O=[280*(g+1)>>>0,(N=280*(g+1),1<=+Math.abs(N)?0<N?(Math.min(+Math.floor(N/4294967296),4294967295)|0)>>>0:~~+Math.ceil((N-+(~~N>>>0))/4294967296)>>>0:0)];y()[b+a+8>>2]=O[0];y()[b+a+12>>2]=O[1];ca()[b+a+16>>1]=280;e()[b+a+18>>0]=p;Ia(k,b+a+19,256);a+=280;g+=1}J.qb(d,280*g,0);return a}catch(q){if("undefined"==typeof J||!(q instanceof J.cb))throw q;return-q.hb}}
function pc(a,b,c){if(F)return V(12,1,a,b,c);try{var d=Ub(a);if(!d.rb)return-53;Yb(b,d.family,bc(d.rb),d.tb,c);return 0}catch(f){if("undefined"==typeof J||!(f instanceof J.cb))throw f;return-f.hb}}function qc(a,b,c){if(F)return V(13,1,a,b,c);try{D("__syscall_getsockname "+a);var d=Ub(a);Yb(b,d.family,bc(d.rc||"0.0.0.0"),d.Ob,c);return 0}catch(f){if("undefined"==typeof J||!(f instanceof J.cb))throw f;return-f.hb}}
function rc(a,b,c,d,f){if(F)return V(14,1,a,b,c,d,f);try{var g=Ub(a);return 1===b&&4===c?(y()[d>>2]=g.error,y()[f>>2]=4,g.error=null,0):-50}catch(k){if("undefined"==typeof J||!(k instanceof J.cb))throw k;return-k.hb}}
function sc(a,b,c){if(F)return V(15,1,a,b,c);Eb=c;try{var d=Gb(a);switch(b){case 21509:case 21505:return d.tty?0:-59;case 21510:case 21511:case 21512:case 21506:case 21507:case 21508:return d.tty?0:-59;case 21519:if(!d.tty)return-59;var f=Fb();return y()[f>>2]=0;case 21520:return d.tty?-28:-59;case 21531:return f=Fb(),J.Tb(d,b,f);case 21523:return d.tty?0:-59;case 21524:return d.tty?0:-59;default:return-28}}catch(g){if("undefined"==typeof J||!(g instanceof J.cb))throw g;return-g.hb}}
function tc(a,b){if(F)return V(16,1,a,b);try{var c=Ub(a);c.sb.listen(c,b);return 0}catch(d){if("undefined"==typeof J||!(d instanceof J.cb))throw d;return-d.hb}}function uc(a,b){if(F)return V(17,1,a,b);try{return a=I(a),Db(J.lstat,a,b)}catch(c){if("undefined"==typeof J||!(c instanceof J.cb))throw c;return-c.hb}}
function vc(a,b,c){if(F)return V(18,1,a,b,c);try{return b=I(b),b=Cb(a,b),b=Q(b),"/"===b[b.length-1]&&(b=b.substr(0,b.length-1)),J.mkdir(b,c,0),0}catch(d){if("undefined"==typeof J||!(d instanceof J.cb))throw d;return-d.hb}}function wc(a,b,c,d){if(F)return V(19,1,a,b,c,d);try{b=I(b);var f=d&256;b=Cb(a,b,d&4096);return Db(f?J.lstat:J.stat,b,c)}catch(g){if("undefined"==typeof J||!(g instanceof J.cb))throw g;return-g.hb}}
function xc(a,b,c,d){if(F)return V(20,1,a,b,c,d);Eb=d;try{b=I(b);b=Cb(a,b);var f=d?Fb():0;return J.open(b,c,f).fd}catch(g){if("undefined"==typeof J||!(g instanceof J.cb))throw g;return-g.hb}}function yc(a,b,c){if(F)return V(21,1,a,b,c);try{for(var d=c=0;d<b;d++){var f=a+8*d,g=y()[f>>2],k=ca()[f+4>>1],l=32,p=J.vb(g);p&&(l=5,p.fb.Wb&&(l=p.fb.Wb(p)));(l&=k|24)&&c++;ca()[f+6>>1]=l}return c}catch(r){if("undefined"==typeof J||!(r instanceof J.cb))throw r;return-r.hb}}
function zc(a,b,c,d,f,g){if(F)return V(22,1,a,b,c,d,f,g);try{var k=Ub(a),l=k.sb.od(k,c);if(!l)return 0;f&&Yb(f,k.family,bc(l.lb),l.port,g);v().set(l.buffer,b);return l.buffer.byteLength}catch(p){if("undefined"==typeof J||!(p instanceof J.cb))throw p;return-p.hb}}function Ac(a,b,c,d){if(F)return V(23,1,a,b,c,d);try{return b=I(b),d=I(d),b=Cb(a,b),d=Cb(c,d),J.rename(b,d),0}catch(f){if("undefined"==typeof J||!(f instanceof J.cb))throw f;return-f.hb}}
function Bc(a){if(F)return V(24,1,a);try{return a=I(a),J.rmdir(a),0}catch(b){if("undefined"==typeof J||!(b instanceof J.cb))throw b;return-b.hb}}function Cc(a,b,c,d,f,g){if(F)return V(25,1,a,b,c,d,f,g);try{var k=Ub(a),l=hc(f,g,!0);return l?k.sb.rd(k,e(),b,c,l.lb,l.port):J.write(k.stream,e(),b,c)}catch(p){if("undefined"==typeof J||!(p instanceof J.cb))throw p;return-p.hb}}
function Dc(a,b,c){if(F)return V(26,1,a,b,c);try{return L.createSocket(a,b,c).stream.fd}catch(d){if("undefined"==typeof J||!(d instanceof J.cb))throw d;return-d.hb}}function Ec(a,b){if(F)return V(27,1,a,b);try{return a=I(a),Db(J.stat,a,b)}catch(c){if("undefined"==typeof J||!(c instanceof J.cb))throw c;return-c.hb}}
function Fc(a,b,c){if(F)return V(28,1,a,b,c);try{return b=I(b),b=Cb(a,b),0===c?J.unlink(b):512===c?J.rmdir(b):H("Invalid flags passed to unlinkat"),0}catch(d){if("undefined"==typeof J||!(d instanceof J.cb))throw d;return-d.hb}}function Lb(a){Atomics.store(y(),a>>2,1);Kb()&&Gc(a);Atomics.compareExchange(y(),a>>2,1,0)}A.executeNotifiedProxyingQueue=Lb;function Hc(a){return z()[a>>2]+4294967296*y()[a+4>>2]}
function Ic(a,b,c,d,f,g){if(F)return V(29,1,a,b,c,d,f,g);try{var k=J.vb(d);if(!k)return-8;var l=J.Mb(k,a,f,b,c),p=l.nd;y()[g>>2]=l.Uc;return p}catch(r){if("undefined"==typeof J||!(r instanceof J.cb))throw r;return-r.hb}}function Jc(a,b,c,d,f,g){if(F)return V(30,1,a,b,c,d,f,g);try{var k=J.vb(f);if(k&&c&2){var l=v().slice(a,a+b);J.Ub(k,l,g,b,d)}}catch(p){if("undefined"==typeof J||!(p instanceof J.cb))throw p;return-p.hb}}function Kc(a){var b=Ja(a)+1,c=Lc(b);c&&Ha(a,e(),c,b);return c}
function Mc(a,b,c){function d(r){return(r=r.toTimeString().match(/\(([A-Za-z ]+)\)$/))?r[1]:"GMT"}if(F)return V(31,1,a,b,c);var f=(new Date).getFullYear(),g=new Date(f,0,1),k=new Date(f,6,1);f=g.getTimezoneOffset();var l=k.getTimezoneOffset(),p=Math.max(f,l);y()[a>>2]=60*p;y()[b>>2]=Number(f!=l);a=d(g);b=d(k);a=Kc(a);b=Kc(b);l<f?(z()[c>>2]=a,z()[c+4>>2]=b):(z()[c>>2]=b,z()[c+4>>2]=a)}function Nc(a,b,c){Nc.Cd||(Nc.Cd=!0,Mc(a,b,c))}var Oc,Pc;
Pc=E?()=>{var a=process.hrtime();return 1E3*a[0]+a[1]/1E6}:F?()=>performance.now()-A.__performance_now_clock_drift:()=>performance.now();function V(a,b){var c=arguments.length-2,d=arguments;return Mb(()=>{for(var f=Qc(8*c),g=f>>3,k=0;k<c;k++){var l=d[2+k];ia()[g+k]=l}return Rc(a,c,f,b)})}var Sc=[],Tc={};
function Uc(){if(!Vc){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"==typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:qa||"./this.program"},b;for(b in Tc)void 0===Tc[b]?delete a[b]:a[b]=Tc[b];var c=[];for(b in a)c.push(b+"="+a[b]);Vc=c}return Vc}var Vc;function Wc(a,b,c){for(var d=0;d<a.length;++d)e()[b++>>0]=a.charCodeAt(d);c||(e()[b>>0]=0)}
function Xc(a,b){if(F)return V(32,1,a,b);var c=0;Uc().forEach(function(d,f){var g=b+c;z()[a+4*f>>2]=g;Wc(d,g);c+=d.length+1});return 0}function Yc(a,b){if(F)return V(33,1,a,b);var c=Uc();z()[a>>2]=c.length;var d=0;c.forEach(function(f){d+=f.length+1});z()[b>>2]=d;return 0}function Zc(a){if(F)return V(34,1,a);try{var b=Gb(a);J.close(b);return 0}catch(c){if("undefined"==typeof J||!(c instanceof J.cb))throw c;return c.hb}}
function $c(a,b){if(F)return V(35,1,a,b);try{var c=Gb(a),d=c.tty?2:J.mb(c.mode)?3:J.Jb(c.mode)?7:4;e()[b>>0]=d;return 0}catch(f){if("undefined"==typeof J||!(f instanceof J.cb))throw f;return f.hb}}
function ad(a,b,c,d){if(F)return V(36,1,a,b,c,d);try{a:{var f=Gb(a);a=b;for(var g=b=0;g<c;g++){var k=z()[a>>2],l=z()[a+4>>2];a+=8;var p=J.read(f,e(),k,l,void 0);if(0>p){var r=-1;break a}b+=p;if(p<l)break}r=b}z()[d>>2]=r;return 0}catch(q){if("undefined"==typeof J||!(q instanceof J.cb))throw q;return q.hb}}
function bd(a,b,c,d,f){if(F)return V(37,1,a,b,c,d,f);try{b=c+2097152>>>0<4194305-!!b?(b>>>0)+4294967296*c:NaN;if(isNaN(b))return 61;var g=Gb(a);J.qb(g,b,d);O=[g.position>>>0,(N=g.position,1<=+Math.abs(N)?0<N?(Math.min(+Math.floor(N/4294967296),4294967295)|0)>>>0:~~+Math.ceil((N-+(~~N>>>0))/4294967296)>>>0:0)];y()[f>>2]=O[0];y()[f+4>>2]=O[1];g.Ib&&0===b&&0===d&&(g.Ib=null);return 0}catch(k){if("undefined"==typeof J||!(k instanceof J.cb))throw k;return k.hb}}
function cd(a,b,c,d){if(F)return V(38,1,a,b,c,d);try{a:{var f=Gb(a);a=b;for(var g=b=0;g<c;g++){var k=z()[a>>2],l=z()[a+4>>2];a+=8;var p=J.write(f,e(),k,l,void 0);if(0>p){var r=-1;break a}b+=p}r=b}z()[d>>2]=r;return 0}catch(q){if("undefined"==typeof J||!(q instanceof J.cb))throw q;return q.hb}}var dd=0;
function ed(a,b,c,d){function f(w,B,m,x,u,K){var S=10===w?28:16;u=10===w?ec(u):dc(u);S=Lc(S);!Yb(S,w,u,K)||H();u=Lc(32);y()[u+4>>2]=w;y()[u+8>>2]=B;y()[u+12>>2]=m;y()[u+24>>2]=x;z()[u+20>>2]=S;10===w?y()[u+16>>2]=28:y()[u+16>>2]=16;y()[u+28>>2]=0;return u}if(F)return V(39,1,a,b,c,d);var g=0,k=0,l=0,p=0,r=0,q=0;c&&(l=y()[c>>2],p=y()[c+4>>2],r=y()[c+8>>2],q=y()[c+12>>2]);r&&!q&&(q=2===r?17:6);!r&&q&&(r=17===q?2:1);0===q&&(q=6);0===r&&(r=1);if(!a&&!b)return-2;if(l&-1088||0!==c&&y()[c>>2]&2&&!a)return-1;
if(l&32)return-2;if(0!==r&&1!==r&&2!==r)return-7;if(0!==p&&2!==p&&10!==p)return-6;if(b&&(b=I(b),k=parseInt(b,10),isNaN(k)))return l&1024?-2:-8;if(!a)return 0===p&&(p=2),0===(l&1)&&(2===p?g=fd(2130706433):g=[0,0,0,1]),a=f(p,r,q,null,g,k),z()[d>>2]=a,0;a=I(a);g=Vb(a);if(null!==g)if(0===p||2===p)p=2;else if(10===p&&l&8)g=[0,0,fd(65535),g],p=10;else return-2;else if(g=Wb(a),null!==g)if(0===p||10===p)p=10;else return-2;if(null!=g)return a=f(p,r,q,a,g,k),z()[d>>2]=a,0;if(l&4)return-2;a=bc(a);g=Vb(a);0===
p?p=2:10===p&&(g=[0,0,fd(65535),g]);a=f(p,r,q,null,g,k);z()[d>>2]=a;return 0}function gd(a){return 0===a%4&&(0!==a%100||0===a%400)}var hd=[31,29,31,30,31,30,31,31,30,31,30,31],jd=[31,28,31,30,31,30,31,31,30,31,30,31];
function kd(a,b,c,d){var f={string:r=>{var q=0;if(null!==r&&void 0!==r&&0!==r){var w=(r.length<<2)+1;q=Qc(w);Ia(r,q,w)}return q},array:r=>{var q=Qc(r.length);Qb(r,q);return q}};a=A["_"+a];var g=[],k=0;if(d)for(var l=0;l<d.length;l++){var p=f[c[l]];p?(0===k&&(k=W()),g[l]=p(d[l])):g[l]=d[l]}c=a.apply(null,g);return c=function(r){0!==k&&X(k);return"string"===b?I(r):"boolean"===b?!!r:r}(c)}P.Sb();
function ld(a,b,c,d){a||(a=this);this.parent=a;this.jb=a.jb;this.ec=null;this.id=J.$d++;this.name=b;this.mode=c;this.eb={};this.fb={};this.rdev=d}Object.defineProperties(ld.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(a){a?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(a){a?this.mode|=146:this.mode&=-147}},Vd:{get:function(){return J.mb(this.mode)}},Gc:{get:function(){return J.cc(this.mode)}}});J.wd=ld;J.ie();var Bb;
A.FS_mount=J.jb;A.FS_unmount=J.qe;A.FS_filesystems=J.cd;
var md=[null,Hb,Jb,Rb,Tb,cc,ic,jc,kc,lc,nc,oc,pc,qc,rc,sc,tc,uc,vc,wc,xc,yc,zc,Ac,Bc,Cc,Dc,Ec,Fc,Ic,Jc,Mc,Xc,Yc,Zc,$c,ad,bd,cd,ed],Ed={c:function(a,b,c,d){H("Assertion failed: "+I(a)+", at: "+[b?I(b):"unknown filename",c,d?I(d):"unknown function"])},ka:function(a){nd(a,!ta,1,!sa);P.ud()},z:function(a){F?postMessage({cmd:"cleanupThread",thread:a}):jb(a)},da:Sb,ca:function(a,b){33===b?F?postMessage({cmd:"cancelThread",thread:a}):ib(a):F?postMessage({cmd:"killThread",thread:a}):gb(a);return 0},_:Tb,
U:cc,T:ic,S:jc,Ca:kc,k:lc,ta:nc,ba:oc,R:pc,Q:qc,P:rc,F:sc,O:tc,qa:uc,ja:vc,ra:wc,B:xc,ga:yc,N:zc,aa:Ac,$:Bc,M:Cc,y:Dc,sa:Ec,X:Fc,Aa:function(){},D:function(){H("To use dlopen, you need enable dynamic linking, see https://github.com/emscripten-core/emscripten/wiki/Linking")},Ba:function(){H("To use dlopen, you need enable dynamic linking, see https://github.com/emscripten-core/emscripten/wiki/Linking")},r:function(){return Date.now()},ea:function(){return 2097152},ua:function(){return!0},fa:function(a,
b,c,d){if(a==b)setTimeout(()=>Lb(d));else if(F)postMessage({targetThread:a,cmd:"processProxyingQueue",queue:d});else{a=P.Eb[a];if(!a)return;a.postMessage({cmd:"processProxyingQueue",queue:d})}return 1},ma:function(){return-1},V:function(){throw Infinity;},va:function(a,b){a=new Date(1E3*Hc(a));y()[b>>2]=a.getUTCSeconds();y()[b+4>>2]=a.getUTCMinutes();y()[b+8>>2]=a.getUTCHours();y()[b+12>>2]=a.getUTCDate();y()[b+16>>2]=a.getUTCMonth();y()[b+20>>2]=a.getUTCFullYear()-1900;y()[b+24>>2]=a.getUTCDay();
a=(a.getTime()-Date.UTC(a.getUTCFullYear(),0,1,0,0,0,0))/864E5|0;y()[b+28>>2]=a},wa:function(a,b){a=new Date(1E3*Hc(a));y()[b>>2]=a.getSeconds();y()[b+4>>2]=a.getMinutes();y()[b+8>>2]=a.getHours();y()[b+12>>2]=a.getDate();y()[b+16>>2]=a.getMonth();y()[b+20>>2]=a.getFullYear()-1900;y()[b+24>>2]=a.getDay();var c=new Date(a.getFullYear(),0,1),d=(a.getTime()-c.getTime())/864E5|0;y()[b+28>>2]=d;y()[b+36>>2]=-(60*a.getTimezoneOffset());d=(new Date(a.getFullYear(),6,1)).getTimezoneOffset();c=c.getTimezoneOffset();
a=(d!=c&&a.getTimezoneOffset()==Math.min(c,d))|0;y()[b+32>>2]=a},xa:function(a){var b=new Date(y()[a+20>>2]+1900,y()[a+16>>2],y()[a+12>>2],y()[a+8>>2],y()[a+4>>2],y()[a>>2],0),c=y()[a+32>>2],d=b.getTimezoneOffset(),f=new Date(b.getFullYear(),0,1),g=(new Date(b.getFullYear(),6,1)).getTimezoneOffset(),k=f.getTimezoneOffset(),l=Math.min(k,g);0>c?y()[a+32>>2]=Number(g!=k&&l==d):0<c!=(l==d)&&(g=Math.max(k,g),b.setTime(b.getTime()+6E4*((0<c?l:g)-d)));y()[a+24>>2]=b.getDay();c=(b.getTime()-f.getTime())/
864E5|0;y()[a+28>>2]=c;y()[a>>2]=b.getSeconds();y()[a+4>>2]=b.getMinutes();y()[a+8>>2]=b.getHours();y()[a+12>>2]=b.getDate();y()[a+16>>2]=b.getMonth();return b.getTime()/1E3|0},ha:Ic,ia:Jc,ya:Nc,b:function(){H("")},A:function(){if(!E&&!ta){var a="Blocking on the main thread is very dangerous, see https://emscripten.org/docs/porting/pthreads.html#blocking-on-the-main-browser-thread";Oc||(Oc={});Oc[a]||(Oc[a]=1,E&&(a="warning: "+a),D(a))}},Y:function(){return 2146435072},l:Pc,za:function(a,b,c){v().copyWithin(a,
b,b+c)},Z:function(){return E?require("os").cpus().length:navigator.hardwareConcurrency},la:function(a,b,c){Sc.length=b;c>>=3;for(var d=0;d<b;d++)Sc[d]=ia()[c+d];return(0>a?eb[-a-1]:md[a]).apply(null,Sc)},W:function(a){var b=v().length;a>>>=0;if(a<=b||2146435072<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);var f=Math;d=Math.max(a,d);f=f.min.call(f,2146435072,d+(65536-d%65536)%65536);a:{try{h.grow(f-n.byteLength+65535>>>16);t(h.buffer);var g=1;break a}catch(k){}g=void 0}if(g)return!0}return!1},
Da:function(){return noExitRuntime},C:function(){throw"unwind";},oa:Xc,pa:Yc,o:Ib,s:Zc,na:$c,E:ad,J:bd,u:cd,d:function(){return dd},p:ed,n:function(a,b,c,d,f,g,k){b=gc(a,b);if(b.hb)return-6;a=b.port;var l=b.lb;b=!1;if(c&&d){var p;if(k&1||!(p=ac[l]?ac[l]:null)){if(k&8)return-2}else l=p;c=Ia(l,c,d);c+1>=d&&(b=!0)}f&&g&&(c=Ia(""+a,f,g),c+1>=g&&(b=!0));return b?-12:0},I:od,j:pd,g:qd,q:rd,x:sd,G:td,w:ud,L:vd,K:wd,h:xd,m:yd,t:zd,f:Ad,v:Bd,Ea:Cd,H:Dd,a:h||A.wasmMemory,e:function(a){dd=a},i:function(a,b,
c,d){function f(m,x,u){for(m="number"==typeof m?m.toString():m||"";m.length<x;)m=u[0]+m;return m}function g(m,x){return f(m,x,"0")}function k(m,x){function u(S){return 0>S?-1:0<S?1:0}var K;0===(K=u(m.getFullYear()-x.getFullYear()))&&0===(K=u(m.getMonth()-x.getMonth()))&&(K=u(m.getDate()-x.getDate()));return K}function l(m){switch(m.getDay()){case 0:return new Date(m.getFullYear()-1,11,29);case 1:return m;case 2:return new Date(m.getFullYear(),0,3);case 3:return new Date(m.getFullYear(),0,2);case 4:return new Date(m.getFullYear(),
0,1);case 5:return new Date(m.getFullYear()-1,11,31);case 6:return new Date(m.getFullYear()-1,11,30)}}function p(m){var x=m.Pb;for(m=new Date((new Date(m.Qb+1900,0,1)).getTime());0<x;){var u=m.getMonth(),K=(gd(m.getFullYear())?hd:jd)[u];if(x>K-m.getDate())x-=K-m.getDate()+1,m.setDate(1),11>u?m.setMonth(u+1):(m.setMonth(0),m.setFullYear(m.getFullYear()+1));else{m.setDate(m.getDate()+x);break}}u=new Date(m.getFullYear()+1,0,4);x=l(new Date(m.getFullYear(),0,4));u=l(u);return 0>=k(x,m)?0>=k(u,m)?m.getFullYear()+
1:m.getFullYear():m.getFullYear()-1}var r=y()[d+40>>2];d={me:y()[d>>2],le:y()[d+4>>2],tc:y()[d+8>>2],Qc:y()[d+12>>2],uc:y()[d+16>>2],Qb:y()[d+20>>2],Bb:y()[d+24>>2],Pb:y()[d+28>>2],Ie:y()[d+32>>2],ke:y()[d+36>>2],ne:r?I(r):""};c=I(c);r={"%c":"%a %b %d %H:%M:%S %Y","%D":"%m/%d/%y","%F":"%Y-%m-%d","%h":"%b","%r":"%I:%M:%S %p","%R":"%H:%M","%T":"%H:%M:%S","%x":"%m/%d/%y","%X":"%H:%M:%S","%Ec":"%c","%EC":"%C","%Ex":"%m/%d/%y","%EX":"%H:%M:%S","%Ey":"%y","%EY":"%Y","%Od":"%d","%Oe":"%e","%OH":"%H","%OI":"%I",
"%Om":"%m","%OM":"%M","%OS":"%S","%Ou":"%u","%OU":"%U","%OV":"%V","%Ow":"%w","%OW":"%W","%Oy":"%y"};for(var q in r)c=c.replace(new RegExp(q,"g"),r[q]);var w="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),B="January February March April May June July August September October November December".split(" ");r={"%a":function(m){return w[m.Bb].substring(0,3)},"%A":function(m){return w[m.Bb]},"%b":function(m){return B[m.uc].substring(0,3)},"%B":function(m){return B[m.uc]},"%C":function(m){return g((m.Qb+
1900)/100|0,2)},"%d":function(m){return g(m.Qc,2)},"%e":function(m){return f(m.Qc,2," ")},"%g":function(m){return p(m).toString().substring(2)},"%G":function(m){return p(m)},"%H":function(m){return g(m.tc,2)},"%I":function(m){m=m.tc;0==m?m=12:12<m&&(m-=12);return g(m,2)},"%j":function(m){for(var x=0,u=0;u<=m.uc-1;x+=(gd(m.Qb+1900)?hd:jd)[u++]);return g(m.Qc+x,3)},"%m":function(m){return g(m.uc+1,2)},"%M":function(m){return g(m.le,2)},"%n":function(){return"\n"},"%p":function(m){return 0<=m.tc&&12>
m.tc?"AM":"PM"},"%S":function(m){return g(m.me,2)},"%t":function(){return"\t"},"%u":function(m){return m.Bb||7},"%U":function(m){return g(Math.floor((m.Pb+7-m.Bb)/7),2)},"%V":function(m){var x=Math.floor((m.Pb+7-(m.Bb+6)%7)/7);2>=(m.Bb+371-m.Pb-2)%7&&x++;if(x)53==x&&(u=(m.Bb+371-m.Pb)%7,4==u||3==u&&gd(m.Qb)||(x=1));else{x=52;var u=(m.Bb+7-m.Pb-1)%7;(4==u||5==u&&gd(m.Qb%400-1))&&x++}return g(x,2)},"%w":function(m){return m.Bb},"%W":function(m){return g(Math.floor((m.Pb+7-(m.Bb+6)%7)/7),2)},"%y":function(m){return(m.Qb+
1900).toString().substring(2)},"%Y":function(m){return m.Qb+1900},"%z":function(m){m=m.ke;var x=0<=m;m=Math.abs(m)/60;return(x?"+":"-")+String("0000"+(m/60*100+m%60)).slice(-4)},"%Z":function(m){return m.ne},"%%":function(){return"%"}};c=c.replace(/%%/g,"\x00\x00");for(q in r)c.includes(q)&&(c=c.replace(new RegExp(q,"g"),r[q](d)));c=c.replace(/\0\0/g,"%");q=sb(c,!1);if(q.length>b)return 0;Qb(q,a);return q.length-1}};
(function(){function a(f,g){A.asm=f.exports;P.vd.push(A.asm.Ma);Pa=A.asm.Ha;Ra.unshift(A.asm.Fa);Da=g;F||ab()}function b(f){a(f.instance,f.module)}function c(f){return db().then(function(g){return WebAssembly.instantiate(g,d)}).then(function(g){return g}).then(f,function(g){D("failed to asynchronously prepare wasm: "+g);H(g)})}var d={a:Ed};F||$a();if(A.instantiateWasm)try{return A.instantiateWasm(d,a)}catch(f){return D("Module.instantiateWasm callback failed with error: "+f),!1}(function(){return Ca||
"function"!=typeof WebAssembly.instantiateStreaming||bb()||M.startsWith("file://")||E||"function"!=typeof fetch?c(b):fetch(M,{credentials:"same-origin"}).then(function(f){return WebAssembly.instantiateStreaming(f,d).then(b,function(g){D("wasm streaming compile failed: "+g);D("falling back to ArrayBuffer instantiation");return c(b)})})})().catch(la);return{}})();A.___wasm_call_ctors=function(){return(A.___wasm_call_ctors=A.asm.Fa).apply(null,arguments)};
var Lc=A._malloc=function(){return(Lc=A._malloc=A.asm.Ga).apply(null,arguments)},mc=A.___errno_location=function(){return(mc=A.___errno_location=A.asm.Ia).apply(null,arguments)},fc=A._ntohs=function(){return(fc=A._ntohs=A.asm.Ja).apply(null,arguments)},Xb=A._htons=function(){return(Xb=A._htons=A.asm.Ka).apply(null,arguments)};A._main=function(){return(A._main=A.asm.La).apply(null,arguments)};A.__emscripten_tls_init=function(){return(A.__emscripten_tls_init=A.asm.Ma).apply(null,arguments)};
var Kb=A._pthread_self=function(){return(Kb=A._pthread_self=A.asm.Na).apply(null,arguments)},zb=A._emscripten_builtin_memalign=function(){return(zb=A._emscripten_builtin_memalign=A.asm.Oa).apply(null,arguments)};A.__emscripten_proxy_main=function(){return(A.__emscripten_proxy_main=A.asm.Pa).apply(null,arguments)};var nd=A.__emscripten_thread_init=function(){return(nd=A.__emscripten_thread_init=A.asm.Qa).apply(null,arguments)};
A.__emscripten_thread_crashed=function(){return(A.__emscripten_thread_crashed=A.asm.Ra).apply(null,arguments)};
var fd=A._htonl=function(){return(fd=A._htonl=A.asm.Sa).apply(null,arguments)},Rc=A._emscripten_run_in_main_runtime_thread_js=function(){return(Rc=A._emscripten_run_in_main_runtime_thread_js=A.asm.Ta).apply(null,arguments)},Gc=A.__emscripten_proxy_execute_task_queue=function(){return(Gc=A.__emscripten_proxy_execute_task_queue=A.asm.Ua).apply(null,arguments)},hb=A.__emscripten_thread_free_data=function(){return(hb=A.__emscripten_thread_free_data=A.asm.Va).apply(null,arguments)},Pb=A.__emscripten_thread_exit=
function(){return(Pb=A.__emscripten_thread_exit=A.asm.Wa).apply(null,arguments)},Z=A._setThrew=function(){return(Z=A._setThrew=A.asm.Xa).apply(null,arguments)},Ob=A._emscripten_stack_set_limits=function(){return(Ob=A._emscripten_stack_set_limits=A.asm.Ya).apply(null,arguments)},W=A.stackSave=function(){return(W=A.stackSave=A.asm.Za).apply(null,arguments)},X=A.stackRestore=function(){return(X=A.stackRestore=A.asm._a).apply(null,arguments)},Qc=A.stackAlloc=function(){return(Qc=A.stackAlloc=A.asm.$a).apply(null,
arguments)},Fd=A.dynCall_iiiijj=function(){return(Fd=A.dynCall_iiiijj=A.asm.ab).apply(null,arguments)},Gd=A.dynCall_iij=function(){return(Gd=A.dynCall_iij=A.asm.bb).apply(null,arguments)};A._ff_h264_cabac_tables=2564460;function qd(a,b,c){var d=W();try{return Y(a)(b,c)}catch(f){X(d);if(f!==f+0)throw f;Z(1,0)}}function xd(a,b){var c=W();try{Y(a)(b)}catch(d){X(c);if(d!==d+0)throw d;Z(1,0)}}function Ad(a,b,c,d,f){var g=W();try{Y(a)(b,c,d,f)}catch(k){X(g);if(k!==k+0)throw k;Z(1,0)}}
function yd(a,b,c){var d=W();try{Y(a)(b,c)}catch(f){X(d);if(f!==f+0)throw f;Z(1,0)}}function pd(a,b){var c=W();try{return Y(a)(b)}catch(d){X(c);if(d!==d+0)throw d;Z(1,0)}}function sd(a,b,c,d,f){var g=W();try{return Y(a)(b,c,d,f)}catch(k){X(g);if(k!==k+0)throw k;Z(1,0)}}function ud(a,b,c,d,f,g,k,l,p){var r=W();try{return Y(a)(b,c,d,f,g,k,l,p)}catch(q){X(r);if(q!==q+0)throw q;Z(1,0)}}function zd(a,b,c,d){var f=W();try{Y(a)(b,c,d)}catch(g){X(f);if(g!==g+0)throw g;Z(1,0)}}
function od(a){var b=W();try{return Y(a)()}catch(c){X(b);if(c!==c+0)throw c;Z(1,0)}}function Bd(a,b,c,d,f,g){var k=W();try{Y(a)(b,c,d,f,g)}catch(l){X(k);if(l!==l+0)throw l;Z(1,0)}}function rd(a,b,c,d){var f=W();try{return Y(a)(b,c,d)}catch(g){X(f);if(g!==g+0)throw g;Z(1,0)}}function Dd(a,b,c,d,f,g,k,l,p){var r=W();try{Y(a)(b,c,d,f,g,k,l,p)}catch(q){X(r);if(q!==q+0)throw q;Z(1,0)}}function td(a,b,c,d,f,g){var k=W();try{return Y(a)(b,c,d,f,g)}catch(l){X(k);if(l!==l+0)throw l;Z(1,0)}}
function Cd(a,b,c,d,f,g,k){var l=W();try{Y(a)(b,c,d,f,g,k)}catch(p){X(l);if(p!==p+0)throw p;Z(1,0)}}function vd(a,b,c,d,f,g,k,l){var p=W();try{return Fd(a,b,c,d,f,g,k,l)}catch(r){X(p);if(r!==r+0)throw r;Z(1,0)}}function wd(a,b,c,d){var f=W();try{return Gd(a,b,c,d)}catch(g){X(f);if(g!==g+0)throw g;Z(1,0)}}A.UTF8ToString=I;A.stringToUTF8=Ia;A.lengthBytesUTF8=Ja;A.keepRuntimeAlive=function(){return noExitRuntime};A.wasmMemory=h;A.ccall=kd;
A.cwrap=function(a,b,c,d){c=c||[];var f=c.every(g=>"number"===g||"boolean"===g);return"string"!==b&&f&&!d?A["_"+a]:function(){return kd(a,b,c,arguments,d)}};
A.setValue=function(a,b,c="i8"){c.endsWith("*")&&(c="*");switch(c){case "i1":e()[a>>0]=b;break;case "i8":e()[a>>0]=b;break;case "i16":ca()[a>>1]=b;break;case "i32":y()[a>>2]=b;break;case "i64":O=[b>>>0,(N=b,1<=+Math.abs(N)?0<N?(Math.min(+Math.floor(N/4294967296),4294967295)|0)>>>0:~~+Math.ceil((N-+(~~N>>>0))/4294967296)>>>0:0)];y()[a>>2]=O[0];y()[a+4>>2]=O[1];break;case "float":h.buffer!=n&&t(h.buffer);La[a>>2]=b;break;case "double":ia()[a>>3]=b;break;case "*":z()[a>>2]=b;break;default:H("invalid type for setValue: "+
c)}};A.writeAsciiToMemory=Wc;A.ExitStatus=ma;A.FS=J;A.PThread=P;var Hd;Za=function Id(){Hd||Jd();Hd||(Za=Id)};function Kd(a){var b=A.__emscripten_proxy_main;a=a||[];a.unshift(qa);var c=a.length,d=Qc(4*(c+1)),f=d>>2;a.forEach(g=>{var k=y(),l=f++,p=Ja(g)+1,r=Qc(p);Ha(g,e(),r,p);k[l]=r});y()[f]=0;b(c,d)}
function Jd(){function a(){if(!Hd&&(Hd=!0,A.calledRun=!0,!Ea)){Ua();F||Va(Sa);ka(A);if(A.onRuntimeInitialized)A.onRuntimeInitialized();Ld&&Kd(b);if(!F){if(A.postRun)for("function"==typeof A.postRun&&(A.postRun=[A.postRun]);A.postRun.length;){var c=A.postRun.shift();Ta.unshift(c)}Va(Ta)}}}var b=b||pa;if(!(0<Xa))if(F)ka(A),Ua(),postMessage({cmd:"loaded"});else{if(A.preRun)for("function"==typeof A.preRun&&(A.preRun=[A.preRun]);A.preRun.length;)Wa();Va(Qa);0<Xa||(A.setStatus?(A.setStatus("Running..."),
setTimeout(function(){setTimeout(function(){A.setStatus("")},1);a()},1)):a())}}if(A.preInit)for("function"==typeof A.preInit&&(A.preInit=[A.preInit]);0<A.preInit.length;)A.preInit.pop()();var Ld=!1;A.noInitialRun&&(Ld=!1);Jd();A.runningWorkers=P.Yb;


  return createFFmpegCore.ready
}
);
})();
if (typeof exports === 'object' && typeof module === 'object')
  module.exports = createFFmpegCore;
else if (typeof define === 'function' && define['amd'])
  define([], function() { return createFFmpegCore; });
else if (typeof exports === 'object')
  exports["createFFmpegCore"] = createFFmpegCore;
